/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.NoweSrodkiTransportu;
import pl.nip24.client.model.PMarzy;
import pl.nip24.client.model.Zwolnienie;
/**
 * Inne adnotacje na fakturze
 */
@Schema(description = "Inne adnotacje na fakturze")

public class Adnotacje {
  @JsonProperty("P_16")
  private Integer p16 = null;

  @JsonProperty("P_17")
  private Integer p17 = null;

  @JsonProperty("P_18")
  private Integer p18 = null;

  @JsonProperty("P_18A")
  private Integer p18A = null;

  @JsonProperty("Zwolnienie")
  private Zwolnienie zwolnienie = null;

  @JsonProperty("NoweSrodkiTransportu")
  private NoweSrodkiTransportu noweSrodkiTransportu = null;

  @JsonProperty("P_23")
  private Integer p23 = null;

  @JsonProperty("PMarzy")
  private PMarzy pmarzy = null;

  public Adnotacje p16(Integer p16) {
    this.p16 = p16;
    return this;
  }

   /**
   * Get p16
   * @return p16
  **/
  @Schema(required = true, description = "")
  public Integer getP16() {
    return p16;
  }

  public void setP16(Integer p16) {
    this.p16 = p16;
  }

  public Adnotacje p17(Integer p17) {
    this.p17 = p17;
    return this;
  }

   /**
   * Get p17
   * @return p17
  **/
  @Schema(required = true, description = "")
  public Integer getP17() {
    return p17;
  }

  public void setP17(Integer p17) {
    this.p17 = p17;
  }

  public Adnotacje p18(Integer p18) {
    this.p18 = p18;
    return this;
  }

   /**
   * Get p18
   * @return p18
  **/
  @Schema(required = true, description = "")
  public Integer getP18() {
    return p18;
  }

  public void setP18(Integer p18) {
    this.p18 = p18;
  }

  public Adnotacje p18A(Integer p18A) {
    this.p18A = p18A;
    return this;
  }

   /**
   * Get p18A
   * @return p18A
  **/
  @Schema(required = true, description = "")
  public Integer getP18A() {
    return p18A;
  }

  public void setP18A(Integer p18A) {
    this.p18A = p18A;
  }

  public Adnotacje zwolnienie(Zwolnienie zwolnienie) {
    this.zwolnienie = zwolnienie;
    return this;
  }

   /**
   * Get zwolnienie
   * @return zwolnienie
  **/
  @Schema(required = true, description = "")
  public Zwolnienie getZwolnienie() {
    return zwolnienie;
  }

  public void setZwolnienie(Zwolnienie zwolnienie) {
    this.zwolnienie = zwolnienie;
  }

  public Adnotacje noweSrodkiTransportu(NoweSrodkiTransportu noweSrodkiTransportu) {
    this.noweSrodkiTransportu = noweSrodkiTransportu;
    return this;
  }

   /**
   * Get noweSrodkiTransportu
   * @return noweSrodkiTransportu
  **/
  @Schema(required = true, description = "")
  public NoweSrodkiTransportu getNoweSrodkiTransportu() {
    return noweSrodkiTransportu;
  }

  public void setNoweSrodkiTransportu(NoweSrodkiTransportu noweSrodkiTransportu) {
    this.noweSrodkiTransportu = noweSrodkiTransportu;
  }

  public Adnotacje p23(Integer p23) {
    this.p23 = p23;
    return this;
  }

   /**
   * Get p23
   * @return p23
  **/
  @Schema(required = true, description = "")
  public Integer getP23() {
    return p23;
  }

  public void setP23(Integer p23) {
    this.p23 = p23;
  }

  public Adnotacje pmarzy(PMarzy pmarzy) {
    this.pmarzy = pmarzy;
    return this;
  }

   /**
   * Get pmarzy
   * @return pmarzy
  **/
  @Schema(required = true, description = "")
  public PMarzy getPmarzy() {
    return pmarzy;
  }

  public void setPmarzy(PMarzy pmarzy) {
    this.pmarzy = pmarzy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Adnotacje adnotacje = (Adnotacje) o;
    return Objects.equals(this.p16, adnotacje.p16) &&
        Objects.equals(this.p17, adnotacje.p17) &&
        Objects.equals(this.p18, adnotacje.p18) &&
        Objects.equals(this.p18A, adnotacje.p18A) &&
        Objects.equals(this.zwolnienie, adnotacje.zwolnienie) &&
        Objects.equals(this.noweSrodkiTransportu, adnotacje.noweSrodkiTransportu) &&
        Objects.equals(this.p23, adnotacje.p23) &&
        Objects.equals(this.pmarzy, adnotacje.pmarzy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p16, p17, p18, p18A, zwolnienie, noweSrodkiTransportu, p23, pmarzy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Adnotacje {\n");
    
    sb.append("    p16: ").append(toIndentedString(p16)).append("\n");
    sb.append("    p17: ").append(toIndentedString(p17)).append("\n");
    sb.append("    p18: ").append(toIndentedString(p18)).append("\n");
    sb.append("    p18A: ").append(toIndentedString(p18A)).append("\n");
    sb.append("    zwolnienie: ").append(toIndentedString(zwolnienie)).append("\n");
    sb.append("    noweSrodkiTransportu: ").append(toIndentedString(noweSrodkiTransportu)).append("\n");
    sb.append("    p23: ").append(toIndentedString(p23)).append("\n");
    sb.append("    pmarzy: ").append(toIndentedString(pmarzy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
