/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Adres
 */


public class Adres {
  @JsonProperty("ulica")
  private String ulica = null;

  @JsonProperty("nrDomu")
  private String nrDomu = null;

  @JsonProperty("nrLokalu")
  private String nrLokalu = null;

  @JsonProperty("miejscowosc")
  private String miejscowosc = null;

  @JsonProperty("kodPocztowy")
  private String kodPocztowy = null;

  @JsonProperty("poczta")
  private String poczta = null;

  @JsonProperty("kraj")
  private String kraj = null;

  public Adres ulica(String ulica) {
    this.ulica = ulica;
    return this;
  }

   /**
   * Get ulica
   * @return ulica
  **/
  @Schema(description = "")
  public String getUlica() {
    return ulica;
  }

  public void setUlica(String ulica) {
    this.ulica = ulica;
  }

  public Adres nrDomu(String nrDomu) {
    this.nrDomu = nrDomu;
    return this;
  }

   /**
   * Get nrDomu
   * @return nrDomu
  **/
  @Schema(description = "")
  public String getNrDomu() {
    return nrDomu;
  }

  public void setNrDomu(String nrDomu) {
    this.nrDomu = nrDomu;
  }

  public Adres nrLokalu(String nrLokalu) {
    this.nrLokalu = nrLokalu;
    return this;
  }

   /**
   * Get nrLokalu
   * @return nrLokalu
  **/
  @Schema(description = "")
  public String getNrLokalu() {
    return nrLokalu;
  }

  public void setNrLokalu(String nrLokalu) {
    this.nrLokalu = nrLokalu;
  }

  public Adres miejscowosc(String miejscowosc) {
    this.miejscowosc = miejscowosc;
    return this;
  }

   /**
   * Get miejscowosc
   * @return miejscowosc
  **/
  @Schema(description = "")
  public String getMiejscowosc() {
    return miejscowosc;
  }

  public void setMiejscowosc(String miejscowosc) {
    this.miejscowosc = miejscowosc;
  }

  public Adres kodPocztowy(String kodPocztowy) {
    this.kodPocztowy = kodPocztowy;
    return this;
  }

   /**
   * Get kodPocztowy
   * @return kodPocztowy
  **/
  @Schema(description = "")
  public String getKodPocztowy() {
    return kodPocztowy;
  }

  public void setKodPocztowy(String kodPocztowy) {
    this.kodPocztowy = kodPocztowy;
  }

  public Adres poczta(String poczta) {
    this.poczta = poczta;
    return this;
  }

   /**
   * Get poczta
   * @return poczta
  **/
  @Schema(description = "")
  public String getPoczta() {
    return poczta;
  }

  public void setPoczta(String poczta) {
    this.poczta = poczta;
  }

  public Adres kraj(String kraj) {
    this.kraj = kraj;
    return this;
  }

   /**
   * Get kraj
   * @return kraj
  **/
  @Schema(description = "")
  public String getKraj() {
    return kraj;
  }

  public void setKraj(String kraj) {
    this.kraj = kraj;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Adres adres = (Adres) o;
    return Objects.equals(this.ulica, adres.ulica) &&
        Objects.equals(this.nrDomu, adres.nrDomu) &&
        Objects.equals(this.nrLokalu, adres.nrLokalu) &&
        Objects.equals(this.miejscowosc, adres.miejscowosc) &&
        Objects.equals(this.kodPocztowy, adres.kodPocztowy) &&
        Objects.equals(this.poczta, adres.poczta) &&
        Objects.equals(this.kraj, adres.kraj);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ulica, nrDomu, nrLokalu, miejscowosc, kodPocztowy, poczta, kraj);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Adres {\n");
    
    sb.append("    ulica: ").append(toIndentedString(ulica)).append("\n");
    sb.append("    nrDomu: ").append(toIndentedString(nrDomu)).append("\n");
    sb.append("    nrLokalu: ").append(toIndentedString(nrLokalu)).append("\n");
    sb.append("    miejscowosc: ").append(toIndentedString(miejscowosc)).append("\n");
    sb.append("    kodPocztowy: ").append(toIndentedString(kodPocztowy)).append("\n");
    sb.append("    poczta: ").append(toIndentedString(poczta)).append("\n");
    sb.append("    kraj: ").append(toIndentedString(kraj)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
