/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.AllData;
/**
 * AllDataResult
 */


public class AllDataResult {
  @JsonProperty("firm")
  private AllData firm = null;

  public AllDataResult firm(AllData firm) {
    this.firm = firm;
    return this;
  }

   /**
   * Get firm
   * @return firm
  **/
  @Schema(required = true, description = "")
  public AllData getFirm() {
    return firm;
  }

  public void setFirm(AllData firm) {
    this.firm = firm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllDataResult allDataResult = (AllDataResult) o;
    return Objects.equals(this.firm, allDataResult.firm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllDataResult {\n");
    
    sb.append("    firm: ").append(toIndentedString(firm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
