/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Dane kontaktowe
 */
@Schema(description = "Dane kontaktowe")

public class DaneKontaktowe {
  @JsonProperty("Email")
  private String email = null;

  @JsonProperty("Telefon")
  private String telefon = null;

  public DaneKontaktowe email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public DaneKontaktowe telefon(String telefon) {
    this.telefon = telefon;
    return this;
  }

   /**
   * Get telefon
   * @return telefon
  **/
  @Schema(description = "")
  public String getTelefon() {
    return telefon;
  }

  public void setTelefon(String telefon) {
    this.telefon = telefon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DaneKontaktowe daneKontaktowe = (DaneKontaktowe) o;
    return Objects.equals(this.email, daneKontaktowe.email) &&
        Objects.equals(this.telefon, daneKontaktowe.telefon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, telefon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DaneKontaktowe {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    telefon: ").append(toIndentedString(telefon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
