/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DaneOWczesniejszejRejestracji
 */


public class DaneOWczesniejszejRejestracji {
  @JsonProperty("nazwaPoprzedniegoRejestru")
  private String nazwaPoprzedniegoRejestru = null;

  @JsonProperty("numerWPoprzednimRejestrze")
  private String numerWPoprzednimRejestrze = null;

  @JsonProperty("sadProwadzacyRejestr")
  private String sadProwadzacyRejestr = null;

  public DaneOWczesniejszejRejestracji nazwaPoprzedniegoRejestru(String nazwaPoprzedniegoRejestru) {
    this.nazwaPoprzedniegoRejestru = nazwaPoprzedniegoRejestru;
    return this;
  }

   /**
   * Get nazwaPoprzedniegoRejestru
   * @return nazwaPoprzedniegoRejestru
  **/
  @Schema(description = "")
  public String getNazwaPoprzedniegoRejestru() {
    return nazwaPoprzedniegoRejestru;
  }

  public void setNazwaPoprzedniegoRejestru(String nazwaPoprzedniegoRejestru) {
    this.nazwaPoprzedniegoRejestru = nazwaPoprzedniegoRejestru;
  }

  public DaneOWczesniejszejRejestracji numerWPoprzednimRejestrze(String numerWPoprzednimRejestrze) {
    this.numerWPoprzednimRejestrze = numerWPoprzednimRejestrze;
    return this;
  }

   /**
   * Get numerWPoprzednimRejestrze
   * @return numerWPoprzednimRejestrze
  **/
  @Schema(description = "")
  public String getNumerWPoprzednimRejestrze() {
    return numerWPoprzednimRejestrze;
  }

  public void setNumerWPoprzednimRejestrze(String numerWPoprzednimRejestrze) {
    this.numerWPoprzednimRejestrze = numerWPoprzednimRejestrze;
  }

  public DaneOWczesniejszejRejestracji sadProwadzacyRejestr(String sadProwadzacyRejestr) {
    this.sadProwadzacyRejestr = sadProwadzacyRejestr;
    return this;
  }

   /**
   * Get sadProwadzacyRejestr
   * @return sadProwadzacyRejestr
  **/
  @Schema(description = "")
  public String getSadProwadzacyRejestr() {
    return sadProwadzacyRejestr;
  }

  public void setSadProwadzacyRejestr(String sadProwadzacyRejestr) {
    this.sadProwadzacyRejestr = sadProwadzacyRejestr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DaneOWczesniejszejRejestracji daneOWczesniejszejRejestracji = (DaneOWczesniejszejRejestracji) o;
    return Objects.equals(this.nazwaPoprzedniegoRejestru, daneOWczesniejszejRejestracji.nazwaPoprzedniegoRejestru) &&
        Objects.equals(this.numerWPoprzednimRejestrze, daneOWczesniejszejRejestracji.numerWPoprzednimRejestrze) &&
        Objects.equals(this.sadProwadzacyRejestr, daneOWczesniejszejRejestracji.sadProwadzacyRejestr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwaPoprzedniegoRejestru, numerWPoprzednimRejestrze, sadProwadzacyRejestr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DaneOWczesniejszejRejestracji {\n");
    
    sb.append("    nazwaPoprzedniegoRejestru: ").append(toIndentedString(nazwaPoprzedniegoRejestru)).append("\n");
    sb.append("    numerWPoprzednimRejestrze: ").append(toIndentedString(numerWPoprzednimRejestrze)).append("\n");
    sb.append("    sadProwadzacyRejestr: ").append(toIndentedString(sadProwadzacyRejestr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
