/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
/**
 * Dane faktury korygowanej
 */
@Schema(description = "Dane faktury korygowanej")

public class DaneFaKorygowanej {
  @JsonProperty("DataWystFaKorygowanej")
  private LocalDate dataWystFaKorygowanej = null;

  @JsonProperty("NrFaKorygowanej")
  private String nrFaKorygowanej = null;

  @JsonProperty("NrKSeF")
  private Integer nrKSeF = null;

  @JsonProperty("NrKSeFFaKorygowanej")
  private String nrKSeFFaKorygowanej = null;

  @JsonProperty("NrKSeFN")
  private Integer nrKSeFN = null;

  public DaneFaKorygowanej dataWystFaKorygowanej(LocalDate dataWystFaKorygowanej) {
    this.dataWystFaKorygowanej = dataWystFaKorygowanej;
    return this;
  }

   /**
   * Get dataWystFaKorygowanej
   * @return dataWystFaKorygowanej
  **/
  @Schema(required = true, description = "")
  public LocalDate getDataWystFaKorygowanej() {
    return dataWystFaKorygowanej;
  }

  public void setDataWystFaKorygowanej(LocalDate dataWystFaKorygowanej) {
    this.dataWystFaKorygowanej = dataWystFaKorygowanej;
  }

  public DaneFaKorygowanej nrFaKorygowanej(String nrFaKorygowanej) {
    this.nrFaKorygowanej = nrFaKorygowanej;
    return this;
  }

   /**
   * Get nrFaKorygowanej
   * @return nrFaKorygowanej
  **/
  @Schema(required = true, description = "")
  public String getNrFaKorygowanej() {
    return nrFaKorygowanej;
  }

  public void setNrFaKorygowanej(String nrFaKorygowanej) {
    this.nrFaKorygowanej = nrFaKorygowanej;
  }

  public DaneFaKorygowanej nrKSeF(Integer nrKSeF) {
    this.nrKSeF = nrKSeF;
    return this;
  }

   /**
   * Get nrKSeF
   * @return nrKSeF
  **/
  @Schema(description = "")
  public Integer getNrKSeF() {
    return nrKSeF;
  }

  public void setNrKSeF(Integer nrKSeF) {
    this.nrKSeF = nrKSeF;
  }

  public DaneFaKorygowanej nrKSeFFaKorygowanej(String nrKSeFFaKorygowanej) {
    this.nrKSeFFaKorygowanej = nrKSeFFaKorygowanej;
    return this;
  }

   /**
   * Get nrKSeFFaKorygowanej
   * @return nrKSeFFaKorygowanej
  **/
  @Schema(description = "")
  public String getNrKSeFFaKorygowanej() {
    return nrKSeFFaKorygowanej;
  }

  public void setNrKSeFFaKorygowanej(String nrKSeFFaKorygowanej) {
    this.nrKSeFFaKorygowanej = nrKSeFFaKorygowanej;
  }

  public DaneFaKorygowanej nrKSeFN(Integer nrKSeFN) {
    this.nrKSeFN = nrKSeFN;
    return this;
  }

   /**
   * Get nrKSeFN
   * @return nrKSeFN
  **/
  @Schema(description = "")
  public Integer getNrKSeFN() {
    return nrKSeFN;
  }

  public void setNrKSeFN(Integer nrKSeFN) {
    this.nrKSeFN = nrKSeFN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DaneFaKorygowanej daneFaKorygowanej = (DaneFaKorygowanej) o;
    return Objects.equals(this.dataWystFaKorygowanej, daneFaKorygowanej.dataWystFaKorygowanej) &&
        Objects.equals(this.nrFaKorygowanej, daneFaKorygowanej.nrFaKorygowanej) &&
        Objects.equals(this.nrKSeF, daneFaKorygowanej.nrKSeF) &&
        Objects.equals(this.nrKSeFFaKorygowanej, daneFaKorygowanej.nrKSeFFaKorygowanej) &&
        Objects.equals(this.nrKSeFN, daneFaKorygowanej.nrKSeFN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataWystFaKorygowanej, nrFaKorygowanej, nrKSeF, nrKSeFFaKorygowanej, nrKSeFN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DaneFaKorygowanej {\n");
    
    sb.append("    dataWystFaKorygowanej: ").append(toIndentedString(dataWystFaKorygowanej)).append("\n");
    sb.append("    nrFaKorygowanej: ").append(toIndentedString(nrFaKorygowanej)).append("\n");
    sb.append("    nrKSeF: ").append(toIndentedString(nrKSeF)).append("\n");
    sb.append("    nrKSeFFaKorygowanej: ").append(toIndentedString(nrKSeFFaKorygowanej)).append("\n");
    sb.append("    nrKSeFN: ").append(toIndentedString(nrKSeFN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
