/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.IdentyfikatorOsoby;
import pl.nip24.client.model.ImionaOsoby;
import pl.nip24.client.model.NazwiskoOsoby;
import pl.nip24.client.model.Podmioty;
/**
 * DaneSyndyka
 */


public class DaneSyndyka {
  @JsonProperty("nazwisko")
  private NazwiskoOsoby nazwisko = null;

  @JsonProperty("imiona")
  private ImionaOsoby imiona = null;

  @JsonProperty("identyfikator")
  private IdentyfikatorOsoby identyfikator = null;

  @JsonProperty("podmiot")
  private Podmioty podmiot = null;

  public DaneSyndyka nazwisko(NazwiskoOsoby nazwisko) {
    this.nazwisko = nazwisko;
    return this;
  }

   /**
   * Get nazwisko
   * @return nazwisko
  **/
  @Schema(description = "")
  public NazwiskoOsoby getNazwisko() {
    return nazwisko;
  }

  public void setNazwisko(NazwiskoOsoby nazwisko) {
    this.nazwisko = nazwisko;
  }

  public DaneSyndyka imiona(ImionaOsoby imiona) {
    this.imiona = imiona;
    return this;
  }

   /**
   * Get imiona
   * @return imiona
  **/
  @Schema(description = "")
  public ImionaOsoby getImiona() {
    return imiona;
  }

  public void setImiona(ImionaOsoby imiona) {
    this.imiona = imiona;
  }

  public DaneSyndyka identyfikator(IdentyfikatorOsoby identyfikator) {
    this.identyfikator = identyfikator;
    return this;
  }

   /**
   * Get identyfikator
   * @return identyfikator
  **/
  @Schema(description = "")
  public IdentyfikatorOsoby getIdentyfikator() {
    return identyfikator;
  }

  public void setIdentyfikator(IdentyfikatorOsoby identyfikator) {
    this.identyfikator = identyfikator;
  }

  public DaneSyndyka podmiot(Podmioty podmiot) {
    this.podmiot = podmiot;
    return this;
  }

   /**
   * Get podmiot
   * @return podmiot
  **/
  @Schema(description = "")
  public Podmioty getPodmiot() {
    return podmiot;
  }

  public void setPodmiot(Podmioty podmiot) {
    this.podmiot = podmiot;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DaneSyndyka daneSyndyka = (DaneSyndyka) o;
    return Objects.equals(this.nazwisko, daneSyndyka.nazwisko) &&
        Objects.equals(this.imiona, daneSyndyka.imiona) &&
        Objects.equals(this.identyfikator, daneSyndyka.identyfikator) &&
        Objects.equals(this.podmiot, daneSyndyka.podmiot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwisko, imiona, identyfikator, podmiot);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DaneSyndyka {\n");
    
    sb.append("    nazwisko: ").append(toIndentedString(nazwisko)).append("\n");
    sb.append("    imiona: ").append(toIndentedString(imiona)).append("\n");
    sb.append("    identyfikator: ").append(toIndentedString(identyfikator)).append("\n");
    sb.append("    podmiot: ").append(toIndentedString(podmiot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
