/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.Dzial1;
import pl.nip24.client.model.Dzial2;
import pl.nip24.client.model.Dzial3;
import pl.nip24.client.model.Dzial4;
import pl.nip24.client.model.Dzial5;
import pl.nip24.client.model.Dzial6;
/**
 * Dane
 */


public class Dane {
  @JsonProperty("dzial1")
  private Dzial1 dzial1 = null;

  @JsonProperty("dzial2")
  private Dzial2 dzial2 = null;

  @JsonProperty("dzial3")
  private Dzial3 dzial3 = null;

  @JsonProperty("dzial4")
  private Dzial4 dzial4 = null;

  @JsonProperty("dzial5")
  private Dzial5 dzial5 = null;

  @JsonProperty("dzial6")
  private Dzial6 dzial6 = null;

  public Dane dzial1(Dzial1 dzial1) {
    this.dzial1 = dzial1;
    return this;
  }

   /**
   * Get dzial1
   * @return dzial1
  **/
  @Schema(description = "")
  public Dzial1 getDzial1() {
    return dzial1;
  }

  public void setDzial1(Dzial1 dzial1) {
    this.dzial1 = dzial1;
  }

  public Dane dzial2(Dzial2 dzial2) {
    this.dzial2 = dzial2;
    return this;
  }

   /**
   * Get dzial2
   * @return dzial2
  **/
  @Schema(description = "")
  public Dzial2 getDzial2() {
    return dzial2;
  }

  public void setDzial2(Dzial2 dzial2) {
    this.dzial2 = dzial2;
  }

  public Dane dzial3(Dzial3 dzial3) {
    this.dzial3 = dzial3;
    return this;
  }

   /**
   * Get dzial3
   * @return dzial3
  **/
  @Schema(description = "")
  public Dzial3 getDzial3() {
    return dzial3;
  }

  public void setDzial3(Dzial3 dzial3) {
    this.dzial3 = dzial3;
  }

  public Dane dzial4(Dzial4 dzial4) {
    this.dzial4 = dzial4;
    return this;
  }

   /**
   * Get dzial4
   * @return dzial4
  **/
  @Schema(description = "")
  public Dzial4 getDzial4() {
    return dzial4;
  }

  public void setDzial4(Dzial4 dzial4) {
    this.dzial4 = dzial4;
  }

  public Dane dzial5(Dzial5 dzial5) {
    this.dzial5 = dzial5;
    return this;
  }

   /**
   * Get dzial5
   * @return dzial5
  **/
  @Schema(description = "")
  public Dzial5 getDzial5() {
    return dzial5;
  }

  public void setDzial5(Dzial5 dzial5) {
    this.dzial5 = dzial5;
  }

  public Dane dzial6(Dzial6 dzial6) {
    this.dzial6 = dzial6;
    return this;
  }

   /**
   * Get dzial6
   * @return dzial6
  **/
  @Schema(description = "")
  public Dzial6 getDzial6() {
    return dzial6;
  }

  public void setDzial6(Dzial6 dzial6) {
    this.dzial6 = dzial6;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dane dane = (Dane) o;
    return Objects.equals(this.dzial1, dane.dzial1) &&
        Objects.equals(this.dzial2, dane.dzial2) &&
        Objects.equals(this.dzial3, dane.dzial3) &&
        Objects.equals(this.dzial4, dane.dzial4) &&
        Objects.equals(this.dzial5, dane.dzial5) &&
        Objects.equals(this.dzial6, dane.dzial6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dzial1, dzial2, dzial3, dzial4, dzial5, dzial6);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dane {\n");
    
    sb.append("    dzial1: ").append(toIndentedString(dzial1)).append("\n");
    sb.append("    dzial2: ").append(toIndentedString(dzial2)).append("\n");
    sb.append("    dzial3: ").append(toIndentedString(dzial3)).append("\n");
    sb.append("    dzial4: ").append(toIndentedString(dzial4)).append("\n");
    sb.append("    dzial5: ").append(toIndentedString(dzial5)).append("\n");
    sb.append("    dzial6: ").append(toIndentedString(dzial6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
