/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Dane kontaktowe podmiotu upoważnionego
 */
@Schema(description = "Dane kontaktowe podmiotu upoważnionego")

public class DaneKontaktowePU {
  @JsonProperty("EmailPU")
  private String emailPU = null;

  @JsonProperty("TelefonPU")
  private String telefonPU = null;

  public DaneKontaktowePU emailPU(String emailPU) {
    this.emailPU = emailPU;
    return this;
  }

   /**
   * Get emailPU
   * @return emailPU
  **/
  @Schema(description = "")
  public String getEmailPU() {
    return emailPU;
  }

  public void setEmailPU(String emailPU) {
    this.emailPU = emailPU;
  }

  public DaneKontaktowePU telefonPU(String telefonPU) {
    this.telefonPU = telefonPU;
    return this;
  }

   /**
   * Get telefonPU
   * @return telefonPU
  **/
  @Schema(description = "")
  public String getTelefonPU() {
    return telefonPU;
  }

  public void setTelefonPU(String telefonPU) {
    this.telefonPU = telefonPU;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DaneKontaktowePU daneKontaktowePU = (DaneKontaktowePU) o;
    return Objects.equals(this.emailPU, daneKontaktowePU.emailPU) &&
        Objects.equals(this.telefonPU, daneKontaktowePU.telefonPU);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailPU, telefonPU);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DaneKontaktowePU {\n");
    
    sb.append("    emailPU: ").append(toIndentedString(emailPU)).append("\n");
    sb.append("    telefonPU: ").append(toIndentedString(telefonPU)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
