/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.OrganNadzoru;
import pl.nip24.client.model.Prokurenci;
import pl.nip24.client.model.Reprezentacja;
/**
 * Dzial2
 */


public class Dzial2 {
  @JsonProperty("organNadzoru")
  private List<OrganNadzoru> organNadzoru = null;

  @JsonProperty("reprezentacja")
  private Reprezentacja reprezentacja = null;

  @JsonProperty("prokurenci")
  private List<Prokurenci> prokurenci = null;

  public Dzial2 organNadzoru(List<OrganNadzoru> organNadzoru) {
    this.organNadzoru = organNadzoru;
    return this;
  }

  public Dzial2 addOrganNadzoruItem(OrganNadzoru organNadzoruItem) {
    if (this.organNadzoru == null) {
      this.organNadzoru = new ArrayList<>();
    }
    this.organNadzoru.add(organNadzoruItem);
    return this;
  }

   /**
   * Get organNadzoru
   * @return organNadzoru
  **/
  @Schema(description = "")
  public List<OrganNadzoru> getOrganNadzoru() {
    return organNadzoru;
  }

  public void setOrganNadzoru(List<OrganNadzoru> organNadzoru) {
    this.organNadzoru = organNadzoru;
  }

  public Dzial2 reprezentacja(Reprezentacja reprezentacja) {
    this.reprezentacja = reprezentacja;
    return this;
  }

   /**
   * Get reprezentacja
   * @return reprezentacja
  **/
  @Schema(description = "")
  public Reprezentacja getReprezentacja() {
    return reprezentacja;
  }

  public void setReprezentacja(Reprezentacja reprezentacja) {
    this.reprezentacja = reprezentacja;
  }

  public Dzial2 prokurenci(List<Prokurenci> prokurenci) {
    this.prokurenci = prokurenci;
    return this;
  }

  public Dzial2 addProkurenciItem(Prokurenci prokurenciItem) {
    if (this.prokurenci == null) {
      this.prokurenci = new ArrayList<>();
    }
    this.prokurenci.add(prokurenciItem);
    return this;
  }

   /**
   * Get prokurenci
   * @return prokurenci
  **/
  @Schema(description = "")
  public List<Prokurenci> getProkurenci() {
    return prokurenci;
  }

  public void setProkurenci(List<Prokurenci> prokurenci) {
    this.prokurenci = prokurenci;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dzial2 dzial2 = (Dzial2) o;
    return Objects.equals(this.organNadzoru, dzial2.organNadzoru) &&
        Objects.equals(this.reprezentacja, dzial2.reprezentacja) &&
        Objects.equals(this.prokurenci, dzial2.prokurenci);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organNadzoru, reprezentacja, prokurenci);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dzial2 {\n");
    
    sb.append("    organNadzoru: ").append(toIndentedString(organNadzoru)).append("\n");
    sb.append("    reprezentacja: ").append(toIndentedString(reprezentacja)).append("\n");
    sb.append("    prokurenci: ").append(toIndentedString(prokurenci)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
