/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Likwidacja;
import pl.nip24.client.model.PolaczeniePodzialPrzeksztalcenie;
import pl.nip24.client.model.PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja;
import pl.nip24.client.model.PostepowanieUkladowe;
import pl.nip24.client.model.PostepowanieUpadlosciowe;
import pl.nip24.client.model.RozwiazanieUniewaznienie;
import pl.nip24.client.model.ZawieszenieWznowienie;
/**
 * Dzial6
 */


public class Dzial6 {
  @JsonProperty("postepowanieUpadlosciowe")
  private List<PostepowanieUpadlosciowe> postepowanieUpadlosciowe = null;

  @JsonProperty("polaczeniePodzialPrzeksztalcenie")
  private List<PolaczeniePodzialPrzeksztalcenie> polaczeniePodzialPrzeksztalcenie = null;

  @JsonProperty("likwidacja")
  private List<Likwidacja> likwidacja = null;

  @JsonProperty("rozwiazanieUniewaznienie")
  private List<RozwiazanieUniewaznienie> rozwiazanieUniewaznienie = null;

  @JsonProperty("zawieszenieWznowienie")
  private List<ZawieszenieWznowienie> zawieszenieWznowienie = null;

  @JsonProperty("postepowanieUkladowe")
  private List<PostepowanieUkladowe> postepowanieUkladowe = null;

  @JsonProperty("postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja")
  private List<PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja> postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja = null;

  public Dzial6 postepowanieUpadlosciowe(List<PostepowanieUpadlosciowe> postepowanieUpadlosciowe) {
    this.postepowanieUpadlosciowe = postepowanieUpadlosciowe;
    return this;
  }

  public Dzial6 addPostepowanieUpadloscioweItem(PostepowanieUpadlosciowe postepowanieUpadloscioweItem) {
    if (this.postepowanieUpadlosciowe == null) {
      this.postepowanieUpadlosciowe = new ArrayList<PostepowanieUpadlosciowe>();
    }
    this.postepowanieUpadlosciowe.add(postepowanieUpadloscioweItem);
    return this;
  }

   /**
   * Get postepowanieUpadlosciowe
   * @return postepowanieUpadlosciowe
  **/
  @Schema(description = "")
  public List<PostepowanieUpadlosciowe> getPostepowanieUpadlosciowe() {
    return postepowanieUpadlosciowe;
  }

  public void setPostepowanieUpadlosciowe(List<PostepowanieUpadlosciowe> postepowanieUpadlosciowe) {
    this.postepowanieUpadlosciowe = postepowanieUpadlosciowe;
  }

  public Dzial6 polaczeniePodzialPrzeksztalcenie(List<PolaczeniePodzialPrzeksztalcenie> polaczeniePodzialPrzeksztalcenie) {
    this.polaczeniePodzialPrzeksztalcenie = polaczeniePodzialPrzeksztalcenie;
    return this;
  }

  public Dzial6 addPolaczeniePodzialPrzeksztalcenieItem(PolaczeniePodzialPrzeksztalcenie polaczeniePodzialPrzeksztalcenieItem) {
    if (this.polaczeniePodzialPrzeksztalcenie == null) {
      this.polaczeniePodzialPrzeksztalcenie = new ArrayList<PolaczeniePodzialPrzeksztalcenie>();
    }
    this.polaczeniePodzialPrzeksztalcenie.add(polaczeniePodzialPrzeksztalcenieItem);
    return this;
  }

   /**
   * Get polaczeniePodzialPrzeksztalcenie
   * @return polaczeniePodzialPrzeksztalcenie
  **/
  @Schema(description = "")
  public List<PolaczeniePodzialPrzeksztalcenie> getPolaczeniePodzialPrzeksztalcenie() {
    return polaczeniePodzialPrzeksztalcenie;
  }

  public void setPolaczeniePodzialPrzeksztalcenie(List<PolaczeniePodzialPrzeksztalcenie> polaczeniePodzialPrzeksztalcenie) {
    this.polaczeniePodzialPrzeksztalcenie = polaczeniePodzialPrzeksztalcenie;
  }

  public Dzial6 likwidacja(List<Likwidacja> likwidacja) {
    this.likwidacja = likwidacja;
    return this;
  }

  public Dzial6 addLikwidacjaItem(Likwidacja likwidacjaItem) {
    if (this.likwidacja == null) {
      this.likwidacja = new ArrayList<Likwidacja>();
    }
    this.likwidacja.add(likwidacjaItem);
    return this;
  }

   /**
   * Get likwidacja
   * @return likwidacja
  **/
  @Schema(description = "")
  public List<Likwidacja> getLikwidacja() {
    return likwidacja;
  }

  public void setLikwidacja(List<Likwidacja> likwidacja) {
    this.likwidacja = likwidacja;
  }

  public Dzial6 rozwiazanieUniewaznienie(List<RozwiazanieUniewaznienie> rozwiazanieUniewaznienie) {
    this.rozwiazanieUniewaznienie = rozwiazanieUniewaznienie;
    return this;
  }

  public Dzial6 addRozwiazanieUniewaznienieItem(RozwiazanieUniewaznienie rozwiazanieUniewaznienieItem) {
    if (this.rozwiazanieUniewaznienie == null) {
      this.rozwiazanieUniewaznienie = new ArrayList<RozwiazanieUniewaznienie>();
    }
    this.rozwiazanieUniewaznienie.add(rozwiazanieUniewaznienieItem);
    return this;
  }

   /**
   * Get rozwiazanieUniewaznienie
   * @return rozwiazanieUniewaznienie
  **/
  @Schema(description = "")
  public List<RozwiazanieUniewaznienie> getRozwiazanieUniewaznienie() {
    return rozwiazanieUniewaznienie;
  }

  public void setRozwiazanieUniewaznienie(List<RozwiazanieUniewaznienie> rozwiazanieUniewaznienie) {
    this.rozwiazanieUniewaznienie = rozwiazanieUniewaznienie;
  }

  public Dzial6 zawieszenieWznowienie(List<ZawieszenieWznowienie> zawieszenieWznowienie) {
    this.zawieszenieWznowienie = zawieszenieWznowienie;
    return this;
  }

  public Dzial6 addZawieszenieWznowienieItem(ZawieszenieWznowienie zawieszenieWznowienieItem) {
    if (this.zawieszenieWznowienie == null) {
      this.zawieszenieWznowienie = new ArrayList<ZawieszenieWznowienie>();
    }
    this.zawieszenieWznowienie.add(zawieszenieWznowienieItem);
    return this;
  }

   /**
   * Get zawieszenieWznowienie
   * @return zawieszenieWznowienie
  **/
  @Schema(description = "")
  public List<ZawieszenieWznowienie> getZawieszenieWznowienie() {
    return zawieszenieWznowienie;
  }

  public void setZawieszenieWznowienie(List<ZawieszenieWznowienie> zawieszenieWznowienie) {
    this.zawieszenieWznowienie = zawieszenieWznowienie;
  }

  public Dzial6 postepowanieUkladowe(List<PostepowanieUkladowe> postepowanieUkladowe) {
    this.postepowanieUkladowe = postepowanieUkladowe;
    return this;
  }

  public Dzial6 addPostepowanieUkladoweItem(PostepowanieUkladowe postepowanieUkladoweItem) {
    if (this.postepowanieUkladowe == null) {
      this.postepowanieUkladowe = new ArrayList<PostepowanieUkladowe>();
    }
    this.postepowanieUkladowe.add(postepowanieUkladoweItem);
    return this;
  }

   /**
   * Get postepowanieUkladowe
   * @return postepowanieUkladowe
  **/
  @Schema(description = "")
  public List<PostepowanieUkladowe> getPostepowanieUkladowe() {
    return postepowanieUkladowe;
  }

  public void setPostepowanieUkladowe(List<PostepowanieUkladowe> postepowanieUkladowe) {
    this.postepowanieUkladowe = postepowanieUkladowe;
  }

  public Dzial6 postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja(List<PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja> postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja) {
    this.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja = postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja;
    return this;
  }

  public Dzial6 addPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacjaItem(PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacjaItem) {
    if (this.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja == null) {
      this.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja = new ArrayList<PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja>();
    }
    this.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja.add(postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacjaItem);
    return this;
  }

   /**
   * Get postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja
   * @return postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja
  **/
  @Schema(description = "")
  public List<PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja> getPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja() {
    return postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja;
  }

  public void setPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja(List<PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja> postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja) {
    this.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja = postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dzial6 dzial6 = (Dzial6) o;
    return Objects.equals(this.postepowanieUpadlosciowe, dzial6.postepowanieUpadlosciowe) &&
        Objects.equals(this.polaczeniePodzialPrzeksztalcenie, dzial6.polaczeniePodzialPrzeksztalcenie) &&
        Objects.equals(this.likwidacja, dzial6.likwidacja) &&
        Objects.equals(this.rozwiazanieUniewaznienie, dzial6.rozwiazanieUniewaznienie) &&
        Objects.equals(this.zawieszenieWznowienie, dzial6.zawieszenieWznowienie) &&
        Objects.equals(this.postepowanieUkladowe, dzial6.postepowanieUkladowe) &&
        Objects.equals(this.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja, dzial6.postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postepowanieUpadlosciowe, polaczeniePodzialPrzeksztalcenie, likwidacja, rozwiazanieUniewaznienie, zawieszenieWznowienie, postepowanieUkladowe, postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dzial6 {\n");
    
    sb.append("    postepowanieUpadlosciowe: ").append(toIndentedString(postepowanieUpadlosciowe)).append("\n");
    sb.append("    polaczeniePodzialPrzeksztalcenie: ").append(toIndentedString(polaczeniePodzialPrzeksztalcenie)).append("\n");
    sb.append("    likwidacja: ").append(toIndentedString(likwidacja)).append("\n");
    sb.append("    rozwiazanieUniewaznienie: ").append(toIndentedString(rozwiazanieUniewaznienie)).append("\n");
    sb.append("    zawieszenieWznowienie: ").append(toIndentedString(zawieszenieWznowienie)).append("\n");
    sb.append("    postepowanieUkladowe: ").append(toIndentedString(postepowanieUkladowe)).append("\n");
    sb.append("    postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja: ").append(toIndentedString(postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
