/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Dzialalnosci
 */


public class Dzialalnosci {
  @JsonProperty("opis")
  private String opis = null;

  @JsonProperty("kodDzial")
  private String kodDzial = null;

  @JsonProperty("kodKlasa")
  private String kodKlasa = null;

  @JsonProperty("kodPodklasa")
  private String kodPodklasa = null;

  public Dzialalnosci opis(String opis) {
    this.opis = opis;
    return this;
  }

   /**
   * Get opis
   * @return opis
  **/
  @Schema(description = "")
  public String getOpis() {
    return opis;
  }

  public void setOpis(String opis) {
    this.opis = opis;
  }

  public Dzialalnosci kodDzial(String kodDzial) {
    this.kodDzial = kodDzial;
    return this;
  }

   /**
   * Get kodDzial
   * @return kodDzial
  **/
  @Schema(description = "")
  public String getKodDzial() {
    return kodDzial;
  }

  public void setKodDzial(String kodDzial) {
    this.kodDzial = kodDzial;
  }

  public Dzialalnosci kodKlasa(String kodKlasa) {
    this.kodKlasa = kodKlasa;
    return this;
  }

   /**
   * Get kodKlasa
   * @return kodKlasa
  **/
  @Schema(description = "")
  public String getKodKlasa() {
    return kodKlasa;
  }

  public void setKodKlasa(String kodKlasa) {
    this.kodKlasa = kodKlasa;
  }

  public Dzialalnosci kodPodklasa(String kodPodklasa) {
    this.kodPodklasa = kodPodklasa;
    return this;
  }

   /**
   * Get kodPodklasa
   * @return kodPodklasa
  **/
  @Schema(description = "")
  public String getKodPodklasa() {
    return kodPodklasa;
  }

  public void setKodPodklasa(String kodPodklasa) {
    this.kodPodklasa = kodPodklasa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dzialalnosci dzialalnosci = (Dzialalnosci) o;
    return Objects.equals(this.opis, dzialalnosci.opis) &&
        Objects.equals(this.kodDzial, dzialalnosci.kodDzial) &&
        Objects.equals(this.kodKlasa, dzialalnosci.kodKlasa) &&
        Objects.equals(this.kodPodklasa, dzialalnosci.kodPodklasa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opis, kodDzial, kodKlasa, kodPodklasa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dzialalnosci {\n");
    
    sb.append("    opis: ").append(toIndentedString(opis)).append("\n");
    sb.append("    kodDzial: ").append(toIndentedString(kodDzial)).append("\n");
    sb.append("    kodKlasa: ").append(toIndentedString(kodKlasa)).append("\n");
    sb.append("    kodPodklasa: ").append(toIndentedString(kodPodklasa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
