/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.CelDzialaniaOrganizacji;
import pl.nip24.client.model.InformacjaODniuKonczacymRokObrotowy;
import pl.nip24.client.model.PrzedmiotDzialalnosci;
import pl.nip24.client.model.PrzedmiotDzialalnosciOPP;
import pl.nip24.client.model.SprawozdaniaGrupyKapitalowej;
import pl.nip24.client.model.WzmiankiOZlozonychDokumentach;
/**
 * Dzial3
 */


public class Dzial3 {
  @JsonProperty("celDzialaniaOrganizacji")
  private CelDzialaniaOrganizacji celDzialaniaOrganizacji = null;

  @JsonProperty("informacjaODniuKonczacymRokObrotowy")
  private InformacjaODniuKonczacymRokObrotowy informacjaODniuKonczacymRokObrotowy = null;

  @JsonProperty("przedmiotDzialalnosci")
  private PrzedmiotDzialalnosci przedmiotDzialalnosci = null;

  @JsonProperty("przedmiotDzialalnosciOPP")
  private PrzedmiotDzialalnosciOPP przedmiotDzialalnosciOPP = null;

  @JsonProperty("sprawozdaniaGrupyKapitalowej")
  private SprawozdaniaGrupyKapitalowej sprawozdaniaGrupyKapitalowej = null;

  @JsonProperty("wzmiankiOZlozonychDokumentach")
  private WzmiankiOZlozonychDokumentach wzmiankiOZlozonychDokumentach = null;

  public Dzial3 celDzialaniaOrganizacji(CelDzialaniaOrganizacji celDzialaniaOrganizacji) {
    this.celDzialaniaOrganizacji = celDzialaniaOrganizacji;
    return this;
  }

   /**
   * Get celDzialaniaOrganizacji
   * @return celDzialaniaOrganizacji
  **/
  @Schema(description = "")
  public CelDzialaniaOrganizacji getCelDzialaniaOrganizacji() {
    return celDzialaniaOrganizacji;
  }

  public void setCelDzialaniaOrganizacji(CelDzialaniaOrganizacji celDzialaniaOrganizacji) {
    this.celDzialaniaOrganizacji = celDzialaniaOrganizacji;
  }

  public Dzial3 informacjaODniuKonczacymRokObrotowy(InformacjaODniuKonczacymRokObrotowy informacjaODniuKonczacymRokObrotowy) {
    this.informacjaODniuKonczacymRokObrotowy = informacjaODniuKonczacymRokObrotowy;
    return this;
  }

   /**
   * Get informacjaODniuKonczacymRokObrotowy
   * @return informacjaODniuKonczacymRokObrotowy
  **/
  @Schema(description = "")
  public InformacjaODniuKonczacymRokObrotowy getInformacjaODniuKonczacymRokObrotowy() {
    return informacjaODniuKonczacymRokObrotowy;
  }

  public void setInformacjaODniuKonczacymRokObrotowy(InformacjaODniuKonczacymRokObrotowy informacjaODniuKonczacymRokObrotowy) {
    this.informacjaODniuKonczacymRokObrotowy = informacjaODniuKonczacymRokObrotowy;
  }

  public Dzial3 przedmiotDzialalnosci(PrzedmiotDzialalnosci przedmiotDzialalnosci) {
    this.przedmiotDzialalnosci = przedmiotDzialalnosci;
    return this;
  }

   /**
   * Get przedmiotDzialalnosci
   * @return przedmiotDzialalnosci
  **/
  @Schema(description = "")
  public PrzedmiotDzialalnosci getPrzedmiotDzialalnosci() {
    return przedmiotDzialalnosci;
  }

  public void setPrzedmiotDzialalnosci(PrzedmiotDzialalnosci przedmiotDzialalnosci) {
    this.przedmiotDzialalnosci = przedmiotDzialalnosci;
  }

  public Dzial3 przedmiotDzialalnosciOPP(PrzedmiotDzialalnosciOPP przedmiotDzialalnosciOPP) {
    this.przedmiotDzialalnosciOPP = przedmiotDzialalnosciOPP;
    return this;
  }

   /**
   * Get przedmiotDzialalnosciOPP
   * @return przedmiotDzialalnosciOPP
  **/
  @Schema(description = "")
  public PrzedmiotDzialalnosciOPP getPrzedmiotDzialalnosciOPP() {
    return przedmiotDzialalnosciOPP;
  }

  public void setPrzedmiotDzialalnosciOPP(PrzedmiotDzialalnosciOPP przedmiotDzialalnosciOPP) {
    this.przedmiotDzialalnosciOPP = przedmiotDzialalnosciOPP;
  }

  public Dzial3 sprawozdaniaGrupyKapitalowej(SprawozdaniaGrupyKapitalowej sprawozdaniaGrupyKapitalowej) {
    this.sprawozdaniaGrupyKapitalowej = sprawozdaniaGrupyKapitalowej;
    return this;
  }

   /**
   * Get sprawozdaniaGrupyKapitalowej
   * @return sprawozdaniaGrupyKapitalowej
  **/
  @Schema(description = "")
  public SprawozdaniaGrupyKapitalowej getSprawozdaniaGrupyKapitalowej() {
    return sprawozdaniaGrupyKapitalowej;
  }

  public void setSprawozdaniaGrupyKapitalowej(SprawozdaniaGrupyKapitalowej sprawozdaniaGrupyKapitalowej) {
    this.sprawozdaniaGrupyKapitalowej = sprawozdaniaGrupyKapitalowej;
  }

  public Dzial3 wzmiankiOZlozonychDokumentach(WzmiankiOZlozonychDokumentach wzmiankiOZlozonychDokumentach) {
    this.wzmiankiOZlozonychDokumentach = wzmiankiOZlozonychDokumentach;
    return this;
  }

   /**
   * Get wzmiankiOZlozonychDokumentach
   * @return wzmiankiOZlozonychDokumentach
  **/
  @Schema(description = "")
  public WzmiankiOZlozonychDokumentach getWzmiankiOZlozonychDokumentach() {
    return wzmiankiOZlozonychDokumentach;
  }

  public void setWzmiankiOZlozonychDokumentach(WzmiankiOZlozonychDokumentach wzmiankiOZlozonychDokumentach) {
    this.wzmiankiOZlozonychDokumentach = wzmiankiOZlozonychDokumentach;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dzial3 dzial3 = (Dzial3) o;
    return Objects.equals(this.celDzialaniaOrganizacji, dzial3.celDzialaniaOrganizacji) &&
        Objects.equals(this.informacjaODniuKonczacymRokObrotowy, dzial3.informacjaODniuKonczacymRokObrotowy) &&
        Objects.equals(this.przedmiotDzialalnosci, dzial3.przedmiotDzialalnosci) &&
        Objects.equals(this.przedmiotDzialalnosciOPP, dzial3.przedmiotDzialalnosciOPP) &&
        Objects.equals(this.sprawozdaniaGrupyKapitalowej, dzial3.sprawozdaniaGrupyKapitalowej) &&
        Objects.equals(this.wzmiankiOZlozonychDokumentach, dzial3.wzmiankiOZlozonychDokumentach);
  }

  @Override
  public int hashCode() {
    return Objects.hash(celDzialaniaOrganizacji, informacjaODniuKonczacymRokObrotowy, przedmiotDzialalnosci, przedmiotDzialalnosciOPP, sprawozdaniaGrupyKapitalowej, wzmiankiOZlozonychDokumentach);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dzial3 {\n");
    
    sb.append("    celDzialaniaOrganizacji: ").append(toIndentedString(celDzialaniaOrganizacji)).append("\n");
    sb.append("    informacjaODniuKonczacymRokObrotowy: ").append(toIndentedString(informacjaODniuKonczacymRokObrotowy)).append("\n");
    sb.append("    przedmiotDzialalnosci: ").append(toIndentedString(przedmiotDzialalnosci)).append("\n");
    sb.append("    przedmiotDzialalnosciOPP: ").append(toIndentedString(przedmiotDzialalnosciOPP)).append("\n");
    sb.append("    sprawozdaniaGrupyKapitalowej: ").append(toIndentedString(sprawozdaniaGrupyKapitalowej)).append("\n");
    sb.append("    wzmiankiOZlozonychDokumentach: ").append(toIndentedString(wzmiankiOZlozonychDokumentach)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
