/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EmisjeAkcji
 */


public class EmisjeAkcji {
  @JsonProperty("nazwaSeriiAkcji")
  private String nazwaSeriiAkcji = null;

  @JsonProperty("liczbaAkcjiWSerii")
  private String liczbaAkcjiWSerii = null;

  @JsonProperty("czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania")
  private String czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania = null;

  public EmisjeAkcji nazwaSeriiAkcji(String nazwaSeriiAkcji) {
    this.nazwaSeriiAkcji = nazwaSeriiAkcji;
    return this;
  }

   /**
   * Get nazwaSeriiAkcji
   * @return nazwaSeriiAkcji
  **/
  @Schema(description = "")
  public String getNazwaSeriiAkcji() {
    return nazwaSeriiAkcji;
  }

  public void setNazwaSeriiAkcji(String nazwaSeriiAkcji) {
    this.nazwaSeriiAkcji = nazwaSeriiAkcji;
  }

  public EmisjeAkcji liczbaAkcjiWSerii(String liczbaAkcjiWSerii) {
    this.liczbaAkcjiWSerii = liczbaAkcjiWSerii;
    return this;
  }

   /**
   * Get liczbaAkcjiWSerii
   * @return liczbaAkcjiWSerii
  **/
  @Schema(description = "")
  public String getLiczbaAkcjiWSerii() {
    return liczbaAkcjiWSerii;
  }

  public void setLiczbaAkcjiWSerii(String liczbaAkcjiWSerii) {
    this.liczbaAkcjiWSerii = liczbaAkcjiWSerii;
  }

  public EmisjeAkcji czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania(String czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania) {
    this.czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania = czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania;
    return this;
  }

   /**
   * Get czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania
   * @return czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania
  **/
  @Schema(description = "")
  public String getCzyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania() {
    return czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania;
  }

  public void setCzyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania(String czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania) {
    this.czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania = czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmisjeAkcji emisjeAkcji = (EmisjeAkcji) o;
    return Objects.equals(this.nazwaSeriiAkcji, emisjeAkcji.nazwaSeriiAkcji) &&
        Objects.equals(this.liczbaAkcjiWSerii, emisjeAkcji.liczbaAkcjiWSerii) &&
        Objects.equals(this.czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania, emisjeAkcji.czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwaSeriiAkcji, liczbaAkcjiWSerii, czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmisjeAkcji {\n");
    
    sb.append("    nazwaSeriiAkcji: ").append(toIndentedString(nazwaSeriiAkcji)).append("\n");
    sb.append("    liczbaAkcjiWSerii: ").append(toIndentedString(liczbaAkcjiWSerii)).append("\n");
    sb.append("    czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania: ").append(toIndentedString(czyAkcjeUprzywilejowaneLiczbaAkcjiRodzajUprzywilejowania)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
