/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Numery faktur zaliczkowych lub ich numery KSeF, jeśli zostały wystawione z użyciem KSeF
 */
@Schema(description = "Numery faktur zaliczkowych lub ich numery KSeF, jeśli zostały wystawione z użyciem KSeF")

public class FakturaZaliczkowa {
  @JsonProperty("NrKSeFZN")
  private Integer nrKSeFZN = null;

  @JsonProperty("NrFaZaliczkowej")
  private String nrFaZaliczkowej = null;

  @JsonProperty("NrKSeFFaZaliczkowej")
  private String nrKSeFFaZaliczkowej = null;

  public FakturaZaliczkowa nrKSeFZN(Integer nrKSeFZN) {
    this.nrKSeFZN = nrKSeFZN;
    return this;
  }

   /**
   * Get nrKSeFZN
   * @return nrKSeFZN
  **/
  @Schema(description = "")
  public Integer getNrKSeFZN() {
    return nrKSeFZN;
  }

  public void setNrKSeFZN(Integer nrKSeFZN) {
    this.nrKSeFZN = nrKSeFZN;
  }

  public FakturaZaliczkowa nrFaZaliczkowej(String nrFaZaliczkowej) {
    this.nrFaZaliczkowej = nrFaZaliczkowej;
    return this;
  }

   /**
   * Get nrFaZaliczkowej
   * @return nrFaZaliczkowej
  **/
  @Schema(description = "")
  public String getNrFaZaliczkowej() {
    return nrFaZaliczkowej;
  }

  public void setNrFaZaliczkowej(String nrFaZaliczkowej) {
    this.nrFaZaliczkowej = nrFaZaliczkowej;
  }

  public FakturaZaliczkowa nrKSeFFaZaliczkowej(String nrKSeFFaZaliczkowej) {
    this.nrKSeFFaZaliczkowej = nrKSeFFaZaliczkowej;
    return this;
  }

   /**
   * Get nrKSeFFaZaliczkowej
   * @return nrKSeFFaZaliczkowej
  **/
  @Schema(description = "")
  public String getNrKSeFFaZaliczkowej() {
    return nrKSeFFaZaliczkowej;
  }

  public void setNrKSeFFaZaliczkowej(String nrKSeFFaZaliczkowej) {
    this.nrKSeFFaZaliczkowej = nrKSeFFaZaliczkowej;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FakturaZaliczkowa fakturaZaliczkowa = (FakturaZaliczkowa) o;
    return Objects.equals(this.nrKSeFZN, fakturaZaliczkowa.nrKSeFZN) &&
        Objects.equals(this.nrFaZaliczkowej, fakturaZaliczkowa.nrFaZaliczkowej) &&
        Objects.equals(this.nrKSeFFaZaliczkowej, fakturaZaliczkowa.nrKSeFFaZaliczkowej);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrKSeFZN, nrFaZaliczkowej, nrKSeFFaZaliczkowej);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FakturaZaliczkowa {\n");
    
    sb.append("    nrKSeFZN: ").append(toIndentedString(nrKSeFZN)).append("\n");
    sb.append("    nrFaZaliczkowej: ").append(toIndentedString(nrFaZaliczkowej)).append("\n");
    sb.append("    nrKSeFFaZaliczkowej: ").append(toIndentedString(nrKSeFFaZaliczkowej)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
