/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import pl.nip24.client.model.TGTU;
import pl.nip24.client.model.TOznaczenieProcedury;
import pl.nip24.client.model.TStawkaPodatku;
/**
 * Szczegółowe pozycje faktury w walucie, w której wystawiono fakturę - węzeł opcjonalny dla faktury zaliczkowej, faktury korygującej fakturę zaliczkową, oraz faktur korygujących dotyczących wszystkich dostaw towarów lub usług dokonanych lub świadczonych w danym okresie, o których mowa w art. 106j ust. 3 ustawy, dla których należy podać dane dotyczące opustu lub obniżki w podziale na stawki podatku i procedury w części Fa. W przypadku faktur korygujących, o których mowa w art. 106j ust. 3 ustawy, gdy opust lub obniżka ceny odnosi się do części dostaw towarów lub usług dokonanych lub świadczonych w danym okresie w części FaWiersz należy podać nazwy (rodzaje) towarów lub usług objętych korektą. W przypadku faktur, o których mowa w art. 106f ust. 3 ustawy, należy wykazać pełne wartości zamówienia lub umowy. W przypadku faktur korygujących pozycje faktury (w tym faktur korygujących faktury, o których mowa w art. 106f ust. 3 ustawy, jeśli korekta dotyczy wartości zamówienia), należy wykazać różnice wynikające z korekty poszczególnych pozycji lub dane pozycji korygowanych w stanie przed korektą i po korekcie jako osobne wiersze. W przypadku faktur korygujących faktury, o których mowa w art. 106f ust. 3 ustawy, jeśli korekta nie dotyczy wartości zamówienia i jednocześnie zmienia wysokość podstawy opodatkowania lub podatku, należy wprowadzić zapis wg stanu przed korektą i zapis w stanie po korekcie w celu potwierdzenia braku zmiany wartości danej pozycji faktury
 */
@Schema(description = "Szczegółowe pozycje faktury w walucie, w której wystawiono fakturę - węzeł opcjonalny dla faktury zaliczkowej, faktury korygującej fakturę zaliczkową, oraz faktur korygujących dotyczących wszystkich dostaw towarów lub usług dokonanych lub świadczonych w danym okresie, o których mowa w art. 106j ust. 3 ustawy, dla których należy podać dane dotyczące opustu lub obniżki w podziale na stawki podatku i procedury w części Fa. W przypadku faktur korygujących, o których mowa w art. 106j ust. 3 ustawy, gdy opust lub obniżka ceny odnosi się do części dostaw towarów lub usług dokonanych lub świadczonych w danym okresie w części FaWiersz należy podać nazwy (rodzaje) towarów lub usług objętych korektą. W przypadku faktur, o których mowa w art. 106f ust. 3 ustawy, należy wykazać pełne wartości zamówienia lub umowy. W przypadku faktur korygujących pozycje faktury (w tym faktur korygujących faktury, o których mowa w art. 106f ust. 3 ustawy, jeśli korekta dotyczy wartości zamówienia), należy wykazać różnice wynikające z korekty poszczególnych pozycji lub dane pozycji korygowanych w stanie przed korektą i po korekcie jako osobne wiersze. W przypadku faktur korygujących faktury, o których mowa w art. 106f ust. 3 ustawy, jeśli korekta nie dotyczy wartości zamówienia i jednocześnie zmienia wysokość podstawy opodatkowania lub podatku, należy wprowadzić zapis wg stanu przed korektą i zapis w stanie po korekcie w celu potwierdzenia braku zmiany wartości danej pozycji faktury")

public class FaWiersz {
  @JsonProperty("NrWierszaFa")
  private Integer nrWierszaFa = null;

  @JsonProperty("UU_ID")
  private String UU_ID = null;

  @JsonProperty("P_6A")
  private LocalDate p6A = null;

  @JsonProperty("P_7")
  private String p7 = null;

  @JsonProperty("Indeks")
  private String indeks = null;

  @JsonProperty("GTIN")
  private String GTIN = null;

  @JsonProperty("PKWiU")
  private String pkWiU = null;

  @JsonProperty("CN")
  private String CN = null;

  @JsonProperty("PKOB")
  private String PKOB = null;

  @JsonProperty("P_8A")
  private String p8A = null;

  @JsonProperty("P_8B")
  private Double p8B = null;

  @JsonProperty("P_9A")
  private Double p9A = null;

  @JsonProperty("P_9B")
  private Double p9B = null;

  @JsonProperty("P_10")
  private Double p10 = null;

  @JsonProperty("P_11")
  private Double p11 = null;

  @JsonProperty("P_11A")
  private Double p11A = null;

  @JsonProperty("P_11Vat")
  private Double p11Vat = null;

  @JsonProperty("P_12")
  private TStawkaPodatku p12 = null;

  @JsonProperty("P_12_XII")
  private Double p12XII = null;

  @JsonProperty("P_12_Zal_15")
  private Integer p12Zal15 = null;

  @JsonProperty("KwotaAkcyzy")
  private Double kwotaAkcyzy = null;

  @JsonProperty("GTU")
  private TGTU GTU = null;

  @JsonProperty("Procedura")
  private TOznaczenieProcedury procedura = null;

  @JsonProperty("KursWaluty")
  private Double kursWaluty = null;

  @JsonProperty("StanPrzed")
  private Integer stanPrzed = null;

  public FaWiersz nrWierszaFa(Integer nrWierszaFa) {
    this.nrWierszaFa = nrWierszaFa;
    return this;
  }

   /**
   * Get nrWierszaFa
   * @return nrWierszaFa
  **/
  @Schema(required = true, description = "")
  public Integer getNrWierszaFa() {
    return nrWierszaFa;
  }

  public void setNrWierszaFa(Integer nrWierszaFa) {
    this.nrWierszaFa = nrWierszaFa;
  }

  public FaWiersz UU_ID(String UU_ID) {
    this.UU_ID = UU_ID;
    return this;
  }

   /**
   * Get UU_ID
   * @return UU_ID
  **/
  @Schema(description = "")
  public String getUUID() {
    return UU_ID;
  }

  public void setUUID(String UU_ID) {
    this.UU_ID = UU_ID;
  }

  public FaWiersz p6A(LocalDate p6A) {
    this.p6A = p6A;
    return this;
  }

   /**
   * Get p6A
   * @return p6A
  **/
  @Schema(description = "")
  public LocalDate getP6A() {
    return p6A;
  }

  public void setP6A(LocalDate p6A) {
    this.p6A = p6A;
  }

  public FaWiersz p7(String p7) {
    this.p7 = p7;
    return this;
  }

   /**
   * Get p7
   * @return p7
  **/
  @Schema(description = "")
  public String getP7() {
    return p7;
  }

  public void setP7(String p7) {
    this.p7 = p7;
  }

  public FaWiersz indeks(String indeks) {
    this.indeks = indeks;
    return this;
  }

   /**
   * Get indeks
   * @return indeks
  **/
  @Schema(description = "")
  public String getIndeks() {
    return indeks;
  }

  public void setIndeks(String indeks) {
    this.indeks = indeks;
  }

  public FaWiersz GTIN(String GTIN) {
    this.GTIN = GTIN;
    return this;
  }

   /**
   * Get GTIN
   * @return GTIN
  **/
  @Schema(description = "")
  public String getGTIN() {
    return GTIN;
  }

  public void setGTIN(String GTIN) {
    this.GTIN = GTIN;
  }

  public FaWiersz pkWiU(String pkWiU) {
    this.pkWiU = pkWiU;
    return this;
  }

   /**
   * Get pkWiU
   * @return pkWiU
  **/
  @Schema(description = "")
  public String getPkWiU() {
    return pkWiU;
  }

  public void setPkWiU(String pkWiU) {
    this.pkWiU = pkWiU;
  }

  public FaWiersz CN(String CN) {
    this.CN = CN;
    return this;
  }

   /**
   * Get CN
   * @return CN
  **/
  @Schema(description = "")
  public String getCN() {
    return CN;
  }

  public void setCN(String CN) {
    this.CN = CN;
  }

  public FaWiersz PKOB(String PKOB) {
    this.PKOB = PKOB;
    return this;
  }

   /**
   * Get PKOB
   * @return PKOB
  **/
  @Schema(description = "")
  public String getPKOB() {
    return PKOB;
  }

  public void setPKOB(String PKOB) {
    this.PKOB = PKOB;
  }

  public FaWiersz p8A(String p8A) {
    this.p8A = p8A;
    return this;
  }

   /**
   * Get p8A
   * @return p8A
  **/
  @Schema(description = "")
  public String getP8A() {
    return p8A;
  }

  public void setP8A(String p8A) {
    this.p8A = p8A;
  }

  public FaWiersz p8B(Double p8B) {
    this.p8B = p8B;
    return this;
  }

   /**
   * Get p8B
   * @return p8B
  **/
  @Schema(description = "")
  public Double getP8B() {
    return p8B;
  }

  public void setP8B(Double p8B) {
    this.p8B = p8B;
  }

  public FaWiersz p9A(Double p9A) {
    this.p9A = p9A;
    return this;
  }

   /**
   * Get p9A
   * @return p9A
  **/
  @Schema(description = "")
  public Double getP9A() {
    return p9A;
  }

  public void setP9A(Double p9A) {
    this.p9A = p9A;
  }

  public FaWiersz p9B(Double p9B) {
    this.p9B = p9B;
    return this;
  }

   /**
   * Get p9B
   * @return p9B
  **/
  @Schema(description = "")
  public Double getP9B() {
    return p9B;
  }

  public void setP9B(Double p9B) {
    this.p9B = p9B;
  }

  public FaWiersz p10(Double p10) {
    this.p10 = p10;
    return this;
  }

   /**
   * Get p10
   * @return p10
  **/
  @Schema(description = "")
  public Double getP10() {
    return p10;
  }

  public void setP10(Double p10) {
    this.p10 = p10;
  }

  public FaWiersz p11(Double p11) {
    this.p11 = p11;
    return this;
  }

   /**
   * Get p11
   * @return p11
  **/
  @Schema(description = "")
  public Double getP11() {
    return p11;
  }

  public void setP11(Double p11) {
    this.p11 = p11;
  }

  public FaWiersz p11A(Double p11A) {
    this.p11A = p11A;
    return this;
  }

   /**
   * Get p11A
   * @return p11A
  **/
  @Schema(description = "")
  public Double getP11A() {
    return p11A;
  }

  public void setP11A(Double p11A) {
    this.p11A = p11A;
  }

  public FaWiersz p11Vat(Double p11Vat) {
    this.p11Vat = p11Vat;
    return this;
  }

   /**
   * Get p11Vat
   * @return p11Vat
  **/
  @Schema(description = "")
  public Double getP11Vat() {
    return p11Vat;
  }

  public void setP11Vat(Double p11Vat) {
    this.p11Vat = p11Vat;
  }

  public FaWiersz p12(TStawkaPodatku p12) {
    this.p12 = p12;
    return this;
  }

   /**
   * Get p12
   * @return p12
  **/
  @Schema(description = "")
  public TStawkaPodatku getP12() {
    return p12;
  }

  public void setP12(TStawkaPodatku p12) {
    this.p12 = p12;
  }

  public FaWiersz p12XII(Double p12XII) {
    this.p12XII = p12XII;
    return this;
  }

   /**
   * Get p12XII
   * @return p12XII
  **/
  @Schema(description = "")
  public Double getP12XII() {
    return p12XII;
  }

  public void setP12XII(Double p12XII) {
    this.p12XII = p12XII;
  }

  public FaWiersz p12Zal15(Integer p12Zal15) {
    this.p12Zal15 = p12Zal15;
    return this;
  }

   /**
   * Get p12Zal15
   * @return p12Zal15
  **/
  @Schema(description = "")
  public Integer getP12Zal15() {
    return p12Zal15;
  }

  public void setP12Zal15(Integer p12Zal15) {
    this.p12Zal15 = p12Zal15;
  }

  public FaWiersz kwotaAkcyzy(Double kwotaAkcyzy) {
    this.kwotaAkcyzy = kwotaAkcyzy;
    return this;
  }

   /**
   * Get kwotaAkcyzy
   * @return kwotaAkcyzy
  **/
  @Schema(description = "")
  public Double getKwotaAkcyzy() {
    return kwotaAkcyzy;
  }

  public void setKwotaAkcyzy(Double kwotaAkcyzy) {
    this.kwotaAkcyzy = kwotaAkcyzy;
  }

  public FaWiersz GTU(TGTU GTU) {
    this.GTU = GTU;
    return this;
  }

   /**
   * Get GTU
   * @return GTU
  **/
  @Schema(description = "")
  public TGTU getGTU() {
    return GTU;
  }

  public void setGTU(TGTU GTU) {
    this.GTU = GTU;
  }

  public FaWiersz procedura(TOznaczenieProcedury procedura) {
    this.procedura = procedura;
    return this;
  }

   /**
   * Get procedura
   * @return procedura
  **/
  @Schema(description = "")
  public TOznaczenieProcedury getProcedura() {
    return procedura;
  }

  public void setProcedura(TOznaczenieProcedury procedura) {
    this.procedura = procedura;
  }

  public FaWiersz kursWaluty(Double kursWaluty) {
    this.kursWaluty = kursWaluty;
    return this;
  }

   /**
   * Get kursWaluty
   * @return kursWaluty
  **/
  @Schema(description = "")
  public Double getKursWaluty() {
    return kursWaluty;
  }

  public void setKursWaluty(Double kursWaluty) {
    this.kursWaluty = kursWaluty;
  }

  public FaWiersz stanPrzed(Integer stanPrzed) {
    this.stanPrzed = stanPrzed;
    return this;
  }

   /**
   * Get stanPrzed
   * @return stanPrzed
  **/
  @Schema(description = "")
  public Integer getStanPrzed() {
    return stanPrzed;
  }

  public void setStanPrzed(Integer stanPrzed) {
    this.stanPrzed = stanPrzed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaWiersz faWiersz = (FaWiersz) o;
    return Objects.equals(this.nrWierszaFa, faWiersz.nrWierszaFa) &&
        Objects.equals(this.UU_ID, faWiersz.UU_ID) &&
        Objects.equals(this.p6A, faWiersz.p6A) &&
        Objects.equals(this.p7, faWiersz.p7) &&
        Objects.equals(this.indeks, faWiersz.indeks) &&
        Objects.equals(this.GTIN, faWiersz.GTIN) &&
        Objects.equals(this.pkWiU, faWiersz.pkWiU) &&
        Objects.equals(this.CN, faWiersz.CN) &&
        Objects.equals(this.PKOB, faWiersz.PKOB) &&
        Objects.equals(this.p8A, faWiersz.p8A) &&
        Objects.equals(this.p8B, faWiersz.p8B) &&
        Objects.equals(this.p9A, faWiersz.p9A) &&
        Objects.equals(this.p9B, faWiersz.p9B) &&
        Objects.equals(this.p10, faWiersz.p10) &&
        Objects.equals(this.p11, faWiersz.p11) &&
        Objects.equals(this.p11A, faWiersz.p11A) &&
        Objects.equals(this.p11Vat, faWiersz.p11Vat) &&
        Objects.equals(this.p12, faWiersz.p12) &&
        Objects.equals(this.p12XII, faWiersz.p12XII) &&
        Objects.equals(this.p12Zal15, faWiersz.p12Zal15) &&
        Objects.equals(this.kwotaAkcyzy, faWiersz.kwotaAkcyzy) &&
        Objects.equals(this.GTU, faWiersz.GTU) &&
        Objects.equals(this.procedura, faWiersz.procedura) &&
        Objects.equals(this.kursWaluty, faWiersz.kursWaluty) &&
        Objects.equals(this.stanPrzed, faWiersz.stanPrzed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrWierszaFa, UU_ID, p6A, p7, indeks, GTIN, pkWiU, CN, PKOB, p8A, p8B, p9A, p9B, p10, p11, p11A, p11Vat, p12, p12XII, p12Zal15, kwotaAkcyzy, GTU, procedura, kursWaluty, stanPrzed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaWiersz {\n");
    
    sb.append("    nrWierszaFa: ").append(toIndentedString(nrWierszaFa)).append("\n");
    sb.append("    UU_ID: ").append(toIndentedString(UU_ID)).append("\n");
    sb.append("    p6A: ").append(toIndentedString(p6A)).append("\n");
    sb.append("    p7: ").append(toIndentedString(p7)).append("\n");
    sb.append("    indeks: ").append(toIndentedString(indeks)).append("\n");
    sb.append("    GTIN: ").append(toIndentedString(GTIN)).append("\n");
    sb.append("    pkWiU: ").append(toIndentedString(pkWiU)).append("\n");
    sb.append("    CN: ").append(toIndentedString(CN)).append("\n");
    sb.append("    PKOB: ").append(toIndentedString(PKOB)).append("\n");
    sb.append("    p8A: ").append(toIndentedString(p8A)).append("\n");
    sb.append("    p8B: ").append(toIndentedString(p8B)).append("\n");
    sb.append("    p9A: ").append(toIndentedString(p9A)).append("\n");
    sb.append("    p9B: ").append(toIndentedString(p9B)).append("\n");
    sb.append("    p10: ").append(toIndentedString(p10)).append("\n");
    sb.append("    p11: ").append(toIndentedString(p11)).append("\n");
    sb.append("    p11A: ").append(toIndentedString(p11A)).append("\n");
    sb.append("    p11Vat: ").append(toIndentedString(p11Vat)).append("\n");
    sb.append("    p12: ").append(toIndentedString(p12)).append("\n");
    sb.append("    p12XII: ").append(toIndentedString(p12XII)).append("\n");
    sb.append("    p12Zal15: ").append(toIndentedString(p12Zal15)).append("\n");
    sb.append("    kwotaAkcyzy: ").append(toIndentedString(kwotaAkcyzy)).append("\n");
    sb.append("    GTU: ").append(toIndentedString(GTU)).append("\n");
    sb.append("    procedura: ").append(toIndentedString(procedura)).append("\n");
    sb.append("    kursWaluty: ").append(toIndentedString(kursWaluty)).append("\n");
    sb.append("    stanPrzed: ").append(toIndentedString(stanPrzed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
