/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * IdentyfikatoryPodmiotu
 */


public class IdentyfikatoryPodmiotu {
  @JsonProperty("nip")
  private String nip = null;

  @JsonProperty("regon")
  private String regon = null;

  @JsonProperty("krs")
  private String krs = null;

  public IdentyfikatoryPodmiotu nip(String nip) {
    this.nip = nip;
    return this;
  }

   /**
   * Get nip
   * @return nip
  **/
  @Schema(description = "")
  public String getNip() {
    return nip;
  }

  public void setNip(String nip) {
    this.nip = nip;
  }

  public IdentyfikatoryPodmiotu regon(String regon) {
    this.regon = regon;
    return this;
  }

   /**
   * Get regon
   * @return regon
  **/
  @Schema(description = "")
  public String getRegon() {
    return regon;
  }

  public void setRegon(String regon) {
    this.regon = regon;
  }

  public IdentyfikatoryPodmiotu krs(String krs) {
    this.krs = krs;
    return this;
  }

   /**
   * Get krs
   * @return krs
  **/
  @Schema(description = "")
  public String getKrs() {
    return krs;
  }

  public void setKrs(String krs) {
    this.krs = krs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentyfikatoryPodmiotu identyfikatoryPodmiotu = (IdentyfikatoryPodmiotu) o;
    return Objects.equals(this.nip, identyfikatoryPodmiotu.nip) &&
        Objects.equals(this.regon, identyfikatoryPodmiotu.regon) &&
        Objects.equals(this.krs, identyfikatoryPodmiotu.krs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nip, regon, krs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentyfikatoryPodmiotu {\n");
    
    sb.append("    nip: ").append(toIndentedString(nip)).append("\n");
    sb.append("    regon: ").append(toIndentedString(regon)).append("\n");
    sb.append("    krs: ").append(toIndentedString(krs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
