/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * IdentyfikatorOsoby
 */


public class IdentyfikatorOsoby {
  @JsonProperty("pesel")
  private String pesel = null;

  @JsonProperty("numerPaszportu")
  private String numerPaszportu = null;

  public IdentyfikatorOsoby pesel(String pesel) {
    this.pesel = pesel;
    return this;
  }

   /**
   * Get pesel
   * @return pesel
  **/
  @Schema(description = "")
  public String getPesel() {
    return pesel;
  }

  public void setPesel(String pesel) {
    this.pesel = pesel;
  }

  public IdentyfikatorOsoby numerPaszportu(String numerPaszportu) {
    this.numerPaszportu = numerPaszportu;
    return this;
  }

   /**
   * Get numerPaszportu
   * @return numerPaszportu
  **/
  @Schema(description = "")
  public String getNumerPaszportu() {
    return numerPaszportu;
  }

  public void setNumerPaszportu(String numerPaszportu) {
    this.numerPaszportu = numerPaszportu;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentyfikatorOsoby identyfikatorOsoby = (IdentyfikatorOsoby) o;
    return Objects.equals(this.pesel, identyfikatorOsoby.pesel) &&
        Objects.equals(this.numerPaszportu, identyfikatorOsoby.numerPaszportu);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pesel, numerPaszportu);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentyfikatorOsoby {\n");
    
    sb.append("    pesel: ").append(toIndentedString(pesel)).append("\n");
    sb.append("    numerPaszportu: ").append(toIndentedString(numerPaszportu)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
