/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ImionaOsoby
 */


public class ImionaOsoby {
  @JsonProperty("imie")
  private String imie = null;

  @JsonProperty("imieDrugie")
  private String imieDrugie = null;

  public ImionaOsoby imie(String imie) {
    this.imie = imie;
    return this;
  }

   /**
   * Get imie
   * @return imie
  **/
  @Schema(description = "")
  public String getImie() {
    return imie;
  }

  public void setImie(String imie) {
    this.imie = imie;
  }

  public ImionaOsoby imieDrugie(String imieDrugie) {
    this.imieDrugie = imieDrugie;
    return this;
  }

   /**
   * Get imieDrugie
   * @return imieDrugie
  **/
  @Schema(description = "")
  public String getImieDrugie() {
    return imieDrugie;
  }

  public void setImieDrugie(String imieDrugie) {
    this.imieDrugie = imieDrugie;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImionaOsoby imionaOsoby = (ImionaOsoby) o;
    return Objects.equals(this.imie, imionaOsoby.imie) &&
        Objects.equals(this.imieDrugie, imionaOsoby.imieDrugie);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imie, imieDrugie);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImionaOsoby {\n");
    
    sb.append("    imie: ").append(toIndentedString(imie)).append("\n");
    sb.append("    imieDrugie: ").append(toIndentedString(imieDrugie)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
