/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * InformacjaOUchyleniuUkladu
 */


public class InformacjaOUchyleniuUkladu {
  @JsonProperty("pole1")
  private String pole1 = null;

  @JsonProperty("pole2")
  private String pole2 = null;

  @JsonProperty("pole3")
  private String pole3 = null;

  @JsonProperty("pole4")
  private String pole4 = null;

  public InformacjaOUchyleniuUkladu pole1(String pole1) {
    this.pole1 = pole1;
    return this;
  }

   /**
   * Get pole1
   * @return pole1
  **/
  @Schema(description = "")
  public String getPole1() {
    return pole1;
  }

  public void setPole1(String pole1) {
    this.pole1 = pole1;
  }

  public InformacjaOUchyleniuUkladu pole2(String pole2) {
    this.pole2 = pole2;
    return this;
  }

   /**
   * Get pole2
   * @return pole2
  **/
  @Schema(description = "")
  public String getPole2() {
    return pole2;
  }

  public void setPole2(String pole2) {
    this.pole2 = pole2;
  }

  public InformacjaOUchyleniuUkladu pole3(String pole3) {
    this.pole3 = pole3;
    return this;
  }

   /**
   * Get pole3
   * @return pole3
  **/
  @Schema(description = "")
  public String getPole3() {
    return pole3;
  }

  public void setPole3(String pole3) {
    this.pole3 = pole3;
  }

  public InformacjaOUchyleniuUkladu pole4(String pole4) {
    this.pole4 = pole4;
    return this;
  }

   /**
   * Get pole4
   * @return pole4
  **/
  @Schema(description = "")
  public String getPole4() {
    return pole4;
  }

  public void setPole4(String pole4) {
    this.pole4 = pole4;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InformacjaOUchyleniuUkladu informacjaOUchyleniuUkladu = (InformacjaOUchyleniuUkladu) o;
    return Objects.equals(this.pole1, informacjaOUchyleniuUkladu.pole1) &&
        Objects.equals(this.pole2, informacjaOUchyleniuUkladu.pole2) &&
        Objects.equals(this.pole3, informacjaOUchyleniuUkladu.pole3) &&
        Objects.equals(this.pole4, informacjaOUchyleniuUkladu.pole4);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pole1, pole2, pole3, pole4);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InformacjaOUchyleniuUkladu {\n");
    
    sb.append("    pole1: ").append(toIndentedString(pole1)).append("\n");
    sb.append("    pole2: ").append(toIndentedString(pole2)).append("\n");
    sb.append("    pole3: ").append(toIndentedString(pole3)).append("\n");
    sb.append("    pole4: ").append(toIndentedString(pole4)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
