/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * InformacjaOOgloszeniuUpadlosci
 */


public class InformacjaOOgloszeniuUpadlosci {
  @JsonProperty("organWydajacy")
  private String organWydajacy = null;

  @JsonProperty("sygnatura")
  private String sygnatura = null;

  @JsonProperty("data")
  private String data = null;

  public InformacjaOOgloszeniuUpadlosci organWydajacy(String organWydajacy) {
    this.organWydajacy = organWydajacy;
    return this;
  }

   /**
   * Get organWydajacy
   * @return organWydajacy
  **/
  @Schema(description = "")
  public String getOrganWydajacy() {
    return organWydajacy;
  }

  public void setOrganWydajacy(String organWydajacy) {
    this.organWydajacy = organWydajacy;
  }

  public InformacjaOOgloszeniuUpadlosci sygnatura(String sygnatura) {
    this.sygnatura = sygnatura;
    return this;
  }

   /**
   * Get sygnatura
   * @return sygnatura
  **/
  @Schema(description = "")
  public String getSygnatura() {
    return sygnatura;
  }

  public void setSygnatura(String sygnatura) {
    this.sygnatura = sygnatura;
  }

  public InformacjaOOgloszeniuUpadlosci data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InformacjaOOgloszeniuUpadlosci informacjaOOgloszeniuUpadlosci = (InformacjaOOgloszeniuUpadlosci) o;
    return Objects.equals(this.organWydajacy, informacjaOOgloszeniuUpadlosci.organWydajacy) &&
        Objects.equals(this.sygnatura, informacjaOOgloszeniuUpadlosci.sygnatura) &&
        Objects.equals(this.data, informacjaOOgloszeniuUpadlosci.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organWydajacy, sygnatura, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InformacjaOOgloszeniuUpadlosci {\n");
    
    sb.append("    organWydajacy: ").append(toIndentedString(organWydajacy)).append("\n");
    sb.append("    sygnatura: ").append(toIndentedString(sygnatura)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
