/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.Adres;
import pl.nip24.client.model.Siedziba;
/**
 * JednostkiTerenoweOddzialy
 */


public class JednostkiTerenoweOddzialy {
  @JsonProperty("nazwa")
  private String nazwa = null;

  @JsonProperty("siedziba")
  private Siedziba siedziba = null;

  @JsonProperty("adres")
  private Adres adres = null;

  public JednostkiTerenoweOddzialy nazwa(String nazwa) {
    this.nazwa = nazwa;
    return this;
  }

   /**
   * Get nazwa
   * @return nazwa
  **/
  @Schema(description = "")
  public String getNazwa() {
    return nazwa;
  }

  public void setNazwa(String nazwa) {
    this.nazwa = nazwa;
  }

  public JednostkiTerenoweOddzialy siedziba(Siedziba siedziba) {
    this.siedziba = siedziba;
    return this;
  }

   /**
   * Get siedziba
   * @return siedziba
  **/
  @Schema(description = "")
  public Siedziba getSiedziba() {
    return siedziba;
  }

  public void setSiedziba(Siedziba siedziba) {
    this.siedziba = siedziba;
  }

  public JednostkiTerenoweOddzialy adres(Adres adres) {
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @Schema(description = "")
  public Adres getAdres() {
    return adres;
  }

  public void setAdres(Adres adres) {
    this.adres = adres;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JednostkiTerenoweOddzialy jednostkiTerenoweOddzialy = (JednostkiTerenoweOddzialy) o;
    return Objects.equals(this.nazwa, jednostkiTerenoweOddzialy.nazwa) &&
        Objects.equals(this.siedziba, jednostkiTerenoweOddzialy.siedziba) &&
        Objects.equals(this.adres, jednostkiTerenoweOddzialy.adres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwa, siedziba, adres);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JednostkiTerenoweOddzialy {\n");
    
    sb.append("    nazwa: ").append(toIndentedString(nazwa)).append("\n");
    sb.append("    siedziba: ").append(toIndentedString(siedziba)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
