/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.CzescKapitaluWplaconegoPokrytego;
import pl.nip24.client.model.WartoscJednejAkcji;
import pl.nip24.client.model.WysokoscKapitaluZakladowego;
/**
 * Kapital
 */


public class Kapital {
  @JsonProperty("wniesioneAporty")
  private Object wniesioneAporty = null;

  @JsonProperty("lacznaLiczbaAkcjiUdzialow")
  private String lacznaLiczbaAkcjiUdzialow = null;

  @JsonProperty("wysokoscKapitaluZakladowego")
  private WysokoscKapitaluZakladowego wysokoscKapitaluZakladowego = null;

  @JsonProperty("wartoscJednejAkcji")
  private WartoscJednejAkcji wartoscJednejAkcji = null;

  @JsonProperty("czescKapitaluWplaconegoPokrytego")
  private CzescKapitaluWplaconegoPokrytego czescKapitaluWplaconegoPokrytego = null;

  public Kapital wniesioneAporty(Object wniesioneAporty) {
    this.wniesioneAporty = wniesioneAporty;
    return this;
  }

   /**
   * Get wniesioneAporty
   * @return wniesioneAporty
  **/
  @Schema(description = "")
  public Object getWniesioneAporty() {
    return wniesioneAporty;
  }

  public void setWniesioneAporty(Object wniesioneAporty) {
    this.wniesioneAporty = wniesioneAporty;
  }

  public Kapital lacznaLiczbaAkcjiUdzialow(String lacznaLiczbaAkcjiUdzialow) {
    this.lacznaLiczbaAkcjiUdzialow = lacznaLiczbaAkcjiUdzialow;
    return this;
  }

   /**
   * Get lacznaLiczbaAkcjiUdzialow
   * @return lacznaLiczbaAkcjiUdzialow
  **/
  @Schema(description = "")
  public String getLacznaLiczbaAkcjiUdzialow() {
    return lacznaLiczbaAkcjiUdzialow;
  }

  public void setLacznaLiczbaAkcjiUdzialow(String lacznaLiczbaAkcjiUdzialow) {
    this.lacznaLiczbaAkcjiUdzialow = lacznaLiczbaAkcjiUdzialow;
  }

  public Kapital wysokoscKapitaluZakladowego(WysokoscKapitaluZakladowego wysokoscKapitaluZakladowego) {
    this.wysokoscKapitaluZakladowego = wysokoscKapitaluZakladowego;
    return this;
  }

   /**
   * Get wysokoscKapitaluZakladowego
   * @return wysokoscKapitaluZakladowego
  **/
  @Schema(description = "")
  public WysokoscKapitaluZakladowego getWysokoscKapitaluZakladowego() {
    return wysokoscKapitaluZakladowego;
  }

  public void setWysokoscKapitaluZakladowego(WysokoscKapitaluZakladowego wysokoscKapitaluZakladowego) {
    this.wysokoscKapitaluZakladowego = wysokoscKapitaluZakladowego;
  }

  public Kapital wartoscJednejAkcji(WartoscJednejAkcji wartoscJednejAkcji) {
    this.wartoscJednejAkcji = wartoscJednejAkcji;
    return this;
  }

   /**
   * Get wartoscJednejAkcji
   * @return wartoscJednejAkcji
  **/
  @Schema(description = "")
  public WartoscJednejAkcji getWartoscJednejAkcji() {
    return wartoscJednejAkcji;
  }

  public void setWartoscJednejAkcji(WartoscJednejAkcji wartoscJednejAkcji) {
    this.wartoscJednejAkcji = wartoscJednejAkcji;
  }

  public Kapital czescKapitaluWplaconegoPokrytego(CzescKapitaluWplaconegoPokrytego czescKapitaluWplaconegoPokrytego) {
    this.czescKapitaluWplaconegoPokrytego = czescKapitaluWplaconegoPokrytego;
    return this;
  }

   /**
   * Get czescKapitaluWplaconegoPokrytego
   * @return czescKapitaluWplaconegoPokrytego
  **/
  @Schema(description = "")
  public CzescKapitaluWplaconegoPokrytego getCzescKapitaluWplaconegoPokrytego() {
    return czescKapitaluWplaconegoPokrytego;
  }

  public void setCzescKapitaluWplaconegoPokrytego(CzescKapitaluWplaconegoPokrytego czescKapitaluWplaconegoPokrytego) {
    this.czescKapitaluWplaconegoPokrytego = czescKapitaluWplaconegoPokrytego;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Kapital kapital = (Kapital) o;
    return Objects.equals(this.wniesioneAporty, kapital.wniesioneAporty) &&
        Objects.equals(this.lacznaLiczbaAkcjiUdzialow, kapital.lacznaLiczbaAkcjiUdzialow) &&
        Objects.equals(this.wysokoscKapitaluZakladowego, kapital.wysokoscKapitaluZakladowego) &&
        Objects.equals(this.wartoscJednejAkcji, kapital.wartoscJednejAkcji) &&
        Objects.equals(this.czescKapitaluWplaconegoPokrytego, kapital.czescKapitaluWplaconegoPokrytego);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wniesioneAporty, lacznaLiczbaAkcjiUdzialow, wysokoscKapitaluZakladowego, wartoscJednejAkcji, czescKapitaluWplaconegoPokrytego);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Kapital {\n");
    
    sb.append("    wniesioneAporty: ").append(toIndentedString(wniesioneAporty)).append("\n");
    sb.append("    lacznaLiczbaAkcjiUdzialow: ").append(toIndentedString(lacznaLiczbaAkcjiUdzialow)).append("\n");
    sb.append("    wysokoscKapitaluZakladowego: ").append(toIndentedString(wysokoscKapitaluZakladowego)).append("\n");
    sb.append("    wartoscJednejAkcji: ").append(toIndentedString(wartoscJednejAkcji)).append("\n");
    sb.append("    czescKapitaluWplaconegoPokrytego: ").append(toIndentedString(czescKapitaluWplaconegoPokrytego)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
