/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets KsefInvoiceVersion
 */
public enum KsefInvoiceVersion {
  V1("v1"),
  V2("v2");

  private String value;

  KsefInvoiceVersion(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static KsefInvoiceVersion fromValue(String input) {
    for (KsefInvoiceVersion b : KsefInvoiceVersion.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
