/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.KsefInvoiceQueryStartRange;
/**
 * KsefInvoiceQueryStartRequest
 */


public class KsefInvoiceQueryStartRequest {
  @JsonProperty("sessionId")
  private String sessionId = null;

  /**
   * Gets or Sets subjectType
   */
  public enum SubjectTypeEnum {
    SUBJECT1("subject1"),
    SUBJECT2("subject2"),
    SUBJECT3("subject3"),
    SUBJECTAUTHORIZED("subjectAuthorized");

    private String value;

    SubjectTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SubjectTypeEnum fromValue(String input) {
      for (SubjectTypeEnum b : SubjectTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("subjectType")
  private SubjectTypeEnum subjectType = null;

  @JsonProperty("range")
  private KsefInvoiceQueryStartRange range = null;

  public KsefInvoiceQueryStartRequest sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @Schema(required = true, description = "")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public KsefInvoiceQueryStartRequest subjectType(SubjectTypeEnum subjectType) {
    this.subjectType = subjectType;
    return this;
  }

   /**
   * Get subjectType
   * @return subjectType
  **/
  @Schema(required = true, description = "")
  public SubjectTypeEnum getSubjectType() {
    return subjectType;
  }

  public void setSubjectType(SubjectTypeEnum subjectType) {
    this.subjectType = subjectType;
  }

  public KsefInvoiceQueryStartRequest range(KsefInvoiceQueryStartRange range) {
    this.range = range;
    return this;
  }

   /**
   * Get range
   * @return range
  **/
  @Schema(description = "")
  public KsefInvoiceQueryStartRange getRange() {
    return range;
  }

  public void setRange(KsefInvoiceQueryStartRange range) {
    this.range = range;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KsefInvoiceQueryStartRequest ksefInvoiceQueryStartRequest = (KsefInvoiceQueryStartRequest) o;
    return Objects.equals(this.sessionId, ksefInvoiceQueryStartRequest.sessionId) &&
        Objects.equals(this.subjectType, ksefInvoiceQueryStartRequest.subjectType) &&
        Objects.equals(this.range, ksefInvoiceQueryStartRequest.range);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, subjectType, range);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KsefInvoiceQueryStartRequest {\n");
    
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    subjectType: ").append(toIndentedString(subjectType)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
