/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import pl.nip24.client.model.Error;
/**
 * KsefInvoiceStatusResponse
 */


public class KsefInvoiceStatusResponse {
  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PROCESSING("processing"),
    ACCEPTED("accepted"),
    REJECTED("rejected");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("acquisitionTimestamp")
  private LocalDateTime acquisitionTimestamp = null;

  @JsonProperty("ksefReferenceNumber")
  private String ksefReferenceNumber = null;

  @JsonProperty("invoiceNumber")
  private String invoiceNumber = null;

  @JsonProperty("error")
  private Error error = null;

  public KsefInvoiceStatusResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public KsefInvoiceStatusResponse acquisitionTimestamp(LocalDateTime acquisitionTimestamp) {
    this.acquisitionTimestamp = acquisitionTimestamp;
    return this;
  }

   /**
   * Get acquisitionTimestamp
   * @return acquisitionTimestamp
  **/
  @Schema(description = "")
  public LocalDateTime getAcquisitionTimestamp() {
    return acquisitionTimestamp;
  }

  public void setAcquisitionTimestamp(LocalDateTime acquisitionTimestamp) {
    this.acquisitionTimestamp = acquisitionTimestamp;
  }

  public KsefInvoiceStatusResponse ksefReferenceNumber(String ksefReferenceNumber) {
    this.ksefReferenceNumber = ksefReferenceNumber;
    return this;
  }

   /**
   * Get ksefReferenceNumber
   * @return ksefReferenceNumber
  **/
  @Schema(description = "")
  public String getKsefReferenceNumber() {
    return ksefReferenceNumber;
  }

  public void setKsefReferenceNumber(String ksefReferenceNumber) {
    this.ksefReferenceNumber = ksefReferenceNumber;
  }

  public KsefInvoiceStatusResponse invoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Get invoiceNumber
   * @return invoiceNumber
  **/
  @Schema(description = "")
  public String getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public KsefInvoiceStatusResponse error(Error error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @Schema(description = "")
  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KsefInvoiceStatusResponse ksefInvoiceStatusResponse = (KsefInvoiceStatusResponse) o;
    return Objects.equals(this.status, ksefInvoiceStatusResponse.status) &&
        Objects.equals(this.acquisitionTimestamp, ksefInvoiceStatusResponse.acquisitionTimestamp) &&
        Objects.equals(this.ksefReferenceNumber, ksefInvoiceStatusResponse.ksefReferenceNumber) &&
        Objects.equals(this.invoiceNumber, ksefInvoiceStatusResponse.invoiceNumber) &&
        Objects.equals(this.error, ksefInvoiceStatusResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, acquisitionTimestamp, ksefReferenceNumber, invoiceNumber, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KsefInvoiceStatusResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    acquisitionTimestamp: ").append(toIndentedString(acquisitionTimestamp)).append("\n");
    sb.append("    ksefReferenceNumber: ").append(toIndentedString(ksefReferenceNumber)).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
