/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * KsefInvoiceVisualizeRequest
 */


public class KsefInvoiceVisualizeRequest {
  @JsonProperty("includeLogo")
  private Boolean includeLogo = null;

  @JsonProperty("includeQrCode")
  private Boolean includeQrCode = null;

  /**
   * Gets or Sets outputFormat
   */
  public enum OutputFormatEnum {
    HTML("html"),
    PDF("pdf");

    private String value;

    OutputFormatEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OutputFormatEnum fromValue(String input) {
      for (OutputFormatEnum b : OutputFormatEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("outputFormat")
  private OutputFormatEnum outputFormat = null;

  /**
   * Gets or Sets outputLanguage
   */
  public enum OutputLanguageEnum {
    PL("pl");

    private String value;

    OutputLanguageEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OutputLanguageEnum fromValue(String input) {
      for (OutputLanguageEnum b : OutputLanguageEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("outputLanguage")
  private OutputLanguageEnum outputLanguage = null;

  @JsonProperty("invoiceKsefNumber")
  private String invoiceKsefNumber = null;

  @JsonProperty("invoiceData")
  private byte[] invoiceData = null;

  public KsefInvoiceVisualizeRequest includeLogo(Boolean includeLogo) {
    this.includeLogo = includeLogo;
    return this;
  }

   /**
   * Get includeLogo
   * @return includeLogo
  **/
  @Schema(required = true, description = "")
  public Boolean isIncludeLogo() {
    return includeLogo;
  }

  public void setIncludeLogo(Boolean includeLogo) {
    this.includeLogo = includeLogo;
  }

  public KsefInvoiceVisualizeRequest includeQrCode(Boolean includeQrCode) {
    this.includeQrCode = includeQrCode;
    return this;
  }

   /**
   * Get includeQrCode
   * @return includeQrCode
  **/
  @Schema(required = true, description = "")
  public Boolean isIncludeQrCode() {
    return includeQrCode;
  }

  public void setIncludeQrCode(Boolean includeQrCode) {
    this.includeQrCode = includeQrCode;
  }

  public KsefInvoiceVisualizeRequest outputFormat(OutputFormatEnum outputFormat) {
    this.outputFormat = outputFormat;
    return this;
  }

   /**
   * Get outputFormat
   * @return outputFormat
  **/
  @Schema(required = true, description = "")
  public OutputFormatEnum getOutputFormat() {
    return outputFormat;
  }

  public void setOutputFormat(OutputFormatEnum outputFormat) {
    this.outputFormat = outputFormat;
  }

  public KsefInvoiceVisualizeRequest outputLanguage(OutputLanguageEnum outputLanguage) {
    this.outputLanguage = outputLanguage;
    return this;
  }

   /**
   * Get outputLanguage
   * @return outputLanguage
  **/
  @Schema(required = true, description = "")
  public OutputLanguageEnum getOutputLanguage() {
    return outputLanguage;
  }

  public void setOutputLanguage(OutputLanguageEnum outputLanguage) {
    this.outputLanguage = outputLanguage;
  }

  public KsefInvoiceVisualizeRequest invoiceKsefNumber(String invoiceKsefNumber) {
    this.invoiceKsefNumber = invoiceKsefNumber;
    return this;
  }

   /**
   * Get invoiceKsefNumber
   * @return invoiceKsefNumber
  **/
  @Schema(required = true, description = "")
  public String getInvoiceKsefNumber() {
    return invoiceKsefNumber;
  }

  public void setInvoiceKsefNumber(String invoiceKsefNumber) {
    this.invoiceKsefNumber = invoiceKsefNumber;
  }

  public KsefInvoiceVisualizeRequest invoiceData(byte[] invoiceData) {
    this.invoiceData = invoiceData;
    return this;
  }

   /**
   * Get invoiceData
   * @return invoiceData
  **/
  @Schema(required = true, description = "")
  public byte[] getInvoiceData() {
    return invoiceData;
  }

  public void setInvoiceData(byte[] invoiceData) {
    this.invoiceData = invoiceData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KsefInvoiceVisualizeRequest ksefInvoiceVisualizeRequest = (KsefInvoiceVisualizeRequest) o;
    return Objects.equals(this.includeLogo, ksefInvoiceVisualizeRequest.includeLogo) &&
        Objects.equals(this.includeQrCode, ksefInvoiceVisualizeRequest.includeQrCode) &&
        Objects.equals(this.outputFormat, ksefInvoiceVisualizeRequest.outputFormat) &&
        Objects.equals(this.outputLanguage, ksefInvoiceVisualizeRequest.outputLanguage) &&
        Objects.equals(this.invoiceKsefNumber, ksefInvoiceVisualizeRequest.invoiceKsefNumber) &&
        Arrays.equals(this.invoiceData, ksefInvoiceVisualizeRequest.invoiceData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeLogo, includeQrCode, outputFormat, outputLanguage, invoiceKsefNumber, Arrays.hashCode(invoiceData));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KsefInvoiceVisualizeRequest {\n");
    
    sb.append("    includeLogo: ").append(toIndentedString(includeLogo)).append("\n");
    sb.append("    includeQrCode: ").append(toIndentedString(includeQrCode)).append("\n");
    sb.append("    outputFormat: ").append(toIndentedString(outputFormat)).append("\n");
    sb.append("    outputLanguage: ").append(toIndentedString(outputLanguage)).append("\n");
    sb.append("    invoiceKsefNumber: ").append(toIndentedString(invoiceKsefNumber)).append("\n");
    sb.append("    invoiceData: ").append(toIndentedString(invoiceData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
