/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Osoba;
/**
 * Likwidacja
 */


public class Likwidacja {
  @JsonProperty("otwarcieLikwidacji")
  private String otwarcieLikwidacji = null;

  @JsonProperty("sposobReprezentacjiPodmiotuPrzezLikwidatorow")
  private String sposobReprezentacjiPodmiotuPrzezLikwidatorow = null;

  @JsonProperty("likwidatorzy")
  private List<Osoba> likwidatorzy = null;

  public Likwidacja otwarcieLikwidacji(String otwarcieLikwidacji) {
    this.otwarcieLikwidacji = otwarcieLikwidacji;
    return this;
  }

   /**
   * Get otwarcieLikwidacji
   * @return otwarcieLikwidacji
  **/
  @Schema(description = "")
  public String getOtwarcieLikwidacji() {
    return otwarcieLikwidacji;
  }

  public void setOtwarcieLikwidacji(String otwarcieLikwidacji) {
    this.otwarcieLikwidacji = otwarcieLikwidacji;
  }

  public Likwidacja sposobReprezentacjiPodmiotuPrzezLikwidatorow(String sposobReprezentacjiPodmiotuPrzezLikwidatorow) {
    this.sposobReprezentacjiPodmiotuPrzezLikwidatorow = sposobReprezentacjiPodmiotuPrzezLikwidatorow;
    return this;
  }

   /**
   * Get sposobReprezentacjiPodmiotuPrzezLikwidatorow
   * @return sposobReprezentacjiPodmiotuPrzezLikwidatorow
  **/
  @Schema(description = "")
  public String getSposobReprezentacjiPodmiotuPrzezLikwidatorow() {
    return sposobReprezentacjiPodmiotuPrzezLikwidatorow;
  }

  public void setSposobReprezentacjiPodmiotuPrzezLikwidatorow(String sposobReprezentacjiPodmiotuPrzezLikwidatorow) {
    this.sposobReprezentacjiPodmiotuPrzezLikwidatorow = sposobReprezentacjiPodmiotuPrzezLikwidatorow;
  }

  public Likwidacja likwidatorzy(List<Osoba> likwidatorzy) {
    this.likwidatorzy = likwidatorzy;
    return this;
  }

  public Likwidacja addLikwidatorzyItem(Osoba likwidatorzyItem) {
    if (this.likwidatorzy == null) {
      this.likwidatorzy = new ArrayList<Osoba>();
    }
    this.likwidatorzy.add(likwidatorzyItem);
    return this;
  }

   /**
   * Get likwidatorzy
   * @return likwidatorzy
  **/
  @Schema(description = "")
  public List<Osoba> getLikwidatorzy() {
    return likwidatorzy;
  }

  public void setLikwidatorzy(List<Osoba> likwidatorzy) {
    this.likwidatorzy = likwidatorzy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Likwidacja likwidacja = (Likwidacja) o;
    return Objects.equals(this.otwarcieLikwidacji, likwidacja.otwarcieLikwidacji) &&
        Objects.equals(this.sposobReprezentacjiPodmiotuPrzezLikwidatorow, likwidacja.sposobReprezentacjiPodmiotuPrzezLikwidatorow) &&
        Objects.equals(this.likwidatorzy, likwidacja.likwidatorzy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(otwarcieLikwidacji, sposobReprezentacjiPodmiotuPrzezLikwidatorow, likwidatorzy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Likwidacja {\n");
    
    sb.append("    otwarcieLikwidacji: ").append(toIndentedString(otwarcieLikwidacji)).append("\n");
    sb.append("    sposobReprezentacjiPodmiotuPrzezLikwidatorow: ").append(toIndentedString(sposobReprezentacjiPodmiotuPrzezLikwidatorow)).append("\n");
    sb.append("    likwidatorzy: ").append(toIndentedString(likwidatorzy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
