/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * NazwiskoOsoby
 */


public class NazwiskoOsoby {
  @JsonProperty("nazwiskoICzlon")
  private String nazwiskoICzlon = null;

  @JsonProperty("nazwiskoIICzlon")
  private String nazwiskoIICzlon = null;

  public NazwiskoOsoby nazwiskoICzlon(String nazwiskoICzlon) {
    this.nazwiskoICzlon = nazwiskoICzlon;
    return this;
  }

   /**
   * Get nazwiskoICzlon
   * @return nazwiskoICzlon
  **/
  @Schema(description = "")
  public String getNazwiskoICzlon() {
    return nazwiskoICzlon;
  }

  public void setNazwiskoICzlon(String nazwiskoICzlon) {
    this.nazwiskoICzlon = nazwiskoICzlon;
  }

  public NazwiskoOsoby nazwiskoIICzlon(String nazwiskoIICzlon) {
    this.nazwiskoIICzlon = nazwiskoIICzlon;
    return this;
  }

   /**
   * Get nazwiskoIICzlon
   * @return nazwiskoIICzlon
  **/
  @Schema(description = "")
  public String getNazwiskoIICzlon() {
    return nazwiskoIICzlon;
  }

  public void setNazwiskoIICzlon(String nazwiskoIICzlon) {
    this.nazwiskoIICzlon = nazwiskoIICzlon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NazwiskoOsoby nazwiskoOsoby = (NazwiskoOsoby) o;
    return Objects.equals(this.nazwiskoICzlon, nazwiskoOsoby.nazwiskoICzlon) &&
        Objects.equals(this.nazwiskoIICzlon, nazwiskoOsoby.nazwiskoIICzlon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwiskoICzlon, nazwiskoIICzlon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NazwiskoOsoby {\n");
    
    sb.append("    nazwiskoICzlon: ").append(toIndentedString(nazwiskoICzlon)).append("\n");
    sb.append("    nazwiskoIICzlon: ").append(toIndentedString(nazwiskoIICzlon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
