/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.NowySrodekTransportu;
/**
 * NoweSrodkiTransportu
 */


public class NoweSrodkiTransportu {
  @JsonProperty("P_22")
  private Integer p22 = null;

  @JsonProperty("P_42_5")
  private Integer p425 = null;

  @JsonProperty("NowySrodekTransportu")
  private List<NowySrodekTransportu> nowySrodekTransportu = null;

  @JsonProperty("P_22N")
  private Integer p22N = null;

  public NoweSrodkiTransportu p22(Integer p22) {
    this.p22 = p22;
    return this;
  }

   /**
   * Get p22
   * @return p22
  **/
  @Schema(description = "")
  public Integer getP22() {
    return p22;
  }

  public void setP22(Integer p22) {
    this.p22 = p22;
  }

  public NoweSrodkiTransportu p425(Integer p425) {
    this.p425 = p425;
    return this;
  }

   /**
   * Get p425
   * @return p425
  **/
  @Schema(description = "")
  public Integer getP425() {
    return p425;
  }

  public void setP425(Integer p425) {
    this.p425 = p425;
  }

  public NoweSrodkiTransportu nowySrodekTransportu(List<NowySrodekTransportu> nowySrodekTransportu) {
    this.nowySrodekTransportu = nowySrodekTransportu;
    return this;
  }

  public NoweSrodkiTransportu addNowySrodekTransportuItem(NowySrodekTransportu nowySrodekTransportuItem) {
    if (this.nowySrodekTransportu == null) {
      this.nowySrodekTransportu = new ArrayList<>();
    }
    this.nowySrodekTransportu.add(nowySrodekTransportuItem);
    return this;
  }

   /**
   * Get nowySrodekTransportu
   * @return nowySrodekTransportu
  **/
  @Schema(description = "")
  public List<NowySrodekTransportu> getNowySrodekTransportu() {
    return nowySrodekTransportu;
  }

  public void setNowySrodekTransportu(List<NowySrodekTransportu> nowySrodekTransportu) {
    this.nowySrodekTransportu = nowySrodekTransportu;
  }

  public NoweSrodkiTransportu p22N(Integer p22N) {
    this.p22N = p22N;
    return this;
  }

   /**
   * Get p22N
   * @return p22N
  **/
  @Schema(description = "")
  public Integer getP22N() {
    return p22N;
  }

  public void setP22N(Integer p22N) {
    this.p22N = p22N;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NoweSrodkiTransportu noweSrodkiTransportu = (NoweSrodkiTransportu) o;
    return Objects.equals(this.p22, noweSrodkiTransportu.p22) &&
        Objects.equals(this.p425, noweSrodkiTransportu.p425) &&
        Objects.equals(this.nowySrodekTransportu, noweSrodkiTransportu.nowySrodekTransportu) &&
        Objects.equals(this.p22N, noweSrodkiTransportu.p22N);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p22, p425, nowySrodekTransportu, p22N);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NoweSrodkiTransportu {\n");
    
    sb.append("    p22: ").append(toIndentedString(p22)).append("\n");
    sb.append("    p425: ").append(toIndentedString(p425)).append("\n");
    sb.append("    nowySrodekTransportu: ").append(toIndentedString(nowySrodekTransportu)).append("\n");
    sb.append("    p22N: ").append(toIndentedString(p22N)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
