/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.Dane;
import pl.nip24.client.model.NaglowekA;
import pl.nip24.client.model.RodzajOdpisu;
/**
 * Odpis
 */


public class Odpis {
  @JsonProperty("rodzaj")
  private RodzajOdpisu rodzaj = null;

  @JsonProperty("naglowekA")
  private NaglowekA naglowekA = null;

  @JsonProperty("dane")
  private Dane dane = null;

  public Odpis rodzaj(RodzajOdpisu rodzaj) {
    this.rodzaj = rodzaj;
    return this;
  }

   /**
   * Get rodzaj
   * @return rodzaj
  **/
  @Schema(required = true, description = "")
  public RodzajOdpisu getRodzaj() {
    return rodzaj;
  }

  public void setRodzaj(RodzajOdpisu rodzaj) {
    this.rodzaj = rodzaj;
  }

  public Odpis naglowekA(NaglowekA naglowekA) {
    this.naglowekA = naglowekA;
    return this;
  }

   /**
   * Get naglowekA
   * @return naglowekA
  **/
  @Schema(description = "")
  public NaglowekA getNaglowekA() {
    return naglowekA;
  }

  public void setNaglowekA(NaglowekA naglowekA) {
    this.naglowekA = naglowekA;
  }

  public Odpis dane(Dane dane) {
    this.dane = dane;
    return this;
  }

   /**
   * Get dane
   * @return dane
  **/
  @Schema(required = true, description = "")
  public Dane getDane() {
    return dane;
  }

  public void setDane(Dane dane) {
    this.dane = dane;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Odpis odpis = (Odpis) o;
    return Objects.equals(this.rodzaj, odpis.rodzaj) &&
        Objects.equals(this.naglowekA, odpis.naglowekA) &&
        Objects.equals(this.dane, odpis.dane);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rodzaj, naglowekA, dane);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Odpis {\n");
    
    sb.append("    rodzaj: ").append(toIndentedString(rodzaj)).append("\n");
    sb.append("    naglowekA: ").append(toIndentedString(naglowekA)).append("\n");
    sb.append("    dane: ").append(toIndentedString(dane)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
