/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
/**
 * Okres, którego dotyczy faktura w przypadkach, o których mowa w art. 19a ust. 3 zdanie pierwsze i ust. 4 oraz ust. 5 pkt 4 ustawy
 */
@Schema(description = "Okres, którego dotyczy faktura w przypadkach, o których mowa w art. 19a ust. 3 zdanie pierwsze i ust. 4 oraz ust. 5 pkt 4 ustawy")

public class OkresFa {
  @JsonProperty("P_6_Od")
  private LocalDate p6Od = null;

  @JsonProperty("P_6_Do")
  private LocalDate p6Do = null;

  public OkresFa p6Od(LocalDate p6Od) {
    this.p6Od = p6Od;
    return this;
  }

   /**
   * Get p6Od
   * @return p6Od
  **/
  @Schema(required = true, description = "")
  public LocalDate getP6Od() {
    return p6Od;
  }

  public void setP6Od(LocalDate p6Od) {
    this.p6Od = p6Od;
  }

  public OkresFa p6Do(LocalDate p6Do) {
    this.p6Do = p6Do;
    return this;
  }

   /**
   * Get p6Do
   * @return p6Do
  **/
  @Schema(required = true, description = "")
  public LocalDate getP6Do() {
    return p6Do;
  }

  public void setP6Do(LocalDate p6Do) {
    this.p6Do = p6Do;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OkresFa okresFa = (OkresFa) o;
    return Objects.equals(this.p6Od, okresFa.p6Od) &&
        Objects.equals(this.p6Do, okresFa.p6Do);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p6Od, p6Do);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OkresFa {\n");
    
    sb.append("    p6Od: ").append(toIndentedString(p6Od)).append("\n");
    sb.append("    p6Do: ").append(toIndentedString(p6Do)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
