/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.DaneKontaktowe;
import pl.nip24.client.model.TAdres;
import pl.nip24.client.model.TPodmiot2;
/**
 * Dane nabywcy
 */
@Schema(description = "Dane nabywcy")

public class Podmiot2 {
  @JsonProperty("NrEORI")
  private String nrEORI = null;

  @JsonProperty("DaneIdentyfikacyjne")
  private TPodmiot2 daneIdentyfikacyjne = null;

  @JsonProperty("Adres")
  private TAdres adres = null;

  @JsonProperty("AdresKoresp")
  private TAdres adresKoresp = null;

  @JsonProperty("DaneKontaktowe")
  private List<DaneKontaktowe> daneKontaktowe = null;

  @JsonProperty("NrKlienta")
  private String nrKlienta = null;

  @JsonProperty("IDNabywcy")
  private String idNabywcy = null;

  public Podmiot2 nrEORI(String nrEORI) {
    this.nrEORI = nrEORI;
    return this;
  }

   /**
   * Get nrEORI
   * @return nrEORI
  **/
  @Schema(description = "")
  public String getNrEORI() {
    return nrEORI;
  }

  public void setNrEORI(String nrEORI) {
    this.nrEORI = nrEORI;
  }

  public Podmiot2 daneIdentyfikacyjne(TPodmiot2 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
    return this;
  }

   /**
   * Get daneIdentyfikacyjne
   * @return daneIdentyfikacyjne
  **/
  @Schema(required = true, description = "")
  public TPodmiot2 getDaneIdentyfikacyjne() {
    return daneIdentyfikacyjne;
  }

  public void setDaneIdentyfikacyjne(TPodmiot2 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
  }

  public Podmiot2 adres(TAdres adres) {
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @Schema(description = "")
  public TAdres getAdres() {
    return adres;
  }

  public void setAdres(TAdres adres) {
    this.adres = adres;
  }

  public Podmiot2 adresKoresp(TAdres adresKoresp) {
    this.adresKoresp = adresKoresp;
    return this;
  }

   /**
   * Get adresKoresp
   * @return adresKoresp
  **/
  @Schema(description = "")
  public TAdres getAdresKoresp() {
    return adresKoresp;
  }

  public void setAdresKoresp(TAdres adresKoresp) {
    this.adresKoresp = adresKoresp;
  }

  public Podmiot2 daneKontaktowe(List<DaneKontaktowe> daneKontaktowe) {
    this.daneKontaktowe = daneKontaktowe;
    return this;
  }

  public Podmiot2 addDaneKontaktoweItem(DaneKontaktowe daneKontaktoweItem) {
    if (this.daneKontaktowe == null) {
      this.daneKontaktowe = new ArrayList<>();
    }
    this.daneKontaktowe.add(daneKontaktoweItem);
    return this;
  }

   /**
   * Get daneKontaktowe
   * @return daneKontaktowe
  **/
  @Schema(description = "")
  public List<DaneKontaktowe> getDaneKontaktowe() {
    return daneKontaktowe;
  }

  public void setDaneKontaktowe(List<DaneKontaktowe> daneKontaktowe) {
    this.daneKontaktowe = daneKontaktowe;
  }

  public Podmiot2 nrKlienta(String nrKlienta) {
    this.nrKlienta = nrKlienta;
    return this;
  }

   /**
   * Get nrKlienta
   * @return nrKlienta
  **/
  @Schema(description = "")
  public String getNrKlienta() {
    return nrKlienta;
  }

  public void setNrKlienta(String nrKlienta) {
    this.nrKlienta = nrKlienta;
  }

  public Podmiot2 idNabywcy(String idNabywcy) {
    this.idNabywcy = idNabywcy;
    return this;
  }

   /**
   * Get idNabywcy
   * @return idNabywcy
  **/
  @Schema(description = "")
  public String getIdNabywcy() {
    return idNabywcy;
  }

  public void setIdNabywcy(String idNabywcy) {
    this.idNabywcy = idNabywcy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Podmiot2 podmiot2 = (Podmiot2) o;
    return Objects.equals(this.nrEORI, podmiot2.nrEORI) &&
        Objects.equals(this.daneIdentyfikacyjne, podmiot2.daneIdentyfikacyjne) &&
        Objects.equals(this.adres, podmiot2.adres) &&
        Objects.equals(this.adresKoresp, podmiot2.adresKoresp) &&
        Objects.equals(this.daneKontaktowe, podmiot2.daneKontaktowe) &&
        Objects.equals(this.nrKlienta, podmiot2.nrKlienta) &&
        Objects.equals(this.idNabywcy, podmiot2.idNabywcy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrEORI, daneIdentyfikacyjne, adres, adresKoresp, daneKontaktowe, nrKlienta, idNabywcy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Podmiot2 {\n");
    
    sb.append("    nrEORI: ").append(toIndentedString(nrEORI)).append("\n");
    sb.append("    daneIdentyfikacyjne: ").append(toIndentedString(daneIdentyfikacyjne)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("    adresKoresp: ").append(toIndentedString(adresKoresp)).append("\n");
    sb.append("    daneKontaktowe: ").append(toIndentedString(daneKontaktowe)).append("\n");
    sb.append("    nrKlienta: ").append(toIndentedString(nrKlienta)).append("\n");
    sb.append("    idNabywcy: ").append(toIndentedString(idNabywcy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
