/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.DaneKontaktowePU;
import pl.nip24.client.model.TAdres;
import pl.nip24.client.model.TPodmiot1;
/**
 * Dane podmiotu upoważnionego, związanego z fakturą
 */
@Schema(description = "Dane podmiotu upoważnionego, związanego z fakturą")

public class PodmiotUpowazniony {
  @JsonProperty("NrEORI")
  private String nrEORI = null;

  @JsonProperty("DaneIdentyfikacyjne")
  private TPodmiot1 daneIdentyfikacyjne = null;

  @JsonProperty("Adres")
  private TAdres adres = null;

  @JsonProperty("AdresKoresp")
  private TAdres adresKoresp = null;

  @JsonProperty("DaneKontaktowe")
  private List<DaneKontaktowePU> daneKontaktowe = null;

  @JsonProperty("RolaPU")
  private Integer rolaPU = null;

  public PodmiotUpowazniony nrEORI(String nrEORI) {
    this.nrEORI = nrEORI;
    return this;
  }

   /**
   * Get nrEORI
   * @return nrEORI
  **/
  @Schema(description = "")
  public String getNrEORI() {
    return nrEORI;
  }

  public void setNrEORI(String nrEORI) {
    this.nrEORI = nrEORI;
  }

  public PodmiotUpowazniony daneIdentyfikacyjne(TPodmiot1 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
    return this;
  }

   /**
   * Get daneIdentyfikacyjne
   * @return daneIdentyfikacyjne
  **/
  @Schema(required = true, description = "")
  public TPodmiot1 getDaneIdentyfikacyjne() {
    return daneIdentyfikacyjne;
  }

  public void setDaneIdentyfikacyjne(TPodmiot1 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
  }

  public PodmiotUpowazniony adres(TAdres adres) {
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @Schema(required = true, description = "")
  public TAdres getAdres() {
    return adres;
  }

  public void setAdres(TAdres adres) {
    this.adres = adres;
  }

  public PodmiotUpowazniony adresKoresp(TAdres adresKoresp) {
    this.adresKoresp = adresKoresp;
    return this;
  }

   /**
   * Get adresKoresp
   * @return adresKoresp
  **/
  @Schema(description = "")
  public TAdres getAdresKoresp() {
    return adresKoresp;
  }

  public void setAdresKoresp(TAdres adresKoresp) {
    this.adresKoresp = adresKoresp;
  }

  public PodmiotUpowazniony daneKontaktowe(List<DaneKontaktowePU> daneKontaktowe) {
    this.daneKontaktowe = daneKontaktowe;
    return this;
  }

  public PodmiotUpowazniony addDaneKontaktoweItem(DaneKontaktowePU daneKontaktoweItem) {
    if (this.daneKontaktowe == null) {
      this.daneKontaktowe = new ArrayList<>();
    }
    this.daneKontaktowe.add(daneKontaktoweItem);
    return this;
  }

   /**
   * Get daneKontaktowe
   * @return daneKontaktowe
  **/
  @Schema(description = "")
  public List<DaneKontaktowePU> getDaneKontaktowe() {
    return daneKontaktowe;
  }

  public void setDaneKontaktowe(List<DaneKontaktowePU> daneKontaktowe) {
    this.daneKontaktowe = daneKontaktowe;
  }

  public PodmiotUpowazniony rolaPU(Integer rolaPU) {
    this.rolaPU = rolaPU;
    return this;
  }

   /**
   * Get rolaPU
   * @return rolaPU
  **/
  @Schema(required = true, description = "")
  public Integer getRolaPU() {
    return rolaPU;
  }

  public void setRolaPU(Integer rolaPU) {
    this.rolaPU = rolaPU;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PodmiotUpowazniony podmiotUpowazniony = (PodmiotUpowazniony) o;
    return Objects.equals(this.nrEORI, podmiotUpowazniony.nrEORI) &&
        Objects.equals(this.daneIdentyfikacyjne, podmiotUpowazniony.daneIdentyfikacyjne) &&
        Objects.equals(this.adres, podmiotUpowazniony.adres) &&
        Objects.equals(this.adresKoresp, podmiotUpowazniony.adresKoresp) &&
        Objects.equals(this.daneKontaktowe, podmiotUpowazniony.daneKontaktowe) &&
        Objects.equals(this.rolaPU, podmiotUpowazniony.rolaPU);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrEORI, daneIdentyfikacyjne, adres, adresKoresp, daneKontaktowe, rolaPU);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PodmiotUpowazniony {\n");
    
    sb.append("    nrEORI: ").append(toIndentedString(nrEORI)).append("\n");
    sb.append("    daneIdentyfikacyjne: ").append(toIndentedString(daneIdentyfikacyjne)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("    adresKoresp: ").append(toIndentedString(adresKoresp)).append("\n");
    sb.append("    daneKontaktowe: ").append(toIndentedString(daneKontaktowe)).append("\n");
    sb.append("    rolaPU: ").append(toIndentedString(rolaPU)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
