/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.DaneKontaktowe;
import pl.nip24.client.model.TAdres;
import pl.nip24.client.model.TKodyKrajowUE;
import pl.nip24.client.model.TPodmiot1;
/**
 * Dane podatnika. Imię i nazwisko lub nazwa sprzedawcy towarów lub usług
 */
@Schema(description = "Dane podatnika. Imię i nazwisko lub nazwa sprzedawcy towarów lub usług")

public class Podmiot1 {
  @JsonProperty("PrefiksPodatnika")
  private TKodyKrajowUE prefiksPodatnika = null;

  @JsonProperty("NrEORI")
  private String nrEORI = null;

  @JsonProperty("DaneIdentyfikacyjne")
  private TPodmiot1 daneIdentyfikacyjne = null;

  @JsonProperty("Adres")
  private TAdres adres = null;

  @JsonProperty("AdresKoresp")
  private TAdres adresKoresp = null;

  @JsonProperty("DaneKontaktowe")
  private List<DaneKontaktowe> daneKontaktowe = null;

  @JsonProperty("StatusInfoPodatnika")
  private Integer statusInfoPodatnika = null;

  public Podmiot1 prefiksPodatnika(TKodyKrajowUE prefiksPodatnika) {
    this.prefiksPodatnika = prefiksPodatnika;
    return this;
  }

   /**
   * Get prefiksPodatnika
   * @return prefiksPodatnika
  **/
  @Schema(description = "")
  public TKodyKrajowUE getPrefiksPodatnika() {
    return prefiksPodatnika;
  }

  public void setPrefiksPodatnika(TKodyKrajowUE prefiksPodatnika) {
    this.prefiksPodatnika = prefiksPodatnika;
  }

  public Podmiot1 nrEORI(String nrEORI) {
    this.nrEORI = nrEORI;
    return this;
  }

   /**
   * Get nrEORI
   * @return nrEORI
  **/
  @Schema(description = "")
  public String getNrEORI() {
    return nrEORI;
  }

  public void setNrEORI(String nrEORI) {
    this.nrEORI = nrEORI;
  }

  public Podmiot1 daneIdentyfikacyjne(TPodmiot1 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
    return this;
  }

   /**
   * Get daneIdentyfikacyjne
   * @return daneIdentyfikacyjne
  **/
  @Schema(required = true, description = "")
  public TPodmiot1 getDaneIdentyfikacyjne() {
    return daneIdentyfikacyjne;
  }

  public void setDaneIdentyfikacyjne(TPodmiot1 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
  }

  public Podmiot1 adres(TAdres adres) {
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @Schema(required = true, description = "")
  public TAdres getAdres() {
    return adres;
  }

  public void setAdres(TAdres adres) {
    this.adres = adres;
  }

  public Podmiot1 adresKoresp(TAdres adresKoresp) {
    this.adresKoresp = adresKoresp;
    return this;
  }

   /**
   * Get adresKoresp
   * @return adresKoresp
  **/
  @Schema(description = "")
  public TAdres getAdresKoresp() {
    return adresKoresp;
  }

  public void setAdresKoresp(TAdres adresKoresp) {
    this.adresKoresp = adresKoresp;
  }

  public Podmiot1 daneKontaktowe(List<DaneKontaktowe> daneKontaktowe) {
    this.daneKontaktowe = daneKontaktowe;
    return this;
  }

  public Podmiot1 addDaneKontaktoweItem(DaneKontaktowe daneKontaktoweItem) {
    if (this.daneKontaktowe == null) {
      this.daneKontaktowe = new ArrayList<>();
    }
    this.daneKontaktowe.add(daneKontaktoweItem);
    return this;
  }

   /**
   * Get daneKontaktowe
   * @return daneKontaktowe
  **/
  @Schema(description = "")
  public List<DaneKontaktowe> getDaneKontaktowe() {
    return daneKontaktowe;
  }

  public void setDaneKontaktowe(List<DaneKontaktowe> daneKontaktowe) {
    this.daneKontaktowe = daneKontaktowe;
  }

  public Podmiot1 statusInfoPodatnika(Integer statusInfoPodatnika) {
    this.statusInfoPodatnika = statusInfoPodatnika;
    return this;
  }

   /**
   * Get statusInfoPodatnika
   * @return statusInfoPodatnika
  **/
  @Schema(description = "")
  public Integer getStatusInfoPodatnika() {
    return statusInfoPodatnika;
  }

  public void setStatusInfoPodatnika(Integer statusInfoPodatnika) {
    this.statusInfoPodatnika = statusInfoPodatnika;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Podmiot1 podmiot1 = (Podmiot1) o;
    return Objects.equals(this.prefiksPodatnika, podmiot1.prefiksPodatnika) &&
        Objects.equals(this.nrEORI, podmiot1.nrEORI) &&
        Objects.equals(this.daneIdentyfikacyjne, podmiot1.daneIdentyfikacyjne) &&
        Objects.equals(this.adres, podmiot1.adres) &&
        Objects.equals(this.adresKoresp, podmiot1.adresKoresp) &&
        Objects.equals(this.daneKontaktowe, podmiot1.daneKontaktowe) &&
        Objects.equals(this.statusInfoPodatnika, podmiot1.statusInfoPodatnika);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefiksPodatnika, nrEORI, daneIdentyfikacyjne, adres, adresKoresp, daneKontaktowe, statusInfoPodatnika);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Podmiot1 {\n");
    
    sb.append("    prefiksPodatnika: ").append(toIndentedString(prefiksPodatnika)).append("\n");
    sb.append("    nrEORI: ").append(toIndentedString(nrEORI)).append("\n");
    sb.append("    daneIdentyfikacyjne: ").append(toIndentedString(daneIdentyfikacyjne)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("    adresKoresp: ").append(toIndentedString(adresKoresp)).append("\n");
    sb.append("    daneKontaktowe: ").append(toIndentedString(daneKontaktowe)).append("\n");
    sb.append("    statusInfoPodatnika: ").append(toIndentedString(statusInfoPodatnika)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
