/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.TAdres;
import pl.nip24.client.model.TKodyKrajowUE;
import pl.nip24.client.model.TPodmiot1;
/**
 * W przypadku korekty danych sprzedawcy należy podać pełne dane sprzedawcy występujące na fakturze korygowanej. Pole nie dotyczy przypadku korekty błędnego NIP występującego na fakturze pierwotnej - wówczas wymagana jest korekta faktury do wartości zerowych
 */
@Schema(description = "W przypadku korekty danych sprzedawcy należy podać pełne dane sprzedawcy występujące na fakturze korygowanej. Pole nie dotyczy przypadku korekty błędnego NIP występującego na fakturze pierwotnej - wówczas wymagana jest korekta faktury do wartości zerowych")

public class Podmiot1K {
  @JsonProperty("PrefiksPodatnika")
  private TKodyKrajowUE prefiksPodatnika = null;

  @JsonProperty("DaneIdentyfikacyjne")
  private TPodmiot1 daneIdentyfikacyjne = null;

  @JsonProperty("Adres")
  private TAdres adres = null;

  public Podmiot1K prefiksPodatnika(TKodyKrajowUE prefiksPodatnika) {
    this.prefiksPodatnika = prefiksPodatnika;
    return this;
  }

   /**
   * Get prefiksPodatnika
   * @return prefiksPodatnika
  **/
  @Schema(description = "")
  public TKodyKrajowUE getPrefiksPodatnika() {
    return prefiksPodatnika;
  }

  public void setPrefiksPodatnika(TKodyKrajowUE prefiksPodatnika) {
    this.prefiksPodatnika = prefiksPodatnika;
  }

  public Podmiot1K daneIdentyfikacyjne(TPodmiot1 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
    return this;
  }

   /**
   * Get daneIdentyfikacyjne
   * @return daneIdentyfikacyjne
  **/
  @Schema(required = true, description = "")
  public TPodmiot1 getDaneIdentyfikacyjne() {
    return daneIdentyfikacyjne;
  }

  public void setDaneIdentyfikacyjne(TPodmiot1 daneIdentyfikacyjne) {
    this.daneIdentyfikacyjne = daneIdentyfikacyjne;
  }

  public Podmiot1K adres(TAdres adres) {
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @Schema(required = true, description = "")
  public TAdres getAdres() {
    return adres;
  }

  public void setAdres(TAdres adres) {
    this.adres = adres;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Podmiot1K podmiot1K = (Podmiot1K) o;
    return Objects.equals(this.prefiksPodatnika, podmiot1K.prefiksPodatnika) &&
        Objects.equals(this.daneIdentyfikacyjne, podmiot1K.daneIdentyfikacyjne) &&
        Objects.equals(this.adres, podmiot1K.adres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefiksPodatnika, daneIdentyfikacyjne, adres);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Podmiot1K {\n");
    
    sb.append("    prefiksPodatnika: ").append(toIndentedString(prefiksPodatnika)).append("\n");
    sb.append("    daneIdentyfikacyjne: ").append(toIndentedString(daneIdentyfikacyjne)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
