/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.IdentyfikatoryPodmiotu;
/**
 * Podmioty
 */


public class Podmioty {
  @JsonProperty("nazwa")
  private String nazwa = null;

  @JsonProperty("krajNazwaRejestruEwidencji")
  private String krajNazwaRejestruEwidencji = null;

  @JsonProperty("numerWRejestrzeAlboEwidencji")
  private String numerWRejestrzeAlboEwidencji = null;

  @JsonProperty("nazwaSaduOrganuProwadzacegoRejestrEwidencje")
  private String nazwaSaduOrganuProwadzacegoRejestrEwidencje = null;

  @JsonProperty("identyfikatory")
  private IdentyfikatoryPodmiotu identyfikatory = null;

  public Podmioty nazwa(String nazwa) {
    this.nazwa = nazwa;
    return this;
  }

   /**
   * Get nazwa
   * @return nazwa
  **/
  @Schema(description = "")
  public String getNazwa() {
    return nazwa;
  }

  public void setNazwa(String nazwa) {
    this.nazwa = nazwa;
  }

  public Podmioty krajNazwaRejestruEwidencji(String krajNazwaRejestruEwidencji) {
    this.krajNazwaRejestruEwidencji = krajNazwaRejestruEwidencji;
    return this;
  }

   /**
   * Get krajNazwaRejestruEwidencji
   * @return krajNazwaRejestruEwidencji
  **/
  @Schema(description = "")
  public String getKrajNazwaRejestruEwidencji() {
    return krajNazwaRejestruEwidencji;
  }

  public void setKrajNazwaRejestruEwidencji(String krajNazwaRejestruEwidencji) {
    this.krajNazwaRejestruEwidencji = krajNazwaRejestruEwidencji;
  }

  public Podmioty numerWRejestrzeAlboEwidencji(String numerWRejestrzeAlboEwidencji) {
    this.numerWRejestrzeAlboEwidencji = numerWRejestrzeAlboEwidencji;
    return this;
  }

   /**
   * Get numerWRejestrzeAlboEwidencji
   * @return numerWRejestrzeAlboEwidencji
  **/
  @Schema(description = "")
  public String getNumerWRejestrzeAlboEwidencji() {
    return numerWRejestrzeAlboEwidencji;
  }

  public void setNumerWRejestrzeAlboEwidencji(String numerWRejestrzeAlboEwidencji) {
    this.numerWRejestrzeAlboEwidencji = numerWRejestrzeAlboEwidencji;
  }

  public Podmioty nazwaSaduOrganuProwadzacegoRejestrEwidencje(String nazwaSaduOrganuProwadzacegoRejestrEwidencje) {
    this.nazwaSaduOrganuProwadzacegoRejestrEwidencje = nazwaSaduOrganuProwadzacegoRejestrEwidencje;
    return this;
  }

   /**
   * Get nazwaSaduOrganuProwadzacegoRejestrEwidencje
   * @return nazwaSaduOrganuProwadzacegoRejestrEwidencje
  **/
  @Schema(description = "")
  public String getNazwaSaduOrganuProwadzacegoRejestrEwidencje() {
    return nazwaSaduOrganuProwadzacegoRejestrEwidencje;
  }

  public void setNazwaSaduOrganuProwadzacegoRejestrEwidencje(String nazwaSaduOrganuProwadzacegoRejestrEwidencje) {
    this.nazwaSaduOrganuProwadzacegoRejestrEwidencje = nazwaSaduOrganuProwadzacegoRejestrEwidencje;
  }

  public Podmioty identyfikatory(IdentyfikatoryPodmiotu identyfikatory) {
    this.identyfikatory = identyfikatory;
    return this;
  }

   /**
   * Get identyfikatory
   * @return identyfikatory
  **/
  @Schema(description = "")
  public IdentyfikatoryPodmiotu getIdentyfikatory() {
    return identyfikatory;
  }

  public void setIdentyfikatory(IdentyfikatoryPodmiotu identyfikatory) {
    this.identyfikatory = identyfikatory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Podmioty podmioty = (Podmioty) o;
    return Objects.equals(this.nazwa, podmioty.nazwa) &&
        Objects.equals(this.krajNazwaRejestruEwidencji, podmioty.krajNazwaRejestruEwidencji) &&
        Objects.equals(this.numerWRejestrzeAlboEwidencji, podmioty.numerWRejestrzeAlboEwidencji) &&
        Objects.equals(this.nazwaSaduOrganuProwadzacegoRejestrEwidencje, podmioty.nazwaSaduOrganuProwadzacegoRejestrEwidencje) &&
        Objects.equals(this.identyfikatory, podmioty.identyfikatory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwa, krajNazwaRejestruEwidencji, numerWRejestrzeAlboEwidencji, nazwaSaduOrganuProwadzacegoRejestrEwidencje, identyfikatory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Podmioty {\n");
    
    sb.append("    nazwa: ").append(toIndentedString(nazwa)).append("\n");
    sb.append("    krajNazwaRejestruEwidencji: ").append(toIndentedString(krajNazwaRejestruEwidencji)).append("\n");
    sb.append("    numerWRejestrzeAlboEwidencji: ").append(toIndentedString(numerWRejestrzeAlboEwidencji)).append("\n");
    sb.append("    nazwaSaduOrganuProwadzacegoRejestrEwidencje: ").append(toIndentedString(nazwaSaduOrganuProwadzacegoRejestrEwidencje)).append("\n");
    sb.append("    identyfikatory: ").append(toIndentedString(identyfikatory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
