/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Podmioty;
/**
 * PolaczeniePodzialPrzeksztalcenie
 */


public class PolaczeniePodzialPrzeksztalcenie {
  @JsonProperty("okreslenieOkolicznosci")
  private String okreslenieOkolicznosci = null;

  @JsonProperty("opisPolaczeniaPodzialuPrzeksztalcenia")
  private String opisPolaczeniaPodzialuPrzeksztalcenia = null;

  @JsonProperty("podmiotyPrzejmowane")
  private List<Podmioty> podmiotyPrzejmowane = null;

  public PolaczeniePodzialPrzeksztalcenie okreslenieOkolicznosci(String okreslenieOkolicznosci) {
    this.okreslenieOkolicznosci = okreslenieOkolicznosci;
    return this;
  }

   /**
   * Get okreslenieOkolicznosci
   * @return okreslenieOkolicznosci
  **/
  @Schema(description = "")
  public String getOkreslenieOkolicznosci() {
    return okreslenieOkolicznosci;
  }

  public void setOkreslenieOkolicznosci(String okreslenieOkolicznosci) {
    this.okreslenieOkolicznosci = okreslenieOkolicznosci;
  }

  public PolaczeniePodzialPrzeksztalcenie opisPolaczeniaPodzialuPrzeksztalcenia(String opisPolaczeniaPodzialuPrzeksztalcenia) {
    this.opisPolaczeniaPodzialuPrzeksztalcenia = opisPolaczeniaPodzialuPrzeksztalcenia;
    return this;
  }

   /**
   * Get opisPolaczeniaPodzialuPrzeksztalcenia
   * @return opisPolaczeniaPodzialuPrzeksztalcenia
  **/
  @Schema(description = "")
  public String getOpisPolaczeniaPodzialuPrzeksztalcenia() {
    return opisPolaczeniaPodzialuPrzeksztalcenia;
  }

  public void setOpisPolaczeniaPodzialuPrzeksztalcenia(String opisPolaczeniaPodzialuPrzeksztalcenia) {
    this.opisPolaczeniaPodzialuPrzeksztalcenia = opisPolaczeniaPodzialuPrzeksztalcenia;
  }

  public PolaczeniePodzialPrzeksztalcenie podmiotyPrzejmowane(List<Podmioty> podmiotyPrzejmowane) {
    this.podmiotyPrzejmowane = podmiotyPrzejmowane;
    return this;
  }

  public PolaczeniePodzialPrzeksztalcenie addPodmiotyPrzejmowaneItem(Podmioty podmiotyPrzejmowaneItem) {
    if (this.podmiotyPrzejmowane == null) {
      this.podmiotyPrzejmowane = new ArrayList<>();
    }
    this.podmiotyPrzejmowane.add(podmiotyPrzejmowaneItem);
    return this;
  }

   /**
   * Get podmiotyPrzejmowane
   * @return podmiotyPrzejmowane
  **/
  @Schema(description = "")
  public List<Podmioty> getPodmiotyPrzejmowane() {
    return podmiotyPrzejmowane;
  }

  public void setPodmiotyPrzejmowane(List<Podmioty> podmiotyPrzejmowane) {
    this.podmiotyPrzejmowane = podmiotyPrzejmowane;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolaczeniePodzialPrzeksztalcenie polaczeniePodzialPrzeksztalcenie = (PolaczeniePodzialPrzeksztalcenie) o;
    return Objects.equals(this.okreslenieOkolicznosci, polaczeniePodzialPrzeksztalcenie.okreslenieOkolicznosci) &&
        Objects.equals(this.opisPolaczeniaPodzialuPrzeksztalcenia, polaczeniePodzialPrzeksztalcenie.opisPolaczeniaPodzialuPrzeksztalcenia) &&
        Objects.equals(this.podmiotyPrzejmowane, polaczeniePodzialPrzeksztalcenie.podmiotyPrzejmowane);
  }

  @Override
  public int hashCode() {
    return Objects.hash(okreslenieOkolicznosci, opisPolaczeniaPodzialuPrzeksztalcenia, podmiotyPrzejmowane);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolaczeniePodzialPrzeksztalcenie {\n");
    
    sb.append("    okreslenieOkolicznosci: ").append(toIndentedString(okreslenieOkolicznosci)).append("\n");
    sb.append("    opisPolaczeniaPodzialuPrzeksztalcenia: ").append(toIndentedString(opisPolaczeniaPodzialuPrzeksztalcenia)).append("\n");
    sb.append("    podmiotyPrzejmowane: ").append(toIndentedString(podmiotyPrzejmowane)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
