/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PozostaleInformacje
 */


public class PozostaleInformacje {
  @JsonProperty("czasNaJakiUtworzonyZostalPodmiot")
  private String czasNaJakiUtworzonyZostalPodmiot = null;

  @JsonProperty("informacjaOLiczbieUdzialow")
  private String informacjaOLiczbieUdzialow = null;

  @JsonProperty("czyUmowaStatutPrzyznajeUprawnieniaOsobiste")
  private Boolean czyUmowaStatutPrzyznajeUprawnieniaOsobiste = null;

  @JsonProperty("czyObligatoriuszeMajaPrawoDoUdzialuWZysku")
  private Boolean czyObligatoriuszeMajaPrawoDoUdzialuWZysku = null;

  public PozostaleInformacje czasNaJakiUtworzonyZostalPodmiot(String czasNaJakiUtworzonyZostalPodmiot) {
    this.czasNaJakiUtworzonyZostalPodmiot = czasNaJakiUtworzonyZostalPodmiot;
    return this;
  }

   /**
   * Get czasNaJakiUtworzonyZostalPodmiot
   * @return czasNaJakiUtworzonyZostalPodmiot
  **/
  @Schema(description = "")
  public String getCzasNaJakiUtworzonyZostalPodmiot() {
    return czasNaJakiUtworzonyZostalPodmiot;
  }

  public void setCzasNaJakiUtworzonyZostalPodmiot(String czasNaJakiUtworzonyZostalPodmiot) {
    this.czasNaJakiUtworzonyZostalPodmiot = czasNaJakiUtworzonyZostalPodmiot;
  }

  public PozostaleInformacje informacjaOLiczbieUdzialow(String informacjaOLiczbieUdzialow) {
    this.informacjaOLiczbieUdzialow = informacjaOLiczbieUdzialow;
    return this;
  }

   /**
   * Get informacjaOLiczbieUdzialow
   * @return informacjaOLiczbieUdzialow
  **/
  @Schema(description = "")
  public String getInformacjaOLiczbieUdzialow() {
    return informacjaOLiczbieUdzialow;
  }

  public void setInformacjaOLiczbieUdzialow(String informacjaOLiczbieUdzialow) {
    this.informacjaOLiczbieUdzialow = informacjaOLiczbieUdzialow;
  }

  public PozostaleInformacje czyUmowaStatutPrzyznajeUprawnieniaOsobiste(Boolean czyUmowaStatutPrzyznajeUprawnieniaOsobiste) {
    this.czyUmowaStatutPrzyznajeUprawnieniaOsobiste = czyUmowaStatutPrzyznajeUprawnieniaOsobiste;
    return this;
  }

   /**
   * Get czyUmowaStatutPrzyznajeUprawnieniaOsobiste
   * @return czyUmowaStatutPrzyznajeUprawnieniaOsobiste
  **/
  @Schema(description = "")
  public Boolean isCzyUmowaStatutPrzyznajeUprawnieniaOsobiste() {
    return czyUmowaStatutPrzyznajeUprawnieniaOsobiste;
  }

  public void setCzyUmowaStatutPrzyznajeUprawnieniaOsobiste(Boolean czyUmowaStatutPrzyznajeUprawnieniaOsobiste) {
    this.czyUmowaStatutPrzyznajeUprawnieniaOsobiste = czyUmowaStatutPrzyznajeUprawnieniaOsobiste;
  }

  public PozostaleInformacje czyObligatoriuszeMajaPrawoDoUdzialuWZysku(Boolean czyObligatoriuszeMajaPrawoDoUdzialuWZysku) {
    this.czyObligatoriuszeMajaPrawoDoUdzialuWZysku = czyObligatoriuszeMajaPrawoDoUdzialuWZysku;
    return this;
  }

   /**
   * Get czyObligatoriuszeMajaPrawoDoUdzialuWZysku
   * @return czyObligatoriuszeMajaPrawoDoUdzialuWZysku
  **/
  @Schema(description = "")
  public Boolean isCzyObligatoriuszeMajaPrawoDoUdzialuWZysku() {
    return czyObligatoriuszeMajaPrawoDoUdzialuWZysku;
  }

  public void setCzyObligatoriuszeMajaPrawoDoUdzialuWZysku(Boolean czyObligatoriuszeMajaPrawoDoUdzialuWZysku) {
    this.czyObligatoriuszeMajaPrawoDoUdzialuWZysku = czyObligatoriuszeMajaPrawoDoUdzialuWZysku;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PozostaleInformacje pozostaleInformacje = (PozostaleInformacje) o;
    return Objects.equals(this.czasNaJakiUtworzonyZostalPodmiot, pozostaleInformacje.czasNaJakiUtworzonyZostalPodmiot) &&
        Objects.equals(this.informacjaOLiczbieUdzialow, pozostaleInformacje.informacjaOLiczbieUdzialow) &&
        Objects.equals(this.czyUmowaStatutPrzyznajeUprawnieniaOsobiste, pozostaleInformacje.czyUmowaStatutPrzyznajeUprawnieniaOsobiste) &&
        Objects.equals(this.czyObligatoriuszeMajaPrawoDoUdzialuWZysku, pozostaleInformacje.czyObligatoriuszeMajaPrawoDoUdzialuWZysku);
  }

  @Override
  public int hashCode() {
    return Objects.hash(czasNaJakiUtworzonyZostalPodmiot, informacjaOLiczbieUdzialow, czyUmowaStatutPrzyznajeUprawnieniaOsobiste, czyObligatoriuszeMajaPrawoDoUdzialuWZysku);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PozostaleInformacje {\n");
    
    sb.append("    czasNaJakiUtworzonyZostalPodmiot: ").append(toIndentedString(czasNaJakiUtworzonyZostalPodmiot)).append("\n");
    sb.append("    informacjaOLiczbieUdzialow: ").append(toIndentedString(informacjaOLiczbieUdzialow)).append("\n");
    sb.append("    czyUmowaStatutPrzyznajeUprawnieniaOsobiste: ").append(toIndentedString(czyUmowaStatutPrzyznajeUprawnieniaOsobiste)).append("\n");
    sb.append("    czyObligatoriuszeMajaPrawoDoUdzialuWZysku: ").append(toIndentedString(czyObligatoriuszeMajaPrawoDoUdzialuWZysku)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
