/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.Osoba;
/**
 * Prokurenci
 */


public class Prokurenci {
  @JsonProperty("rodzajProkury")
  private String rodzajProkury = null;

  @JsonProperty("osoba")
  private Osoba osoba = null;

  public Prokurenci rodzajProkury(String rodzajProkury) {
    this.rodzajProkury = rodzajProkury;
    return this;
  }

   /**
   * Get rodzajProkury
   * @return rodzajProkury
  **/
  @Schema(description = "")
  public String getRodzajProkury() {
    return rodzajProkury;
  }

  public void setRodzajProkury(String rodzajProkury) {
    this.rodzajProkury = rodzajProkury;
  }

  public Prokurenci osoba(Osoba osoba) {
    this.osoba = osoba;
    return this;
  }

   /**
   * Get osoba
   * @return osoba
  **/
  @Schema(description = "")
  public Osoba getOsoba() {
    return osoba;
  }

  public void setOsoba(Osoba osoba) {
    this.osoba = osoba;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Prokurenci prokurenci = (Prokurenci) o;
    return Objects.equals(this.rodzajProkury, prokurenci.rodzajProkury) &&
        Objects.equals(this.osoba, prokurenci.osoba);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rodzajProkury, osoba);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Prokurenci {\n");
    
    sb.append("    rodzajProkury: ").append(toIndentedString(rodzajProkury)).append("\n");
    sb.append("    osoba: ").append(toIndentedString(osoba)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
