/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Obciazenia;
import pl.nip24.client.model.Odliczenia;
/**
 * Dodatkowe rozliczenia na fakturze
 */
@Schema(description = "Dodatkowe rozliczenia na fakturze")

public class Rozliczenie {
  @JsonProperty("Obciazenia")
  private List<Obciazenia> obciazenia = null;

  @JsonProperty("SumaObciazen")
  private Double sumaObciazen = null;

  @JsonProperty("Odliczenia")
  private List<Odliczenia> odliczenia = null;

  @JsonProperty("SumaOdliczen")
  private Double sumaOdliczen = null;

  @JsonProperty("DoZaplaty")
  private Double doZaplaty = null;

  @JsonProperty("DoRozliczenia")
  private Double doRozliczenia = null;

  public Rozliczenie obciazenia(List<Obciazenia> obciazenia) {
    this.obciazenia = obciazenia;
    return this;
  }

  public Rozliczenie addObciazeniaItem(Obciazenia obciazeniaItem) {
    if (this.obciazenia == null) {
      this.obciazenia = new ArrayList<>();
    }
    this.obciazenia.add(obciazeniaItem);
    return this;
  }

   /**
   * Get obciazenia
   * @return obciazenia
  **/
  @Schema(description = "")
  public List<Obciazenia> getObciazenia() {
    return obciazenia;
  }

  public void setObciazenia(List<Obciazenia> obciazenia) {
    this.obciazenia = obciazenia;
  }

  public Rozliczenie sumaObciazen(Double sumaObciazen) {
    this.sumaObciazen = sumaObciazen;
    return this;
  }

   /**
   * Get sumaObciazen
   * @return sumaObciazen
  **/
  @Schema(description = "")
  public Double getSumaObciazen() {
    return sumaObciazen;
  }

  public void setSumaObciazen(Double sumaObciazen) {
    this.sumaObciazen = sumaObciazen;
  }

  public Rozliczenie odliczenia(List<Odliczenia> odliczenia) {
    this.odliczenia = odliczenia;
    return this;
  }

  public Rozliczenie addOdliczeniaItem(Odliczenia odliczeniaItem) {
    if (this.odliczenia == null) {
      this.odliczenia = new ArrayList<>();
    }
    this.odliczenia.add(odliczeniaItem);
    return this;
  }

   /**
   * Get odliczenia
   * @return odliczenia
  **/
  @Schema(description = "")
  public List<Odliczenia> getOdliczenia() {
    return odliczenia;
  }

  public void setOdliczenia(List<Odliczenia> odliczenia) {
    this.odliczenia = odliczenia;
  }

  public Rozliczenie sumaOdliczen(Double sumaOdliczen) {
    this.sumaOdliczen = sumaOdliczen;
    return this;
  }

   /**
   * Get sumaOdliczen
   * @return sumaOdliczen
  **/
  @Schema(description = "")
  public Double getSumaOdliczen() {
    return sumaOdliczen;
  }

  public void setSumaOdliczen(Double sumaOdliczen) {
    this.sumaOdliczen = sumaOdliczen;
  }

  public Rozliczenie doZaplaty(Double doZaplaty) {
    this.doZaplaty = doZaplaty;
    return this;
  }

   /**
   * Get doZaplaty
   * @return doZaplaty
  **/
  @Schema(description = "")
  public Double getDoZaplaty() {
    return doZaplaty;
  }

  public void setDoZaplaty(Double doZaplaty) {
    this.doZaplaty = doZaplaty;
  }

  public Rozliczenie doRozliczenia(Double doRozliczenia) {
    this.doRozliczenia = doRozliczenia;
    return this;
  }

   /**
   * Get doRozliczenia
   * @return doRozliczenia
  **/
  @Schema(description = "")
  public Double getDoRozliczenia() {
    return doRozliczenia;
  }

  public void setDoRozliczenia(Double doRozliczenia) {
    this.doRozliczenia = doRozliczenia;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rozliczenie rozliczenie = (Rozliczenie) o;
    return Objects.equals(this.obciazenia, rozliczenie.obciazenia) &&
        Objects.equals(this.sumaObciazen, rozliczenie.sumaObciazen) &&
        Objects.equals(this.odliczenia, rozliczenie.odliczenia) &&
        Objects.equals(this.sumaOdliczen, rozliczenie.sumaOdliczen) &&
        Objects.equals(this.doZaplaty, rozliczenie.doZaplaty) &&
        Objects.equals(this.doRozliczenia, rozliczenie.doRozliczenia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(obciazenia, sumaObciazen, odliczenia, sumaOdliczen, doZaplaty, doRozliczenia);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rozliczenie {\n");
    
    sb.append("    obciazenia: ").append(toIndentedString(obciazenia)).append("\n");
    sb.append("    sumaObciazen: ").append(toIndentedString(sumaObciazen)).append("\n");
    sb.append("    odliczenia: ").append(toIndentedString(odliczenia)).append("\n");
    sb.append("    sumaOdliczen: ").append(toIndentedString(sumaOdliczen)).append("\n");
    sb.append("    doZaplaty: ").append(toIndentedString(doZaplaty)).append("\n");
    sb.append("    doRozliczenia: ").append(toIndentedString(doRozliczenia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
