/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Siedziba
 */


public class Siedziba {
  @JsonProperty("kraj")
  private String kraj = null;

  @JsonProperty("wojewodztwo")
  private String wojewodztwo = null;

  @JsonProperty("powiat")
  private String powiat = null;

  @JsonProperty("gmina")
  private String gmina = null;

  @JsonProperty("miejscowosc")
  private String miejscowosc = null;

  public Siedziba kraj(String kraj) {
    this.kraj = kraj;
    return this;
  }

   /**
   * Get kraj
   * @return kraj
  **/
  @Schema(description = "")
  public String getKraj() {
    return kraj;
  }

  public void setKraj(String kraj) {
    this.kraj = kraj;
  }

  public Siedziba wojewodztwo(String wojewodztwo) {
    this.wojewodztwo = wojewodztwo;
    return this;
  }

   /**
   * Get wojewodztwo
   * @return wojewodztwo
  **/
  @Schema(description = "")
  public String getWojewodztwo() {
    return wojewodztwo;
  }

  public void setWojewodztwo(String wojewodztwo) {
    this.wojewodztwo = wojewodztwo;
  }

  public Siedziba powiat(String powiat) {
    this.powiat = powiat;
    return this;
  }

   /**
   * Get powiat
   * @return powiat
  **/
  @Schema(description = "")
  public String getPowiat() {
    return powiat;
  }

  public void setPowiat(String powiat) {
    this.powiat = powiat;
  }

  public Siedziba gmina(String gmina) {
    this.gmina = gmina;
    return this;
  }

   /**
   * Get gmina
   * @return gmina
  **/
  @Schema(description = "")
  public String getGmina() {
    return gmina;
  }

  public void setGmina(String gmina) {
    this.gmina = gmina;
  }

  public Siedziba miejscowosc(String miejscowosc) {
    this.miejscowosc = miejscowosc;
    return this;
  }

   /**
   * Get miejscowosc
   * @return miejscowosc
  **/
  @Schema(description = "")
  public String getMiejscowosc() {
    return miejscowosc;
  }

  public void setMiejscowosc(String miejscowosc) {
    this.miejscowosc = miejscowosc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Siedziba siedziba = (Siedziba) o;
    return Objects.equals(this.kraj, siedziba.kraj) &&
        Objects.equals(this.wojewodztwo, siedziba.wojewodztwo) &&
        Objects.equals(this.powiat, siedziba.powiat) &&
        Objects.equals(this.gmina, siedziba.gmina) &&
        Objects.equals(this.miejscowosc, siedziba.miejscowosc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kraj, wojewodztwo, powiat, gmina, miejscowosc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Siedziba {\n");
    
    sb.append("    kraj: ").append(toIndentedString(kraj)).append("\n");
    sb.append("    wojewodztwo: ").append(toIndentedString(wojewodztwo)).append("\n");
    sb.append("    powiat: ").append(toIndentedString(powiat)).append("\n");
    sb.append("    gmina: ").append(toIndentedString(gmina)).append("\n");
    sb.append("    miejscowosc: ").append(toIndentedString(miejscowosc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
