/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Skonto
 */
@Schema(description = "Skonto")

public class Skonto {
  @JsonProperty("WarunkiSkonta")
  private String warunkiSkonta = null;

  @JsonProperty("WysokoscSkonta")
  private String wysokoscSkonta = null;

  public Skonto warunkiSkonta(String warunkiSkonta) {
    this.warunkiSkonta = warunkiSkonta;
    return this;
  }

   /**
   * Get warunkiSkonta
   * @return warunkiSkonta
  **/
  @Schema(required = true, description = "")
  public String getWarunkiSkonta() {
    return warunkiSkonta;
  }

  public void setWarunkiSkonta(String warunkiSkonta) {
    this.warunkiSkonta = warunkiSkonta;
  }

  public Skonto wysokoscSkonta(String wysokoscSkonta) {
    this.wysokoscSkonta = wysokoscSkonta;
    return this;
  }

   /**
   * Get wysokoscSkonta
   * @return wysokoscSkonta
  **/
  @Schema(required = true, description = "")
  public String getWysokoscSkonta() {
    return wysokoscSkonta;
  }

  public void setWysokoscSkonta(String wysokoscSkonta) {
    this.wysokoscSkonta = wysokoscSkonta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Skonto skonto = (Skonto) o;
    return Objects.equals(this.warunkiSkonta, skonto.warunkiSkonta) &&
        Objects.equals(this.wysokoscSkonta, skonto.wysokoscSkonta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(warunkiSkonta, wysokoscSkonta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Skonto {\n");
    
    sb.append("    warunkiSkonta: ").append(toIndentedString(warunkiSkonta)).append("\n");
    sb.append("    wysokoscSkonta: ").append(toIndentedString(wysokoscSkonta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
