/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Podmioty;
/**
 * Tylko dla spółki S.A. występuje atrybut
 */
@Schema(description = "Tylko dla spółki S.A. występuje atrybut")

public class SposobPowstaniaPodmiotu {
  @JsonProperty("okolicznosciPowstania")
  private String okolicznosciPowstania = null;

  @JsonProperty("opisSposobuPowstaniaInformacjaOUchwale")
  private String opisSposobuPowstaniaInformacjaOUchwale = null;

  @JsonProperty("nrDataDecyzjiPrezesaUOKiK")
  private String nrDataDecyzjiPrezesaUOKiK = null;

  @JsonProperty("podmioty")
  private List<Podmioty> podmioty = null;

  public SposobPowstaniaPodmiotu okolicznosciPowstania(String okolicznosciPowstania) {
    this.okolicznosciPowstania = okolicznosciPowstania;
    return this;
  }

   /**
   * Get okolicznosciPowstania
   * @return okolicznosciPowstania
  **/
  @Schema(description = "")
  public String getOkolicznosciPowstania() {
    return okolicznosciPowstania;
  }

  public void setOkolicznosciPowstania(String okolicznosciPowstania) {
    this.okolicznosciPowstania = okolicznosciPowstania;
  }

  public SposobPowstaniaPodmiotu opisSposobuPowstaniaInformacjaOUchwale(String opisSposobuPowstaniaInformacjaOUchwale) {
    this.opisSposobuPowstaniaInformacjaOUchwale = opisSposobuPowstaniaInformacjaOUchwale;
    return this;
  }

   /**
   * Get opisSposobuPowstaniaInformacjaOUchwale
   * @return opisSposobuPowstaniaInformacjaOUchwale
  **/
  @Schema(description = "")
  public String getOpisSposobuPowstaniaInformacjaOUchwale() {
    return opisSposobuPowstaniaInformacjaOUchwale;
  }

  public void setOpisSposobuPowstaniaInformacjaOUchwale(String opisSposobuPowstaniaInformacjaOUchwale) {
    this.opisSposobuPowstaniaInformacjaOUchwale = opisSposobuPowstaniaInformacjaOUchwale;
  }

  public SposobPowstaniaPodmiotu nrDataDecyzjiPrezesaUOKiK(String nrDataDecyzjiPrezesaUOKiK) {
    this.nrDataDecyzjiPrezesaUOKiK = nrDataDecyzjiPrezesaUOKiK;
    return this;
  }

   /**
   * Get nrDataDecyzjiPrezesaUOKiK
   * @return nrDataDecyzjiPrezesaUOKiK
  **/
  @Schema(description = "")
  public String getNrDataDecyzjiPrezesaUOKiK() {
    return nrDataDecyzjiPrezesaUOKiK;
  }

  public void setNrDataDecyzjiPrezesaUOKiK(String nrDataDecyzjiPrezesaUOKiK) {
    this.nrDataDecyzjiPrezesaUOKiK = nrDataDecyzjiPrezesaUOKiK;
  }

  public SposobPowstaniaPodmiotu podmioty(List<Podmioty> podmioty) {
    this.podmioty = podmioty;
    return this;
  }

  public SposobPowstaniaPodmiotu addPodmiotyItem(Podmioty podmiotyItem) {
    if (this.podmioty == null) {
      this.podmioty = new ArrayList<>();
    }
    this.podmioty.add(podmiotyItem);
    return this;
  }

   /**
   * Get podmioty
   * @return podmioty
  **/
  @Schema(description = "")
  public List<Podmioty> getPodmioty() {
    return podmioty;
  }

  public void setPodmioty(List<Podmioty> podmioty) {
    this.podmioty = podmioty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SposobPowstaniaPodmiotu sposobPowstaniaPodmiotu = (SposobPowstaniaPodmiotu) o;
    return Objects.equals(this.okolicznosciPowstania, sposobPowstaniaPodmiotu.okolicznosciPowstania) &&
        Objects.equals(this.opisSposobuPowstaniaInformacjaOUchwale, sposobPowstaniaPodmiotu.opisSposobuPowstaniaInformacjaOUchwale) &&
        Objects.equals(this.nrDataDecyzjiPrezesaUOKiK, sposobPowstaniaPodmiotu.nrDataDecyzjiPrezesaUOKiK) &&
        Objects.equals(this.podmioty, sposobPowstaniaPodmiotu.podmioty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(okolicznosciPowstania, opisSposobuPowstaniaInformacjaOUchwale, nrDataDecyzjiPrezesaUOKiK, podmioty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SposobPowstaniaPodmiotu {\n");
    
    sb.append("    okolicznosciPowstania: ").append(toIndentedString(okolicznosciPowstania)).append("\n");
    sb.append("    opisSposobuPowstaniaInformacjaOUchwale: ").append(toIndentedString(opisSposobuPowstaniaInformacjaOUchwale)).append("\n");
    sb.append("    nrDataDecyzjiPrezesaUOKiK: ").append(toIndentedString(nrDataDecyzjiPrezesaUOKiK)).append("\n");
    sb.append("    podmioty: ").append(toIndentedString(podmioty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
