/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
/**
 * TerminPlatnosci
 */


public class TerminPlatnosci {
  @JsonProperty("Termin")
  private LocalDate termin = null;

  @JsonProperty("TerminOpis")
  private String terminOpis = null;

  public TerminPlatnosci termin(LocalDate termin) {
    this.termin = termin;
    return this;
  }

   /**
   * Get termin
   * @return termin
  **/
  @Schema(required = true, description = "")
  public LocalDate getTermin() {
    return termin;
  }

  public void setTermin(LocalDate termin) {
    this.termin = termin;
  }

  public TerminPlatnosci terminOpis(String terminOpis) {
    this.terminOpis = terminOpis;
    return this;
  }

   /**
   * Get terminOpis
   * @return terminOpis
  **/
  @Schema(description = "")
  public String getTerminOpis() {
    return terminOpis;
  }

  public void setTerminOpis(String terminOpis) {
    this.terminOpis = terminOpis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerminPlatnosci terminPlatnosci = (TerminPlatnosci) o;
    return Objects.equals(this.termin, terminPlatnosci.termin) &&
        Objects.equals(this.terminOpis, terminPlatnosci.terminOpis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(termin, terminOpis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminPlatnosci {\n");
    
    sb.append("    termin: ").append(toIndentedString(termin)).append("\n");
    sb.append("    terminOpis: ").append(toIndentedString(terminOpis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
