/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Kody krajów członkowskich Unii Europejskiej, w tym kod dla obszaru Irlandii Północnej
 */
public enum TKodyKrajowUE {
  AT("AT"),
  BE("BE"),
  BG("BG"),
  CY("CY"),
  CZ("CZ"),
  DK("DK"),
  EE("EE"),
  FI("FI"),
  FR("FR"),
  DE("DE"),
  EL("EL"),
  HR("HR"),
  HU("HU"),
  IE("IE"),
  IT("IT"),
  LV("LV"),
  LT("LT"),
  LU("LU"),
  MT("MT"),
  NL("NL"),
  PL("PL"),
  PT("PT"),
  RO("RO"),
  SK("SK"),
  SI("SI"),
  ES("ES"),
  SE("SE"),
  XI("XI");

  private String value;

  TKodyKrajowUE(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TKodyKrajowUE fromValue(String input) {
    for (TKodyKrajowUE b : TKodyKrajowUE.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
