/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TKodFormularza
 */


public class TKodFormularza {
  /**
   * Gets or Sets kodFormularza
   */
  public enum KodFormularzaEnum {
    FA("FA");

    private String value;

    KodFormularzaEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static KodFormularzaEnum fromValue(String input) {
      for (KodFormularzaEnum b : KodFormularzaEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("kodFormularza")
  private KodFormularzaEnum kodFormularza = null;

  /**
   * Gets or Sets kodSystemowy
   */
  public enum KodSystemowyEnum {
    FA_V2("FA_V2");

    private String value;

    KodSystemowyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static KodSystemowyEnum fromValue(String input) {
      for (KodSystemowyEnum b : KodSystemowyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("kodSystemowy")
  private KodSystemowyEnum kodSystemowy = null;

  /**
   * Gets or Sets wersjaSchemy
   */
  public enum WersjaSchemyEnum {
    _1_0E("1_0E");

    private String value;

    WersjaSchemyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static WersjaSchemyEnum fromValue(String input) {
      for (WersjaSchemyEnum b : WersjaSchemyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("wersjaSchemy")
  private WersjaSchemyEnum wersjaSchemy = null;

  public TKodFormularza kodFormularza(KodFormularzaEnum kodFormularza) {
    this.kodFormularza = kodFormularza;
    return this;
  }

   /**
   * Get kodFormularza
   * @return kodFormularza
  **/
  @Schema(description = "")
  public KodFormularzaEnum getKodFormularza() {
    return kodFormularza;
  }

  public void setKodFormularza(KodFormularzaEnum kodFormularza) {
    this.kodFormularza = kodFormularza;
  }

  public TKodFormularza kodSystemowy(KodSystemowyEnum kodSystemowy) {
    this.kodSystemowy = kodSystemowy;
    return this;
  }

   /**
   * Get kodSystemowy
   * @return kodSystemowy
  **/
  @Schema(description = "")
  public KodSystemowyEnum getKodSystemowy() {
    return kodSystemowy;
  }

  public void setKodSystemowy(KodSystemowyEnum kodSystemowy) {
    this.kodSystemowy = kodSystemowy;
  }

  public TKodFormularza wersjaSchemy(WersjaSchemyEnum wersjaSchemy) {
    this.wersjaSchemy = wersjaSchemy;
    return this;
  }

   /**
   * Get wersjaSchemy
   * @return wersjaSchemy
  **/
  @Schema(description = "")
  public WersjaSchemyEnum getWersjaSchemy() {
    return wersjaSchemy;
  }

  public void setWersjaSchemy(WersjaSchemyEnum wersjaSchemy) {
    this.wersjaSchemy = wersjaSchemy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TKodFormularza tkodFormularza = (TKodFormularza) o;
    return Objects.equals(this.kodFormularza, tkodFormularza.kodFormularza) &&
        Objects.equals(this.kodSystemowy, tkodFormularza.kodSystemowy) &&
        Objects.equals(this.wersjaSchemy, tkodFormularza.wersjaSchemy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kodFormularza, kodSystemowy, wersjaSchemy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TKodFormularza {\n");
    
    sb.append("    kodFormularza: ").append(toIndentedString(kodFormularza)).append("\n");
    sb.append("    kodSystemowy: ").append(toIndentedString(kodSystemowy)).append("\n");
    sb.append("    wersjaSchemy: ").append(toIndentedString(wersjaSchemy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
