/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Oznaczenia dotyczące procedur dla faktur
 */
public enum TOznaczenieProcedury {
  WSTO_EE("WSTO_EE"),
  IED("IED"),
  TT_D("TT_D"),
  I_42("I_42"),
  I_63("I_63"),
  B_SPV("B_SPV"),
  B_SPV_DOSTAWA("B_SPV_DOSTAWA"),
  B_MPV_PROWIZJA("B_MPV_PROWIZJA");

  private String value;

  TOznaczenieProcedury(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TOznaczenieProcedury fromValue(String input) {
    for (TOznaczenieProcedury b : TOznaczenieProcedury.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
