/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Zestaw danych identyfikacyjnych oraz danych adresowych podatnika
 */
@Schema(description = "Zestaw danych identyfikacyjnych oraz danych adresowych podatnika")

public class TPodmiot1 {
  @JsonProperty("NIP")
  private String NIP = null;

  @JsonProperty("Nazwa")
  private String nazwa = null;

  public TPodmiot1 NIP(String NIP) {
    this.NIP = NIP;
    return this;
  }

   /**
   * Get NIP
   * @return NIP
  **/
  @Schema(required = true, description = "")
  public String getNIP() {
    return NIP;
  }

  public void setNIP(String NIP) {
    this.NIP = NIP;
  }

  public TPodmiot1 nazwa(String nazwa) {
    this.nazwa = nazwa;
    return this;
  }

   /**
   * Get nazwa
   * @return nazwa
  **/
  @Schema(required = true, description = "")
  public String getNazwa() {
    return nazwa;
  }

  public void setNazwa(String nazwa) {
    this.nazwa = nazwa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TPodmiot1 tpodmiot1 = (TPodmiot1) o;
    return Objects.equals(this.NIP, tpodmiot1.NIP) &&
        Objects.equals(this.nazwa, tpodmiot1.nazwa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(NIP, nazwa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TPodmiot1 {\n");
    
    sb.append("    NIP: ").append(toIndentedString(NIP)).append("\n");
    sb.append("    nazwa: ").append(toIndentedString(nazwa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
