/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Informacje o rachunku
 */
@Schema(description = "Informacje o rachunku")

public class TRachunekBankowy {
  @JsonProperty("NrRB")
  private String nrRB = null;

  @JsonProperty("SWIFT")
  private String SWIFT = null;

  @JsonProperty("RachunekWlasnyBanku")
  private Integer rachunekWlasnyBanku = null;

  @JsonProperty("NazwaBanku")
  private String nazwaBanku = null;

  @JsonProperty("OpisRachunku")
  private String opisRachunku = null;

  public TRachunekBankowy nrRB(String nrRB) {
    this.nrRB = nrRB;
    return this;
  }

   /**
   * Get nrRB
   * @return nrRB
  **/
  @Schema(required = true, description = "")
  public String getNrRB() {
    return nrRB;
  }

  public void setNrRB(String nrRB) {
    this.nrRB = nrRB;
  }

  public TRachunekBankowy SWIFT(String SWIFT) {
    this.SWIFT = SWIFT;
    return this;
  }

   /**
   * Get SWIFT
   * @return SWIFT
  **/
  @Schema(description = "")
  public String getSWIFT() {
    return SWIFT;
  }

  public void setSWIFT(String SWIFT) {
    this.SWIFT = SWIFT;
  }

  public TRachunekBankowy rachunekWlasnyBanku(Integer rachunekWlasnyBanku) {
    this.rachunekWlasnyBanku = rachunekWlasnyBanku;
    return this;
  }

   /**
   * Get rachunekWlasnyBanku
   * @return rachunekWlasnyBanku
  **/
  @Schema(description = "")
  public Integer getRachunekWlasnyBanku() {
    return rachunekWlasnyBanku;
  }

  public void setRachunekWlasnyBanku(Integer rachunekWlasnyBanku) {
    this.rachunekWlasnyBanku = rachunekWlasnyBanku;
  }

  public TRachunekBankowy nazwaBanku(String nazwaBanku) {
    this.nazwaBanku = nazwaBanku;
    return this;
  }

   /**
   * Get nazwaBanku
   * @return nazwaBanku
  **/
  @Schema(description = "")
  public String getNazwaBanku() {
    return nazwaBanku;
  }

  public void setNazwaBanku(String nazwaBanku) {
    this.nazwaBanku = nazwaBanku;
  }

  public TRachunekBankowy opisRachunku(String opisRachunku) {
    this.opisRachunku = opisRachunku;
    return this;
  }

   /**
   * Get opisRachunku
   * @return opisRachunku
  **/
  @Schema(description = "")
  public String getOpisRachunku() {
    return opisRachunku;
  }

  public void setOpisRachunku(String opisRachunku) {
    this.opisRachunku = opisRachunku;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TRachunekBankowy trachunekBankowy = (TRachunekBankowy) o;
    return Objects.equals(this.nrRB, trachunekBankowy.nrRB) &&
        Objects.equals(this.SWIFT, trachunekBankowy.SWIFT) &&
        Objects.equals(this.rachunekWlasnyBanku, trachunekBankowy.rachunekWlasnyBanku) &&
        Objects.equals(this.nazwaBanku, trachunekBankowy.nazwaBanku) &&
        Objects.equals(this.opisRachunku, trachunekBankowy.opisRachunku);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrRB, SWIFT, rachunekWlasnyBanku, nazwaBanku, opisRachunku);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TRachunekBankowy {\n");
    
    sb.append("    nrRB: ").append(toIndentedString(nrRB)).append("\n");
    sb.append("    SWIFT: ").append(toIndentedString(SWIFT)).append("\n");
    sb.append("    rachunekWlasnyBanku: ").append(toIndentedString(rachunekWlasnyBanku)).append("\n");
    sb.append("    nazwaBanku: ").append(toIndentedString(nazwaBanku)).append("\n");
    sb.append("    opisRachunku: ").append(toIndentedString(opisRachunku)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
