/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Przewoznik;
import pl.nip24.client.model.TAdres;
/**
 * Transport
 */


public class Transport {
  @JsonProperty("RodzajTransportu")
  private Integer rodzajTransportu = null;

  @JsonProperty("TransportInny")
  private Integer transportInny = null;

  @JsonProperty("OpisInnegoTransportu")
  private String opisInnegoTransportu = null;

  @JsonProperty("Przewoznik")
  private Przewoznik przewoznik = null;

  @JsonProperty("NrZleceniaTransportu")
  private String nrZleceniaTransportu = null;

  @JsonProperty("OpisLadunku")
  private Integer opisLadunku = null;

  @JsonProperty("LadunekInny")
  private Integer ladunekInny = null;

  @JsonProperty("OpisInnegoLadunku")
  private String opisInnegoLadunku = null;

  @JsonProperty("JednostkaOpakowania")
  private String jednostkaOpakowania = null;

  @JsonProperty("DataGodzRozpTransportu")
  private LocalDateTime dataGodzRozpTransportu = null;

  @JsonProperty("DataGodzZakTransportu")
  private LocalDateTime dataGodzZakTransportu = null;

  @JsonProperty("WysylkaZ")
  private TAdres wysylkaZ = null;

  @JsonProperty("WysylkaPrzez")
  private List<TAdres> wysylkaPrzez = null;

  @JsonProperty("WysylkaDo")
  private TAdres wysylkaDo = null;

  public Transport rodzajTransportu(Integer rodzajTransportu) {
    this.rodzajTransportu = rodzajTransportu;
    return this;
  }

   /**
   * Get rodzajTransportu
   * @return rodzajTransportu
  **/
  @Schema(description = "")
  public Integer getRodzajTransportu() {
    return rodzajTransportu;
  }

  public void setRodzajTransportu(Integer rodzajTransportu) {
    this.rodzajTransportu = rodzajTransportu;
  }

  public Transport transportInny(Integer transportInny) {
    this.transportInny = transportInny;
    return this;
  }

   /**
   * Get transportInny
   * @return transportInny
  **/
  @Schema(description = "")
  public Integer getTransportInny() {
    return transportInny;
  }

  public void setTransportInny(Integer transportInny) {
    this.transportInny = transportInny;
  }

  public Transport opisInnegoTransportu(String opisInnegoTransportu) {
    this.opisInnegoTransportu = opisInnegoTransportu;
    return this;
  }

   /**
   * Get opisInnegoTransportu
   * @return opisInnegoTransportu
  **/
  @Schema(description = "")
  public String getOpisInnegoTransportu() {
    return opisInnegoTransportu;
  }

  public void setOpisInnegoTransportu(String opisInnegoTransportu) {
    this.opisInnegoTransportu = opisInnegoTransportu;
  }

  public Transport przewoznik(Przewoznik przewoznik) {
    this.przewoznik = przewoznik;
    return this;
  }

   /**
   * Get przewoznik
   * @return przewoznik
  **/
  @Schema(description = "")
  public Przewoznik getPrzewoznik() {
    return przewoznik;
  }

  public void setPrzewoznik(Przewoznik przewoznik) {
    this.przewoznik = przewoznik;
  }

  public Transport nrZleceniaTransportu(String nrZleceniaTransportu) {
    this.nrZleceniaTransportu = nrZleceniaTransportu;
    return this;
  }

   /**
   * Get nrZleceniaTransportu
   * @return nrZleceniaTransportu
  **/
  @Schema(description = "")
  public String getNrZleceniaTransportu() {
    return nrZleceniaTransportu;
  }

  public void setNrZleceniaTransportu(String nrZleceniaTransportu) {
    this.nrZleceniaTransportu = nrZleceniaTransportu;
  }

  public Transport opisLadunku(Integer opisLadunku) {
    this.opisLadunku = opisLadunku;
    return this;
  }

   /**
   * Get opisLadunku
   * @return opisLadunku
  **/
  @Schema(description = "")
  public Integer getOpisLadunku() {
    return opisLadunku;
  }

  public void setOpisLadunku(Integer opisLadunku) {
    this.opisLadunku = opisLadunku;
  }

  public Transport ladunekInny(Integer ladunekInny) {
    this.ladunekInny = ladunekInny;
    return this;
  }

   /**
   * Get ladunekInny
   * @return ladunekInny
  **/
  @Schema(description = "")
  public Integer getLadunekInny() {
    return ladunekInny;
  }

  public void setLadunekInny(Integer ladunekInny) {
    this.ladunekInny = ladunekInny;
  }

  public Transport opisInnegoLadunku(String opisInnegoLadunku) {
    this.opisInnegoLadunku = opisInnegoLadunku;
    return this;
  }

   /**
   * Get opisInnegoLadunku
   * @return opisInnegoLadunku
  **/
  @Schema(description = "")
  public String getOpisInnegoLadunku() {
    return opisInnegoLadunku;
  }

  public void setOpisInnegoLadunku(String opisInnegoLadunku) {
    this.opisInnegoLadunku = opisInnegoLadunku;
  }

  public Transport jednostkaOpakowania(String jednostkaOpakowania) {
    this.jednostkaOpakowania = jednostkaOpakowania;
    return this;
  }

   /**
   * Get jednostkaOpakowania
   * @return jednostkaOpakowania
  **/
  @Schema(description = "")
  public String getJednostkaOpakowania() {
    return jednostkaOpakowania;
  }

  public void setJednostkaOpakowania(String jednostkaOpakowania) {
    this.jednostkaOpakowania = jednostkaOpakowania;
  }

  public Transport dataGodzRozpTransportu(LocalDateTime dataGodzRozpTransportu) {
    this.dataGodzRozpTransportu = dataGodzRozpTransportu;
    return this;
  }

   /**
   * Get dataGodzRozpTransportu
   * @return dataGodzRozpTransportu
  **/
  @Schema(description = "")
  public LocalDateTime getDataGodzRozpTransportu() {
    return dataGodzRozpTransportu;
  }

  public void setDataGodzRozpTransportu(LocalDateTime dataGodzRozpTransportu) {
    this.dataGodzRozpTransportu = dataGodzRozpTransportu;
  }

  public Transport dataGodzZakTransportu(LocalDateTime dataGodzZakTransportu) {
    this.dataGodzZakTransportu = dataGodzZakTransportu;
    return this;
  }

   /**
   * Get dataGodzZakTransportu
   * @return dataGodzZakTransportu
  **/
  @Schema(description = "")
  public LocalDateTime getDataGodzZakTransportu() {
    return dataGodzZakTransportu;
  }

  public void setDataGodzZakTransportu(LocalDateTime dataGodzZakTransportu) {
    this.dataGodzZakTransportu = dataGodzZakTransportu;
  }

  public Transport wysylkaZ(TAdres wysylkaZ) {
    this.wysylkaZ = wysylkaZ;
    return this;
  }

   /**
   * Get wysylkaZ
   * @return wysylkaZ
  **/
  @Schema(description = "")
  public TAdres getWysylkaZ() {
    return wysylkaZ;
  }

  public void setWysylkaZ(TAdres wysylkaZ) {
    this.wysylkaZ = wysylkaZ;
  }

  public Transport wysylkaPrzez(List<TAdres> wysylkaPrzez) {
    this.wysylkaPrzez = wysylkaPrzez;
    return this;
  }

  public Transport addWysylkaPrzezItem(TAdres wysylkaPrzezItem) {
    if (this.wysylkaPrzez == null) {
      this.wysylkaPrzez = new ArrayList<>();
    }
    this.wysylkaPrzez.add(wysylkaPrzezItem);
    return this;
  }

   /**
   * Get wysylkaPrzez
   * @return wysylkaPrzez
  **/
  @Schema(description = "")
  public List<TAdres> getWysylkaPrzez() {
    return wysylkaPrzez;
  }

  public void setWysylkaPrzez(List<TAdres> wysylkaPrzez) {
    this.wysylkaPrzez = wysylkaPrzez;
  }

  public Transport wysylkaDo(TAdres wysylkaDo) {
    this.wysylkaDo = wysylkaDo;
    return this;
  }

   /**
   * Get wysylkaDo
   * @return wysylkaDo
  **/
  @Schema(description = "")
  public TAdres getWysylkaDo() {
    return wysylkaDo;
  }

  public void setWysylkaDo(TAdres wysylkaDo) {
    this.wysylkaDo = wysylkaDo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transport transport = (Transport) o;
    return Objects.equals(this.rodzajTransportu, transport.rodzajTransportu) &&
        Objects.equals(this.transportInny, transport.transportInny) &&
        Objects.equals(this.opisInnegoTransportu, transport.opisInnegoTransportu) &&
        Objects.equals(this.przewoznik, transport.przewoznik) &&
        Objects.equals(this.nrZleceniaTransportu, transport.nrZleceniaTransportu) &&
        Objects.equals(this.opisLadunku, transport.opisLadunku) &&
        Objects.equals(this.ladunekInny, transport.ladunekInny) &&
        Objects.equals(this.opisInnegoLadunku, transport.opisInnegoLadunku) &&
        Objects.equals(this.jednostkaOpakowania, transport.jednostkaOpakowania) &&
        Objects.equals(this.dataGodzRozpTransportu, transport.dataGodzRozpTransportu) &&
        Objects.equals(this.dataGodzZakTransportu, transport.dataGodzZakTransportu) &&
        Objects.equals(this.wysylkaZ, transport.wysylkaZ) &&
        Objects.equals(this.wysylkaPrzez, transport.wysylkaPrzez) &&
        Objects.equals(this.wysylkaDo, transport.wysylkaDo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rodzajTransportu, transportInny, opisInnegoTransportu, przewoznik, nrZleceniaTransportu, opisLadunku, ladunekInny, opisInnegoLadunku, jednostkaOpakowania, dataGodzRozpTransportu, dataGodzZakTransportu, wysylkaZ, wysylkaPrzez, wysylkaDo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transport {\n");
    
    sb.append("    rodzajTransportu: ").append(toIndentedString(rodzajTransportu)).append("\n");
    sb.append("    transportInny: ").append(toIndentedString(transportInny)).append("\n");
    sb.append("    opisInnegoTransportu: ").append(toIndentedString(opisInnegoTransportu)).append("\n");
    sb.append("    przewoznik: ").append(toIndentedString(przewoznik)).append("\n");
    sb.append("    nrZleceniaTransportu: ").append(toIndentedString(nrZleceniaTransportu)).append("\n");
    sb.append("    opisLadunku: ").append(toIndentedString(opisLadunku)).append("\n");
    sb.append("    ladunekInny: ").append(toIndentedString(ladunekInny)).append("\n");
    sb.append("    opisInnegoLadunku: ").append(toIndentedString(opisInnegoLadunku)).append("\n");
    sb.append("    jednostkaOpakowania: ").append(toIndentedString(jednostkaOpakowania)).append("\n");
    sb.append("    dataGodzRozpTransportu: ").append(toIndentedString(dataGodzRozpTransportu)).append("\n");
    sb.append("    dataGodzZakTransportu: ").append(toIndentedString(dataGodzZakTransportu)).append("\n");
    sb.append("    wysylkaZ: ").append(toIndentedString(wysylkaZ)).append("\n");
    sb.append("    wysylkaPrzez: ").append(toIndentedString(wysylkaPrzez)).append("\n");
    sb.append("    wysylkaDo: ").append(toIndentedString(wysylkaDo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
