/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Stawka podatku
 */
public enum TStawkaPodatku {
  _23("23"),
  _22("22"),
  _8("8"),
  _7("7"),
  _5("5"),
  _4("4"),
  _3("3"),
  _0("0"),
  ZW("zw"),
  OO("oo"),
  NP("np");

  private String value;

  TStawkaPodatku(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TStawkaPodatku fromValue(String input) {
    for (TStawkaPodatku b : TStawkaPodatku.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
