/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * UchylenieUkladu
 */


public class UchylenieUkladu {
  @JsonProperty("organUchylajacy")
  private String organUchylajacy = null;

  @JsonProperty("dataUchylenia")
  private String dataUchylenia = null;

  @JsonProperty("sygnatura")
  private String sygnatura = null;

  public UchylenieUkladu organUchylajacy(String organUchylajacy) {
    this.organUchylajacy = organUchylajacy;
    return this;
  }

   /**
   * Get organUchylajacy
   * @return organUchylajacy
  **/
  @Schema(description = "")
  public String getOrganUchylajacy() {
    return organUchylajacy;
  }

  public void setOrganUchylajacy(String organUchylajacy) {
    this.organUchylajacy = organUchylajacy;
  }

  public UchylenieUkladu dataUchylenia(String dataUchylenia) {
    this.dataUchylenia = dataUchylenia;
    return this;
  }

   /**
   * Get dataUchylenia
   * @return dataUchylenia
  **/
  @Schema(description = "")
  public String getDataUchylenia() {
    return dataUchylenia;
  }

  public void setDataUchylenia(String dataUchylenia) {
    this.dataUchylenia = dataUchylenia;
  }

  public UchylenieUkladu sygnatura(String sygnatura) {
    this.sygnatura = sygnatura;
    return this;
  }

   /**
   * Get sygnatura
   * @return sygnatura
  **/
  @Schema(description = "")
  public String getSygnatura() {
    return sygnatura;
  }

  public void setSygnatura(String sygnatura) {
    this.sygnatura = sygnatura;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UchylenieUkladu uchylenieUkladu = (UchylenieUkladu) o;
    return Objects.equals(this.organUchylajacy, uchylenieUkladu.organUchylajacy) &&
        Objects.equals(this.dataUchylenia, uchylenieUkladu.dataUchylenia) &&
        Objects.equals(this.sygnatura, uchylenieUkladu.sygnatura);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organUchylajacy, dataUchylenia, sygnatura);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UchylenieUkladu {\n");
    
    sb.append("    organUchylajacy: ").append(toIndentedString(organUchylajacy)).append("\n");
    sb.append("    dataUchylenia: ").append(toIndentedString(dataUchylenia)).append("\n");
    sb.append("    sygnatura: ").append(toIndentedString(sygnatura)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
