/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
/**
 * Umowy
 */


public class Umowy {
  @JsonProperty("DataUmowy")
  private LocalDate dataUmowy = null;

  @JsonProperty("NrUmowy")
  private String nrUmowy = null;

  public Umowy dataUmowy(LocalDate dataUmowy) {
    this.dataUmowy = dataUmowy;
    return this;
  }

   /**
   * Get dataUmowy
   * @return dataUmowy
  **/
  @Schema(description = "")
  public LocalDate getDataUmowy() {
    return dataUmowy;
  }

  public void setDataUmowy(LocalDate dataUmowy) {
    this.dataUmowy = dataUmowy;
  }

  public Umowy nrUmowy(String nrUmowy) {
    this.nrUmowy = nrUmowy;
    return this;
  }

   /**
   * Get nrUmowy
   * @return nrUmowy
  **/
  @Schema(description = "")
  public String getNrUmowy() {
    return nrUmowy;
  }

  public void setNrUmowy(String nrUmowy) {
    this.nrUmowy = nrUmowy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Umowy umowy = (Umowy) o;
    return Objects.equals(this.dataUmowy, umowy.dataUmowy) &&
        Objects.equals(this.nrUmowy, umowy.nrUmowy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataUmowy, nrUmowy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Umowy {\n");
    
    sb.append("    dataUmowy: ").append(toIndentedString(dataUmowy)).append("\n");
    sb.append("    nrUmowy: ").append(toIndentedString(nrUmowy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
