/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.TKodWaluty;
import pl.nip24.client.model.Transport;
import pl.nip24.client.model.Umowy;
import pl.nip24.client.model.Zamowienia;
/**
 * Warunki transakcji, o ile występują
 */
@Schema(description = "Warunki transakcji, o ile występują")

public class WarunkiTransakcji {
  @JsonProperty("Umowy")
  private List<Umowy> umowy = null;

  @JsonProperty("Zamowienia")
  private List<Zamowienia> zamowienia = null;

  @JsonProperty("NrPartiiTowaru")
  private List<String> nrPartiiTowaru = null;

  @JsonProperty("WarunkiDostawy")
  private String warunkiDostawy = null;

  @JsonProperty("KursUmowny")
  private Double kursUmowny = null;

  @JsonProperty("WalutaUmowna")
  private TKodWaluty walutaUmowna = null;

  @JsonProperty("Transport")
  private List<Transport> transport = null;

  @JsonProperty("PodmiotPosredniczacy")
  private Integer podmiotPosredniczacy = null;

  public WarunkiTransakcji umowy(List<Umowy> umowy) {
    this.umowy = umowy;
    return this;
  }

  public WarunkiTransakcji addUmowyItem(Umowy umowyItem) {
    if (this.umowy == null) {
      this.umowy = new ArrayList<>();
    }
    this.umowy.add(umowyItem);
    return this;
  }

   /**
   * Get umowy
   * @return umowy
  **/
  @Schema(description = "")
  public List<Umowy> getUmowy() {
    return umowy;
  }

  public void setUmowy(List<Umowy> umowy) {
    this.umowy = umowy;
  }

  public WarunkiTransakcji zamowienia(List<Zamowienia> zamowienia) {
    this.zamowienia = zamowienia;
    return this;
  }

  public WarunkiTransakcji addZamowieniaItem(Zamowienia zamowieniaItem) {
    if (this.zamowienia == null) {
      this.zamowienia = new ArrayList<>();
    }
    this.zamowienia.add(zamowieniaItem);
    return this;
  }

   /**
   * Get zamowienia
   * @return zamowienia
  **/
  @Schema(description = "")
  public List<Zamowienia> getZamowienia() {
    return zamowienia;
  }

  public void setZamowienia(List<Zamowienia> zamowienia) {
    this.zamowienia = zamowienia;
  }

  public WarunkiTransakcji nrPartiiTowaru(List<String> nrPartiiTowaru) {
    this.nrPartiiTowaru = nrPartiiTowaru;
    return this;
  }

  public WarunkiTransakcji addNrPartiiTowaruItem(String nrPartiiTowaruItem) {
    if (this.nrPartiiTowaru == null) {
      this.nrPartiiTowaru = new ArrayList<>();
    }
    this.nrPartiiTowaru.add(nrPartiiTowaruItem);
    return this;
  }

   /**
   * Get nrPartiiTowaru
   * @return nrPartiiTowaru
  **/
  @Schema(description = "")
  public List<String> getNrPartiiTowaru() {
    return nrPartiiTowaru;
  }

  public void setNrPartiiTowaru(List<String> nrPartiiTowaru) {
    this.nrPartiiTowaru = nrPartiiTowaru;
  }

  public WarunkiTransakcji warunkiDostawy(String warunkiDostawy) {
    this.warunkiDostawy = warunkiDostawy;
    return this;
  }

   /**
   * Get warunkiDostawy
   * @return warunkiDostawy
  **/
  @Schema(description = "")
  public String getWarunkiDostawy() {
    return warunkiDostawy;
  }

  public void setWarunkiDostawy(String warunkiDostawy) {
    this.warunkiDostawy = warunkiDostawy;
  }

  public WarunkiTransakcji kursUmowny(Double kursUmowny) {
    this.kursUmowny = kursUmowny;
    return this;
  }

   /**
   * Get kursUmowny
   * @return kursUmowny
  **/
  @Schema(description = "")
  public Double getKursUmowny() {
    return kursUmowny;
  }

  public void setKursUmowny(Double kursUmowny) {
    this.kursUmowny = kursUmowny;
  }

  public WarunkiTransakcji walutaUmowna(TKodWaluty walutaUmowna) {
    this.walutaUmowna = walutaUmowna;
    return this;
  }

   /**
   * Get walutaUmowna
   * @return walutaUmowna
  **/
  @Schema(description = "")
  public TKodWaluty getWalutaUmowna() {
    return walutaUmowna;
  }

  public void setWalutaUmowna(TKodWaluty walutaUmowna) {
    this.walutaUmowna = walutaUmowna;
  }

  public WarunkiTransakcji transport(List<Transport> transport) {
    this.transport = transport;
    return this;
  }

  public WarunkiTransakcji addTransportItem(Transport transportItem) {
    if (this.transport == null) {
      this.transport = new ArrayList<>();
    }
    this.transport.add(transportItem);
    return this;
  }

   /**
   * Get transport
   * @return transport
  **/
  @Schema(description = "")
  public List<Transport> getTransport() {
    return transport;
  }

  public void setTransport(List<Transport> transport) {
    this.transport = transport;
  }

  public WarunkiTransakcji podmiotPosredniczacy(Integer podmiotPosredniczacy) {
    this.podmiotPosredniczacy = podmiotPosredniczacy;
    return this;
  }

   /**
   * Get podmiotPosredniczacy
   * @return podmiotPosredniczacy
  **/
  @Schema(description = "")
  public Integer getPodmiotPosredniczacy() {
    return podmiotPosredniczacy;
  }

  public void setPodmiotPosredniczacy(Integer podmiotPosredniczacy) {
    this.podmiotPosredniczacy = podmiotPosredniczacy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WarunkiTransakcji warunkiTransakcji = (WarunkiTransakcji) o;
    return Objects.equals(this.umowy, warunkiTransakcji.umowy) &&
        Objects.equals(this.zamowienia, warunkiTransakcji.zamowienia) &&
        Objects.equals(this.nrPartiiTowaru, warunkiTransakcji.nrPartiiTowaru) &&
        Objects.equals(this.warunkiDostawy, warunkiTransakcji.warunkiDostawy) &&
        Objects.equals(this.kursUmowny, warunkiTransakcji.kursUmowny) &&
        Objects.equals(this.walutaUmowna, warunkiTransakcji.walutaUmowna) &&
        Objects.equals(this.transport, warunkiTransakcji.transport) &&
        Objects.equals(this.podmiotPosredniczacy, warunkiTransakcji.podmiotPosredniczacy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(umowy, zamowienia, nrPartiiTowaru, warunkiDostawy, kursUmowny, walutaUmowna, transport, podmiotPosredniczacy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WarunkiTransakcji {\n");
    
    sb.append("    umowy: ").append(toIndentedString(umowy)).append("\n");
    sb.append("    zamowienia: ").append(toIndentedString(zamowienia)).append("\n");
    sb.append("    nrPartiiTowaru: ").append(toIndentedString(nrPartiiTowaru)).append("\n");
    sb.append("    warunkiDostawy: ").append(toIndentedString(warunkiDostawy)).append("\n");
    sb.append("    kursUmowny: ").append(toIndentedString(kursUmowny)).append("\n");
    sb.append("    walutaUmowna: ").append(toIndentedString(walutaUmowna)).append("\n");
    sb.append("    transport: ").append(toIndentedString(transport)).append("\n");
    sb.append("    podmiotPosredniczacy: ").append(toIndentedString(podmiotPosredniczacy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
