/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.IdentyfikatorOsoby;
import pl.nip24.client.model.ImionaOsoby;
import pl.nip24.client.model.NazwiskoOsoby;
/**
 * WspolnicySpzoo
 */


public class WspolnicySpzoo {
  @JsonProperty("nazwisko")
  private NazwiskoOsoby nazwisko = null;

  @JsonProperty("imiona")
  private ImionaOsoby imiona = null;

  @JsonProperty("identyfikator")
  private IdentyfikatorOsoby identyfikator = null;

  @JsonProperty("posiadaneUdzialy")
  private String posiadaneUdzialy = null;

  @JsonProperty("czyPosiadaCaloscUdzialow")
  private Boolean czyPosiadaCaloscUdzialow = null;

  public WspolnicySpzoo nazwisko(NazwiskoOsoby nazwisko) {
    this.nazwisko = nazwisko;
    return this;
  }

   /**
   * Get nazwisko
   * @return nazwisko
  **/
  @Schema(description = "")
  public NazwiskoOsoby getNazwisko() {
    return nazwisko;
  }

  public void setNazwisko(NazwiskoOsoby nazwisko) {
    this.nazwisko = nazwisko;
  }

  public WspolnicySpzoo imiona(ImionaOsoby imiona) {
    this.imiona = imiona;
    return this;
  }

   /**
   * Get imiona
   * @return imiona
  **/
  @Schema(description = "")
  public ImionaOsoby getImiona() {
    return imiona;
  }

  public void setImiona(ImionaOsoby imiona) {
    this.imiona = imiona;
  }

  public WspolnicySpzoo identyfikator(IdentyfikatorOsoby identyfikator) {
    this.identyfikator = identyfikator;
    return this;
  }

   /**
   * Get identyfikator
   * @return identyfikator
  **/
  @Schema(description = "")
  public IdentyfikatorOsoby getIdentyfikator() {
    return identyfikator;
  }

  public void setIdentyfikator(IdentyfikatorOsoby identyfikator) {
    this.identyfikator = identyfikator;
  }

  public WspolnicySpzoo posiadaneUdzialy(String posiadaneUdzialy) {
    this.posiadaneUdzialy = posiadaneUdzialy;
    return this;
  }

   /**
   * Get posiadaneUdzialy
   * @return posiadaneUdzialy
  **/
  @Schema(description = "")
  public String getPosiadaneUdzialy() {
    return posiadaneUdzialy;
  }

  public void setPosiadaneUdzialy(String posiadaneUdzialy) {
    this.posiadaneUdzialy = posiadaneUdzialy;
  }

  public WspolnicySpzoo czyPosiadaCaloscUdzialow(Boolean czyPosiadaCaloscUdzialow) {
    this.czyPosiadaCaloscUdzialow = czyPosiadaCaloscUdzialow;
    return this;
  }

   /**
   * Get czyPosiadaCaloscUdzialow
   * @return czyPosiadaCaloscUdzialow
  **/
  @Schema(description = "")
  public Boolean isCzyPosiadaCaloscUdzialow() {
    return czyPosiadaCaloscUdzialow;
  }

  public void setCzyPosiadaCaloscUdzialow(Boolean czyPosiadaCaloscUdzialow) {
    this.czyPosiadaCaloscUdzialow = czyPosiadaCaloscUdzialow;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WspolnicySpzoo wspolnicySpzoo = (WspolnicySpzoo) o;
    return Objects.equals(this.nazwisko, wspolnicySpzoo.nazwisko) &&
        Objects.equals(this.imiona, wspolnicySpzoo.imiona) &&
        Objects.equals(this.identyfikator, wspolnicySpzoo.identyfikator) &&
        Objects.equals(this.posiadaneUdzialy, wspolnicySpzoo.posiadaneUdzialy) &&
        Objects.equals(this.czyPosiadaCaloscUdzialow, wspolnicySpzoo.czyPosiadaCaloscUdzialow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nazwisko, imiona, identyfikator, posiadaneUdzialy, czyPosiadaCaloscUdzialow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WspolnicySpzoo {\n");
    
    sb.append("    nazwisko: ").append(toIndentedString(nazwisko)).append("\n");
    sb.append("    imiona: ").append(toIndentedString(imiona)).append("\n");
    sb.append("    identyfikator: ").append(toIndentedString(identyfikator)).append("\n");
    sb.append("    posiadaneUdzialy: ").append(toIndentedString(posiadaneUdzialy)).append("\n");
    sb.append("    czyPosiadaCaloscUdzialow: ").append(toIndentedString(czyPosiadaCaloscUdzialow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
