/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * WysokoscKapitaluZakladowego
 */


public class WysokoscKapitaluZakladowego {
  @JsonProperty("wartosc")
  private String wartosc = null;

  @JsonProperty("waluta")
  private String waluta = null;

  public WysokoscKapitaluZakladowego wartosc(String wartosc) {
    this.wartosc = wartosc;
    return this;
  }

   /**
   * Get wartosc
   * @return wartosc
  **/
  @Schema(description = "")
  public String getWartosc() {
    return wartosc;
  }

  public void setWartosc(String wartosc) {
    this.wartosc = wartosc;
  }

  public WysokoscKapitaluZakladowego waluta(String waluta) {
    this.waluta = waluta;
    return this;
  }

   /**
   * Get waluta
   * @return waluta
  **/
  @Schema(description = "")
  public String getWaluta() {
    return waluta;
  }

  public void setWaluta(String waluta) {
    this.waluta = waluta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WysokoscKapitaluZakladowego wysokoscKapitaluZakladowego = (WysokoscKapitaluZakladowego) o;
    return Objects.equals(this.wartosc, wysokoscKapitaluZakladowego.wartosc) &&
        Objects.equals(this.waluta, wysokoscKapitaluZakladowego.waluta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wartosc, waluta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WysokoscKapitaluZakladowego {\n");
    
    sb.append("    wartosc: ").append(toIndentedString(wartosc)).append("\n");
    sb.append("    waluta: ").append(toIndentedString(waluta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
