/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import pl.nip24.client.model.Wzmianka;
/**
 * WzmiankiOZlozonychDokumentach
 */


public class WzmiankiOZlozonychDokumentach {
  @JsonProperty("wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania")
  private List<Wzmianka> wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania = null;

  @JsonProperty("wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego")
  private List<Wzmianka> wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego = null;

  @JsonProperty("wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego")
  private List<Wzmianka> wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego = null;

  @JsonProperty("wzmiankaOZlozeniuSprawozdaniaZDzialalnosci")
  private List<Wzmianka> wzmiankaOZlozeniuSprawozdaniaZDzialalnosci = null;

  public WzmiankiOZlozonychDokumentach wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania(List<Wzmianka> wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania) {
    this.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania = wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania;
    return this;
  }

  public WzmiankiOZlozonychDokumentach addWzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadaniaItem(Wzmianka wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadaniaItem) {
    if (this.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania == null) {
      this.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania = new ArrayList<Wzmianka>();
    }
    this.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania.add(wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadaniaItem);
    return this;
  }

   /**
   * Get wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania
   * @return wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania
  **/
  @Schema(description = "")
  public List<Wzmianka> getWzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania() {
    return wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania;
  }

  public void setWzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania(List<Wzmianka> wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania) {
    this.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania = wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania;
  }

  public WzmiankiOZlozonychDokumentach wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego(List<Wzmianka> wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego) {
    this.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego = wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego;
    return this;
  }

  public WzmiankiOZlozonychDokumentach addWzmiankaOZlozeniuRocznegoSprawozdaniaFinansowegoItem(Wzmianka wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowegoItem) {
    if (this.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego == null) {
      this.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego = new ArrayList<Wzmianka>();
    }
    this.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego.add(wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowegoItem);
    return this;
  }

   /**
   * Get wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego
   * @return wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego
  **/
  @Schema(description = "")
  public List<Wzmianka> getWzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego() {
    return wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego;
  }

  public void setWzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego(List<Wzmianka> wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego) {
    this.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego = wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego;
  }

  public WzmiankiOZlozonychDokumentach wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego(List<Wzmianka> wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego) {
    this.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego = wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego;
    return this;
  }

  public WzmiankiOZlozonychDokumentach addWzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowegoItem(Wzmianka wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowegoItem) {
    if (this.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego == null) {
      this.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego = new ArrayList<Wzmianka>();
    }
    this.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego.add(wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowegoItem);
    return this;
  }

   /**
   * Get wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego
   * @return wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego
  **/
  @Schema(description = "")
  public List<Wzmianka> getWzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego() {
    return wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego;
  }

  public void setWzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego(List<Wzmianka> wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego) {
    this.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego = wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego;
  }

  public WzmiankiOZlozonychDokumentach wzmiankaOZlozeniuSprawozdaniaZDzialalnosci(List<Wzmianka> wzmiankaOZlozeniuSprawozdaniaZDzialalnosci) {
    this.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci = wzmiankaOZlozeniuSprawozdaniaZDzialalnosci;
    return this;
  }

  public WzmiankiOZlozonychDokumentach addWzmiankaOZlozeniuSprawozdaniaZDzialalnosciItem(Wzmianka wzmiankaOZlozeniuSprawozdaniaZDzialalnosciItem) {
    if (this.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci == null) {
      this.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci = new ArrayList<Wzmianka>();
    }
    this.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci.add(wzmiankaOZlozeniuSprawozdaniaZDzialalnosciItem);
    return this;
  }

   /**
   * Get wzmiankaOZlozeniuSprawozdaniaZDzialalnosci
   * @return wzmiankaOZlozeniuSprawozdaniaZDzialalnosci
  **/
  @Schema(description = "")
  public List<Wzmianka> getWzmiankaOZlozeniuSprawozdaniaZDzialalnosci() {
    return wzmiankaOZlozeniuSprawozdaniaZDzialalnosci;
  }

  public void setWzmiankaOZlozeniuSprawozdaniaZDzialalnosci(List<Wzmianka> wzmiankaOZlozeniuSprawozdaniaZDzialalnosci) {
    this.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci = wzmiankaOZlozeniuSprawozdaniaZDzialalnosci;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WzmiankiOZlozonychDokumentach wzmiankiOZlozonychDokumentach = (WzmiankiOZlozonychDokumentach) o;
    return Objects.equals(this.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania, wzmiankiOZlozonychDokumentach.wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania) &&
        Objects.equals(this.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego, wzmiankiOZlozonychDokumentach.wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego) &&
        Objects.equals(this.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego, wzmiankiOZlozonychDokumentach.wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego) &&
        Objects.equals(this.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci, wzmiankiOZlozonychDokumentach.wzmiankaOZlozeniuSprawozdaniaZDzialalnosci);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania, wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego, wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego, wzmiankaOZlozeniuSprawozdaniaZDzialalnosci);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WzmiankiOZlozonychDokumentach {\n");
    
    sb.append("    wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania: ").append(toIndentedString(wzmiankaOZlozeniuOpiniiBieglegoRewidentaSprawozdaniaZBadania)).append("\n");
    sb.append("    wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego: ").append(toIndentedString(wzmiankaOZlozeniuRocznegoSprawozdaniaFinansowego)).append("\n");
    sb.append("    wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego: ").append(toIndentedString(wzmiankaOZlozeniuUchwalyPostanowieniaOZatwierdzeniuRocznegoSprawozdaniaFinansowego)).append("\n");
    sb.append("    wzmiankaOZlozeniuSprawozdaniaZDzialalnosci: ").append(toIndentedString(wzmiankaOZlozeniuSprawozdaniaZDzialalnosci)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
