/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych
 */


public class WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych {
  @JsonProperty("czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych")
  private Boolean czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych = null;

  public WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych(Boolean czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych) {
    this.czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych = czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych;
    return this;
  }

   /**
   * Get czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych
   * @return czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych
  **/
  @Schema(description = "")
  public Boolean isCzyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych() {
    return czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych;
  }

  public void setCzyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych(Boolean czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych) {
    this.czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych = czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych wzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych = (WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych) o;
    return Objects.equals(this.czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych, wzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych.czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych);
  }

  @Override
  public int hashCode() {
    return Objects.hash(czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych {\n");
    
    sb.append("    czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych: ").append(toIndentedString(czyZarzadJestUprawnionyDoEmisjiWarrantowSubskrypcyjnych)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
