/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych
 */


public class WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych {
  @JsonProperty("dataPodjeciaUchwaly")
  private String dataPodjeciaUchwaly = null;

  public WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych dataPodjeciaUchwaly(String dataPodjeciaUchwaly) {
    this.dataPodjeciaUchwaly = dataPodjeciaUchwaly;
    return this;
  }

   /**
   * Get dataPodjeciaUchwaly
   * @return dataPodjeciaUchwaly
  **/
  @Schema(description = "")
  public String getDataPodjeciaUchwaly() {
    return dataPodjeciaUchwaly;
  }

  public void setDataPodjeciaUchwaly(String dataPodjeciaUchwaly) {
    this.dataPodjeciaUchwaly = dataPodjeciaUchwaly;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych wzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych = (WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych) o;
    return Objects.equals(this.dataPodjeciaUchwaly, wzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych.dataPodjeciaUchwaly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataPodjeciaUchwaly);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych {\n");
    
    sb.append("    dataPodjeciaUchwaly: ").append(toIndentedString(dataPodjeciaUchwaly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
