/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym;
/**
 * ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc
 */


public class ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc {
  @JsonProperty("oddalenieWnioskuOUpadlosc")
  private String oddalenieWnioskuOUpadlosc = null;

  @JsonProperty("dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego")
  private String dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego = null;

  @JsonProperty("zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym")
  private ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym = null;

  public ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc oddalenieWnioskuOUpadlosc(String oddalenieWnioskuOUpadlosc) {
    this.oddalenieWnioskuOUpadlosc = oddalenieWnioskuOUpadlosc;
    return this;
  }

   /**
   * Get oddalenieWnioskuOUpadlosc
   * @return oddalenieWnioskuOUpadlosc
  **/
  @Schema(description = "")
  public String getOddalenieWnioskuOUpadlosc() {
    return oddalenieWnioskuOUpadlosc;
  }

  public void setOddalenieWnioskuOUpadlosc(String oddalenieWnioskuOUpadlosc) {
    this.oddalenieWnioskuOUpadlosc = oddalenieWnioskuOUpadlosc;
  }

  public ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego(String dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego) {
    this.dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego = dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego;
    return this;
  }

   /**
   * Get dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego
   * @return dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego
  **/
  @Schema(description = "")
  public String getDalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego() {
    return dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego;
  }

  public void setDalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego(String dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego) {
    this.dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego = dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego;
  }

  public ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym(ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym) {
    this.zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym = zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym;
    return this;
  }

   /**
   * Get zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym
   * @return zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym
  **/
  @Schema(description = "")
  public ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym getZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym() {
    return zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym;
  }

  public void setZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym(ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym) {
    this.zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym = zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc zabezpieczenieMajatkuOddalenieWnioskuOUpadlosc = (ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc) o;
    return Objects.equals(this.oddalenieWnioskuOUpadlosc, zabezpieczenieMajatkuOddalenieWnioskuOUpadlosc.oddalenieWnioskuOUpadlosc) &&
        Objects.equals(this.dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego, zabezpieczenieMajatkuOddalenieWnioskuOUpadlosc.dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego) &&
        Objects.equals(this.zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym, zabezpieczenieMajatkuOddalenieWnioskuOUpadlosc.zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oddalenieWnioskuOUpadlosc, dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego, zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZabezpieczenieMajatkuOddalenieWnioskuOUpadlosc {\n");
    
    sb.append("    oddalenieWnioskuOUpadlosc: ").append(toIndentedString(oddalenieWnioskuOUpadlosc)).append("\n");
    sb.append("    dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego: ").append(toIndentedString(dalszePelnienieFunkcjiPoUkonczeniuPostepowaniaRestrukturyzacyjnego)).append("\n");
    sb.append("    zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym: ").append(toIndentedString(zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
