/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym
 */


public class ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym {
  @JsonProperty("organWydajacy")
  private String organWydajacy = null;

  @JsonProperty("sygnaturaSprawy")
  private String sygnaturaSprawy = null;

  @JsonProperty("dataNadaniaKlauzuliWykonalnosci")
  private String dataNadaniaKlauzuliWykonalnosci = null;

  @JsonProperty("informacjaOPrzedmiocieZabezpieczenia")
  private String informacjaOPrzedmiocieZabezpieczenia = null;

  @JsonProperty("rodzajPostepowania")
  private String rodzajPostepowania = null;

  public ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym organWydajacy(String organWydajacy) {
    this.organWydajacy = organWydajacy;
    return this;
  }

   /**
   * Get organWydajacy
   * @return organWydajacy
  **/
  @Schema(description = "")
  public String getOrganWydajacy() {
    return organWydajacy;
  }

  public void setOrganWydajacy(String organWydajacy) {
    this.organWydajacy = organWydajacy;
  }

  public ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym sygnaturaSprawy(String sygnaturaSprawy) {
    this.sygnaturaSprawy = sygnaturaSprawy;
    return this;
  }

   /**
   * Get sygnaturaSprawy
   * @return sygnaturaSprawy
  **/
  @Schema(description = "")
  public String getSygnaturaSprawy() {
    return sygnaturaSprawy;
  }

  public void setSygnaturaSprawy(String sygnaturaSprawy) {
    this.sygnaturaSprawy = sygnaturaSprawy;
  }

  public ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym dataNadaniaKlauzuliWykonalnosci(String dataNadaniaKlauzuliWykonalnosci) {
    this.dataNadaniaKlauzuliWykonalnosci = dataNadaniaKlauzuliWykonalnosci;
    return this;
  }

   /**
   * Get dataNadaniaKlauzuliWykonalnosci
   * @return dataNadaniaKlauzuliWykonalnosci
  **/
  @Schema(description = "")
  public String getDataNadaniaKlauzuliWykonalnosci() {
    return dataNadaniaKlauzuliWykonalnosci;
  }

  public void setDataNadaniaKlauzuliWykonalnosci(String dataNadaniaKlauzuliWykonalnosci) {
    this.dataNadaniaKlauzuliWykonalnosci = dataNadaniaKlauzuliWykonalnosci;
  }

  public ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym informacjaOPrzedmiocieZabezpieczenia(String informacjaOPrzedmiocieZabezpieczenia) {
    this.informacjaOPrzedmiocieZabezpieczenia = informacjaOPrzedmiocieZabezpieczenia;
    return this;
  }

   /**
   * Get informacjaOPrzedmiocieZabezpieczenia
   * @return informacjaOPrzedmiocieZabezpieczenia
  **/
  @Schema(description = "")
  public String getInformacjaOPrzedmiocieZabezpieczenia() {
    return informacjaOPrzedmiocieZabezpieczenia;
  }

  public void setInformacjaOPrzedmiocieZabezpieczenia(String informacjaOPrzedmiocieZabezpieczenia) {
    this.informacjaOPrzedmiocieZabezpieczenia = informacjaOPrzedmiocieZabezpieczenia;
  }

  public ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym rodzajPostepowania(String rodzajPostepowania) {
    this.rodzajPostepowania = rodzajPostepowania;
    return this;
  }

   /**
   * Get rodzajPostepowania
   * @return rodzajPostepowania
  **/
  @Schema(description = "")
  public String getRodzajPostepowania() {
    return rodzajPostepowania;
  }

  public void setRodzajPostepowania(String rodzajPostepowania) {
    this.rodzajPostepowania = rodzajPostepowania;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym = (ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym) o;
    return Objects.equals(this.organWydajacy, zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym.organWydajacy) &&
        Objects.equals(this.sygnaturaSprawy, zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym.sygnaturaSprawy) &&
        Objects.equals(this.dataNadaniaKlauzuliWykonalnosci, zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym.dataNadaniaKlauzuliWykonalnosci) &&
        Objects.equals(this.informacjaOPrzedmiocieZabezpieczenia, zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym.informacjaOPrzedmiocieZabezpieczenia) &&
        Objects.equals(this.rodzajPostepowania, zabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym.rodzajPostepowania);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organWydajacy, sygnaturaSprawy, dataNadaniaKlauzuliWykonalnosci, informacjaOPrzedmiocieZabezpieczenia, rodzajPostepowania);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZabezpieczenieMajatkuDluznikaWPostepowaniuUpadlosciowym {\n");
    
    sb.append("    organWydajacy: ").append(toIndentedString(organWydajacy)).append("\n");
    sb.append("    sygnaturaSprawy: ").append(toIndentedString(sygnaturaSprawy)).append("\n");
    sb.append("    dataNadaniaKlauzuliWykonalnosci: ").append(toIndentedString(dataNadaniaKlauzuliWykonalnosci)).append("\n");
    sb.append("    informacjaOPrzedmiocieZabezpieczenia: ").append(toIndentedString(informacjaOPrzedmiocieZabezpieczenia)).append("\n");
    sb.append("    rodzajPostepowania: ").append(toIndentedString(rodzajPostepowania)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
