/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import pl.nip24.client.model.DaneEgzekucji;
import pl.nip24.client.model.WszczecieEgzekucji;
import pl.nip24.client.model.WysokoscZaleglosci;
/**
 * Zaleglosci
 */


public class Zaleglosci {
  @JsonProperty("charakterZaleglosci")
  private String charakterZaleglosci = null;

  @JsonProperty("zakonczenieEgzekucji")
  private String zakonczenieEgzekucji = null;

  @JsonProperty("wszczecieEgzekucji")
  private WszczecieEgzekucji wszczecieEgzekucji = null;

  @JsonProperty("umorzenieEgzekucji")
  private DaneEgzekucji umorzenieEgzekucji = null;

  @JsonProperty("wysokoscZaleglosci")
  private WysokoscZaleglosci wysokoscZaleglosci = null;

  public Zaleglosci charakterZaleglosci(String charakterZaleglosci) {
    this.charakterZaleglosci = charakterZaleglosci;
    return this;
  }

   /**
   * Get charakterZaleglosci
   * @return charakterZaleglosci
  **/
  @Schema(description = "")
  public String getCharakterZaleglosci() {
    return charakterZaleglosci;
  }

  public void setCharakterZaleglosci(String charakterZaleglosci) {
    this.charakterZaleglosci = charakterZaleglosci;
  }

  public Zaleglosci zakonczenieEgzekucji(String zakonczenieEgzekucji) {
    this.zakonczenieEgzekucji = zakonczenieEgzekucji;
    return this;
  }

   /**
   * Get zakonczenieEgzekucji
   * @return zakonczenieEgzekucji
  **/
  @Schema(description = "")
  public String getZakonczenieEgzekucji() {
    return zakonczenieEgzekucji;
  }

  public void setZakonczenieEgzekucji(String zakonczenieEgzekucji) {
    this.zakonczenieEgzekucji = zakonczenieEgzekucji;
  }

  public Zaleglosci wszczecieEgzekucji(WszczecieEgzekucji wszczecieEgzekucji) {
    this.wszczecieEgzekucji = wszczecieEgzekucji;
    return this;
  }

   /**
   * Get wszczecieEgzekucji
   * @return wszczecieEgzekucji
  **/
  @Schema(description = "")
  public WszczecieEgzekucji getWszczecieEgzekucji() {
    return wszczecieEgzekucji;
  }

  public void setWszczecieEgzekucji(WszczecieEgzekucji wszczecieEgzekucji) {
    this.wszczecieEgzekucji = wszczecieEgzekucji;
  }

  public Zaleglosci umorzenieEgzekucji(DaneEgzekucji umorzenieEgzekucji) {
    this.umorzenieEgzekucji = umorzenieEgzekucji;
    return this;
  }

   /**
   * Get umorzenieEgzekucji
   * @return umorzenieEgzekucji
  **/
  @Schema(description = "")
  public DaneEgzekucji getUmorzenieEgzekucji() {
    return umorzenieEgzekucji;
  }

  public void setUmorzenieEgzekucji(DaneEgzekucji umorzenieEgzekucji) {
    this.umorzenieEgzekucji = umorzenieEgzekucji;
  }

  public Zaleglosci wysokoscZaleglosci(WysokoscZaleglosci wysokoscZaleglosci) {
    this.wysokoscZaleglosci = wysokoscZaleglosci;
    return this;
  }

   /**
   * Get wysokoscZaleglosci
   * @return wysokoscZaleglosci
  **/
  @Schema(description = "")
  public WysokoscZaleglosci getWysokoscZaleglosci() {
    return wysokoscZaleglosci;
  }

  public void setWysokoscZaleglosci(WysokoscZaleglosci wysokoscZaleglosci) {
    this.wysokoscZaleglosci = wysokoscZaleglosci;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Zaleglosci zaleglosci = (Zaleglosci) o;
    return Objects.equals(this.charakterZaleglosci, zaleglosci.charakterZaleglosci) &&
        Objects.equals(this.zakonczenieEgzekucji, zaleglosci.zakonczenieEgzekucji) &&
        Objects.equals(this.wszczecieEgzekucji, zaleglosci.wszczecieEgzekucji) &&
        Objects.equals(this.umorzenieEgzekucji, zaleglosci.umorzenieEgzekucji) &&
        Objects.equals(this.wysokoscZaleglosci, zaleglosci.wysokoscZaleglosci);
  }

  @Override
  public int hashCode() {
    return Objects.hash(charakterZaleglosci, zakonczenieEgzekucji, wszczecieEgzekucji, umorzenieEgzekucji, wysokoscZaleglosci);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Zaleglosci {\n");
    
    sb.append("    charakterZaleglosci: ").append(toIndentedString(charakterZaleglosci)).append("\n");
    sb.append("    zakonczenieEgzekucji: ").append(toIndentedString(zakonczenieEgzekucji)).append("\n");
    sb.append("    wszczecieEgzekucji: ").append(toIndentedString(wszczecieEgzekucji)).append("\n");
    sb.append("    umorzenieEgzekucji: ").append(toIndentedString(umorzenieEgzekucji)).append("\n");
    sb.append("    wysokoscZaleglosci: ").append(toIndentedString(wysokoscZaleglosci)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
