/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
/**
 * Dane dla przypadków faktur dokumentujących otrzymanie więcej niż jednej płatności, o której mowa w art. 106b ust. 1 pkt 4 ustawy. W przypadku, gdy faktura, o której mowa w art. 106f ust. 3 ustawy dokumentuje jednocześnie otrzymanie części zapłaty przed dokonaniem czynności, różnica kwoty w polu P_15 i sumy poszczególnych pól P_15Z stanowi kwotę pozostałą ponad płatności otrzymane przed wykonaniem czynności udokumentowanej fakturą
 */
@Schema(description = "Dane dla przypadków faktur dokumentujących otrzymanie więcej niż jednej płatności, o której mowa w art. 106b ust. 1 pkt 4 ustawy. W przypadku, gdy faktura, o której mowa w art. 106f ust. 3 ustawy dokumentuje jednocześnie otrzymanie części zapłaty przed dokonaniem czynności, różnica kwoty w polu P_15 i sumy poszczególnych pól P_15Z stanowi kwotę pozostałą ponad płatności otrzymane przed wykonaniem czynności udokumentowanej fakturą")

public class ZaliczkaCzesciowa {
  @JsonProperty("P_6Z")
  private LocalDate p6Z = null;

  @JsonProperty("P_15Z")
  private Double p15Z = null;

  @JsonProperty("KursWalutyZW")
  private Double kursWalutyZW = null;

  public ZaliczkaCzesciowa p6Z(LocalDate p6Z) {
    this.p6Z = p6Z;
    return this;
  }

   /**
   * Get p6Z
   * @return p6Z
  **/
  @Schema(required = true, description = "")
  public LocalDate getP6Z() {
    return p6Z;
  }

  public void setP6Z(LocalDate p6Z) {
    this.p6Z = p6Z;
  }

  public ZaliczkaCzesciowa p15Z(Double p15Z) {
    this.p15Z = p15Z;
    return this;
  }

   /**
   * Get p15Z
   * @return p15Z
  **/
  @Schema(required = true, description = "")
  public Double getP15Z() {
    return p15Z;
  }

  public void setP15Z(Double p15Z) {
    this.p15Z = p15Z;
  }

  public ZaliczkaCzesciowa kursWalutyZW(Double kursWalutyZW) {
    this.kursWalutyZW = kursWalutyZW;
    return this;
  }

   /**
   * Get kursWalutyZW
   * @return kursWalutyZW
  **/
  @Schema(description = "")
  public Double getKursWalutyZW() {
    return kursWalutyZW;
  }

  public void setKursWalutyZW(Double kursWalutyZW) {
    this.kursWalutyZW = kursWalutyZW;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZaliczkaCzesciowa zaliczkaCzesciowa = (ZaliczkaCzesciowa) o;
    return Objects.equals(this.p6Z, zaliczkaCzesciowa.p6Z) &&
        Objects.equals(this.p15Z, zaliczkaCzesciowa.p15Z) &&
        Objects.equals(this.kursWalutyZW, zaliczkaCzesciowa.kursWalutyZW);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p6Z, p15Z, kursWalutyZW);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZaliczkaCzesciowa {\n");
    
    sb.append("    p6Z: ").append(toIndentedString(p6Z)).append("\n");
    sb.append("    p15Z: ").append(toIndentedString(p15Z)).append("\n");
    sb.append("    kursWalutyZW: ").append(toIndentedString(kursWalutyZW)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
