/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ZawieszenieWznowienie
 */


public class ZawieszenieWznowienie {
  @JsonProperty("dataZawieszenia")
  private String dataZawieszenia = null;

  @JsonProperty("dataWznowienia")
  private String dataWznowienia = null;

  public ZawieszenieWznowienie dataZawieszenia(String dataZawieszenia) {
    this.dataZawieszenia = dataZawieszenia;
    return this;
  }

   /**
   * Get dataZawieszenia
   * @return dataZawieszenia
  **/
  @Schema(description = "")
  public String getDataZawieszenia() {
    return dataZawieszenia;
  }

  public void setDataZawieszenia(String dataZawieszenia) {
    this.dataZawieszenia = dataZawieszenia;
  }

  public ZawieszenieWznowienie dataWznowienia(String dataWznowienia) {
    this.dataWznowienia = dataWznowienia;
    return this;
  }

   /**
   * Get dataWznowienia
   * @return dataWznowienia
  **/
  @Schema(description = "")
  public String getDataWznowienia() {
    return dataWznowienia;
  }

  public void setDataWznowienia(String dataWznowienia) {
    this.dataWznowienia = dataWznowienia;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZawieszenieWznowienie zawieszenieWznowienie = (ZawieszenieWznowienie) o;
    return Objects.equals(this.dataZawieszenia, zawieszenieWznowienie.dataZawieszenia) &&
        Objects.equals(this.dataWznowienia, zawieszenieWznowienie.dataWznowienia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataZawieszenia, dataWznowienia);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZawieszenieWznowienie {\n");
    
    sb.append("    dataZawieszenia: ").append(toIndentedString(dataZawieszenia)).append("\n");
    sb.append("    dataWznowienia: ").append(toIndentedString(dataWznowienia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
