/*
 * NIP24 Service
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pl.nip24.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Zwolnienie
 */


public class Zwolnienie {
  @JsonProperty("P_19")
  private Integer p19 = null;

  @JsonProperty("P_19A")
  private String p19A = null;

  @JsonProperty("P_19B")
  private String p19B = null;

  @JsonProperty("P_19C")
  private String p19C = null;

  @JsonProperty("P_19N")
  private Integer p19N = null;

  public Zwolnienie p19(Integer p19) {
    this.p19 = p19;
    return this;
  }

   /**
   * Get p19
   * @return p19
  **/
  @Schema(description = "")
  public Integer getP19() {
    return p19;
  }

  public void setP19(Integer p19) {
    this.p19 = p19;
  }

  public Zwolnienie p19A(String p19A) {
    this.p19A = p19A;
    return this;
  }

   /**
   * Get p19A
   * @return p19A
  **/
  @Schema(description = "")
  public String getP19A() {
    return p19A;
  }

  public void setP19A(String p19A) {
    this.p19A = p19A;
  }

  public Zwolnienie p19B(String p19B) {
    this.p19B = p19B;
    return this;
  }

   /**
   * Get p19B
   * @return p19B
  **/
  @Schema(description = "")
  public String getP19B() {
    return p19B;
  }

  public void setP19B(String p19B) {
    this.p19B = p19B;
  }

  public Zwolnienie p19C(String p19C) {
    this.p19C = p19C;
    return this;
  }

   /**
   * Get p19C
   * @return p19C
  **/
  @Schema(description = "")
  public String getP19C() {
    return p19C;
  }

  public void setP19C(String p19C) {
    this.p19C = p19C;
  }

  public Zwolnienie p19N(Integer p19N) {
    this.p19N = p19N;
    return this;
  }

   /**
   * Get p19N
   * @return p19N
  **/
  @Schema(description = "")
  public Integer getP19N() {
    return p19N;
  }

  public void setP19N(Integer p19N) {
    this.p19N = p19N;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Zwolnienie zwolnienie = (Zwolnienie) o;
    return Objects.equals(this.p19, zwolnienie.p19) &&
        Objects.equals(this.p19A, zwolnienie.p19A) &&
        Objects.equals(this.p19B, zwolnienie.p19B) &&
        Objects.equals(this.p19C, zwolnienie.p19C) &&
        Objects.equals(this.p19N, zwolnienie.p19N);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p19, p19A, p19B, p19C, p19N);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Zwolnienie {\n");
    
    sb.append("    p19: ").append(toIndentedString(p19)).append("\n");
    sb.append("    p19A: ").append(toIndentedString(p19A)).append("\n");
    sb.append("    p19B: ").append(toIndentedString(p19B)).append("\n");
    sb.append("    p19C: ").append(toIndentedString(p19C)).append("\n");
    sb.append("    p19N: ").append(toIndentedString(p19N)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
